### ISSUE TITLE
Resolve Action<T>

### ISSUE THREAD

**Issue by Artusoft** [dadhi/DryIoc#114]
Hi, with the version >= 4.0.1 this code not working any more:

`	var container = new Container();

	container.RegisterInstance<Action<String>>((s => Console.WriteLine("1-{0}", s)), ifAlreadyRegistered: IfAlreadyRegistered.AppendNotKeyed);
	container.RegisterInstance<Action<String>>((s => Console.WriteLine("2-{0}", s)), ifAlreadyRegistered: IfAlreadyRegistered.AppendNotKeyed);

	var actions = container.ResolveMany<Action<String>>();

	actions.ToList().ForEach(a => a.Invoke("Hello world"));`

The "actions" collection is always empty.
Thank's

**Comment by dadhi** [comment]
Thanks for reporting, will check.

**Comment by dadhi** [comment]
DryIoc v4.0.3 with the fix is out
