### ISSUE TITLE
Reuse.InWebRequest

### ISSUE THREAD

**Issue by zsender** [dadhi/DryIoc#115]
Hello. I have a problem with **Reuse.InWebRequest**. The project was version 1.3.0. Moved to version 4.0.3
I downloaded your project for an example [https://github.com/dadhi/DryIoc/blob/master/samples/DryIoc.AspNetCore.Sample/Startup.cs](url)
Added a simple code

`public interface IRequestService { }`
`public class RequestService : IRequestService  {}`

Than registered in MyCompositionRoot
`r.Register<IRequestService, RequestService>(Reuse.InWebRequest);`

In HomeControlled added service to constructor
`public HomeController(IRequestService requestService, IScopedService scoped, ITransientService transient, IExportedService imported = null)
        {
            _requestService = requestService;
           // to do ...
        }`

For the test, I removed the rest of the services from the constructor
`public HomeController(IRequestService requestService)
        {
            _requestService = requestService;
        }`

A get an error
**Unable to find matching scope with name "~WebRequestScopeName" starting from the current scope {no name}**

How to register ** Reuse.InWebRequest**

**Comment by dadhi** [comment]
Shorty put, use the `Reuse.Scoped`. This is how ASP .NET Core is working. There is no special request level scope, all levels are treated equally.

**Comment by zsender** [comment]
Thanks for the answer. I just have a project on .NET CORE 2.2.0, DryIoc.Microsoft.DependencyInjection version 1.3.1, DryIoc version 2.12.1 and everything worked correctly for `Reuse.InWebRequest`.

I really liked the option of creating a single instance for the life of the request

**Comment by zsender** [comment]
After several tests it seems that they (Scoped and InWebRequest) work the same way. This option suits me. Thanks for the help
