### ISSUE TITLE
Validate issue

### ISSUE THREAD

**Issue by molinch** [dadhi/DryIoc#118]
@dadhi First of all thanks a lot, DryIoc is really fast, but also very easy to use.

We use it and have multiple scopes defined:
- "global"
   - then thread scoped
       - then custom scoped

We always call Validate, and just found one case where Validate wouldn't spot an issue:
- class CS is custom scoped
- class TS is thread scoped, its constructor requires CS

In theory that shouldn't be OK: TS has a more general scope/lifetime, it shouldn't be able to use CS.

In practice it works and it's really bad: TS will be constructed with an instance of CS.
TS has a longer lifetime but it will still hold CS which shouldn't be used anymore.

Do you think we could throw an exception during Validate for such cases?

**Comment by dadhi** [comment]
You have a very specific setup here.
Maybe it make sense to add a pluggable Validation rule.. or could you check the validity of reuse within `IReuse.CanApply` implementation?

Do you use a custom `IReuse` implementation or just a scope with the special name?

**Comment by molinch** [comment]
We don't use a custom IReuse implementation, but now that I think about what we do, for sure Validate cannot enforce anything... It's our fault for assuming that.
However I still believe this misconfiguration could be detected during runtime when resolving things.
What is your opinion?

Our registration is kind of like:
```c#
using DryIoc;
using System;

namespace TestDryIoc
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var container = new Container())
            {
                container.Register<SomethingDefinedInOuterScope>(Reuse.InCurrentNamedScope("Outer"));
                container.Register<SomethingDefinedInInnerScope>(Reuse.InCurrentNamedScope("Inner"));
                container.Validate();

                using (var outerScopedContainer = container.OpenScope(name: "Outer"))
                {
                    using (var innerScopedContainer = container.OpenScope(name: "Inner"))
                    {
                        var item = container.Resolve<SomethingDefinedInOuterScope>();
                    }
                }
            }

            Console.WriteLine("Hello World!");
        }
    }


    class SomethingDefinedInOuterScope
    {
        public SomethingDefinedInOuterScope(SomethingDefinedInInnerScope dependency) // we were expecting DryIoC to not allow that, it's wrong since the dependency has a tighter lifetime
        {

        }
    }


    class SomethingDefinedInInnerScope
    {

    }
}
```

**Comment by dadhi** [comment]
Yep, now it is much clearer. Need to think about this.

**Comment by dadhi** [comment]
@molinch 
Was thinking how to address this issue.
The main problem is that we are not defining the scope hierarchy in registration - the `Reuse.ScopedTo(name)` is just a binding to that named scoped. It may be perfectly valid to have this named scope in unnamed scope and the vice versa.

So probably the validity should be defined externally via some validation rules applied to container. `Validate` may provide the rules as a sugar for thing like this `Rules.WithValidation(
req => req.Reuse.Name != null && req.Parent != null && req.Parent.Reuse.Name == null ? Error.Of("Hey, stop!") : null)`

**Comment by dadhi** [comment]
Given that situation with ensuring the scope hierarchy is quite common (see https://stackoverflow.com/questions/60092293/dryioc-scope-and-reuse) maybe we can add a sugar `ValidateScopeHierarchy(name1, name2)`.
Maybe it can validate opening scopes too, hmm...

**Comment by dadhi** [comment]
> Maybe it can validate opening scopes too, hmm...

I am not sure that it is useful anymore because the check is happen at runtime operation - when the scope is opening and not in validation phase.

Regarding the check maybe its enough to expose the `Lifetime` in `Reuse.Scoped(lifetime: Reuse.DefaultScopedLifetime - 1)`

**Comment by dadhi** [comment]
Another interesting idea is to remove the runtime checks after `Validate()` is called.
Why to double-check?
To ensure that container is not changed after `Validate` DryIoc already has a thing c.WithNoMoreRegistrationAllowed()`
