### ISSUE TITLE
V4.0.3 double dryioc break the build

### ISSUE THREAD

**Issue by ilgb** [dadhi/DryIoc#120]
The Dryioc Nuget package install a link to Dryioc source code in project, but if you use Dryioc in 2 projects (class lib net standard 2.0) in same solution with one that refer the other, it break the compilation with many error CS0121.

**Comment by dadhi** [comment]
- That's why you should use lib **DryIoc.dll** package, 
- or use source **DryIoc** package in composition root project only (and the rest should be IoC agnostic)
- or use source **DryIoc.Internal** package where the DryIoc public types made internal and not visible across the project boundary.
