### ISSUE TITLE
FastExpressionCompiler.cs and Expression.cs code comment out in .NetFramework 4.7

### ISSUE THREAD

**Issue by stevensrf11** [dadhi/DryIoc#121]
When using .Net Framework 4.7 the code is commented in the FastExpressionCompiler.cs and Expression.cs files.
 Is Dryioc not fully compatiable for ,Net Framework 4.7.?
In both of these  files this is shown if .Net Framework 4.7 used
// ReSharper disable CoVariantArrayConversion
#if NET45 || NETSTANDARD1_3 || NETSTANDARD2_0

Should Dryioc only be used in .NetFramework 4.5?

**Comment by dadhi** [comment]
Nope. But if you are using the source package the compile vars are not covering all platform variants. Will fix. 
But for now you may add NET47 yourself.
