### ISSUE TITLE
The name 'AsyncExecutionFlowScopeContext' does not exist in the current context when using nuget

### ISSUE THREAD

**Issue by stevensrf11** [dadhi/DryIoc#122]
The compile error shown appears when using nuget install Dryioc, Dryioc.Mvc, and Dryioc.Web.
Why does this happen?
The name 'AsyncExecutionFlowScopeContext' does not exist in the current context
The error occurs in the drylocmvc.cs file,
The compile error is on AsyncExecutionFlowScopeContext.Default;
Do I have to create this AsyncExecutionFlowScopeContext class

 public class AsyncExecutionFlowScopeContextRequestHandler : IDryIocHttpModuleRequestHandler
    {
        /// Uses a default instance of shared scope context that can be propagated throw async / await boundaries
        internal static IScopeContext DefaultScopeContext = AsyncExecutionFlowScopeContext.Default;

**Comment by dadhi** [comment]
Are you on .NET 4.7 ?

**Comment by stevensrf11** [comment]
yes net framework 4.7 and visual studio 2017

**Comment by Havunen** [comment]
I encountered the same error. net framework 4.6.1, I ended up cloning the source codes...
