### ISSUE TITLE
DryIoc.Mvc.TestApp-master\C#\MvcMovie\DryIoc sample example dryloc folder completely different then what installed by nuget 

### ISSUE THREAD

**Issue by stevensrf11** [dadhi/DryIoc#123]
Now this is really weird.
The MvcMovie download test example has the following files in the dryloc folder:
AsyncExecutionFlowScopeContext.cs
Container.cs
FactoryCompiler.cs
InternalsVisibleToDryIocFactoryCompilerDynamicAssembly.cs

Where as the nuger dryioc packages the following files in the dryioc folder
Container.cs
FastExpressionCompiler.cs
Expression.cs
ImTools.cs

Two of these files code is commented out if .Net Framework is 4.7

WHY SUCH THE MISS MATCH

**Comment by dadhi** [comment]
What sample did you compare with? Could provide the links?

**Comment by stevensrf11** [comment]
In Visual Studio 2017 create a new mvc .Net Framework 7 web application.
Using nuget add dryioc,dryioc.mvc and dryioc.web.
Then try to compile the application you will notice the compile errors the dryioc nuget packages introduce.
Look in the dryioc folder create you will notice in two of the files added by the dryioc package all the code is commented out. I am not sure if this done by resharper  or not still it is a bug in dryioc if it is.

Now look at the mvc test app in the dryico download, The application is titled MVCMovieRTM.
If I remember it did not compile either the first time.
https://github.com/dadhi/DryIoc.Mvc.TestApp
![dryiocnugetpackagecodecommentedout](https://user-images.githubusercontent.com/22349374/56851899-ffc80000-68d9-11e9-9de6-fd77fb7f82eb.png)
![dryiocnugetpackagecoompilerror](https://user-images.githubusercontent.com/22349374/56851904-08b8d180-68da-11e9-8e7f-8a0bf5927f89.png)

![dryiocnugetpackagefilesvssamplemvcappondryiocwebsite](https://user-images.githubusercontent.com/22349374/56852022-3d795880-68db-11e9-8b18-c53c61a55411.png)

**Comment by dadhi** [comment]
Ok, I need to check that again.

**Comment by dadhi** [comment]
The content packages work different now in the latest VS, so closing.
