### ISSUE TITLE
Question: Why DryIoC throws Exception if registering two classes with common base?

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#125]
Hi,

Why DryIoc throws when registering two classes with their own interfaces which share a common base? I wanted to use ifAlreadyRegistered.Throw, to detect duplicate default registrations  which might be the reason for https://github.com/dadhi/DryIoc/issues/124

When having following setup:
```c#
public class Class1 : CommonBase, IClass1
{
	public string Greet()
	{
		return "Framework";
	}
}

public class Class2 : CommonBase, IClass2
{
	public string Speak()
	{
		return "Framework";
	}
}

interface IClass1
{
	string Greet();
}

interface IClass2
{
	string Speak();
}

public abstract class CommonBase
{
}
```

Registration part:

```c#
var container = new Container((rules) => rules.With(FactoryMethod.ConstructorWithResolvableArguments));

// Register everything from framework
var fwTypes = typeof(framework.Class1).GetAssembly().GetLoadedTypes().Where(
	(t) => !t.IsInterface && !t.IsAbstract
);
container.RegisterMany(fwTypes, ifAlreadyRegistered: IfAlreadyRegistered.Throw);
```

And then registering everything from that assembly, filtering out the abstract base class, dryIOC throws error.

```
DryIoc.ContainerException: 'The default service framework.CommonBase without key {FactoryID=28, ImplType=framework.Class2} is already registered as {FactoryID=27, ImplType=framework.Class1}.'
```

Is this expected behavior? Why does it happen? I have filtered out `CommonBase` using "isAbstract" filter. 

Thanks,
Havunen

**Comment by Havunen** [comment]
@dadhi Can you please have a look at this issue? Am I doing something wrong here or is this bug in DryIoc? I`m trying to do real world benchmark comparing dryIoc to Autofac and this is blocker for me to proceed the migration. I will post results here how dryIoc affects latency and throughput of the server If I can get it working. :)

**Comment by dadhi** [comment]
Hi, I don't see a reason for this behavior from the example. Likely a bug.
You may add the minimal failing test into `DryIoc.IssuesTests` project and submit a PR. This will greatly speedup my fix Or you may try to fix it yourself, which is the fastest route to release.

Check the https://github.com/dadhi/DryIoc/blob/master/CONTRIBUTING.md guide for general guidelines.

**Comment by dadhi** [comment]
@Havunen,

I have added the test my self and apparently, there is the problem with your setup.

```cs
var fwTypes = typeof(framework.Class1).GetAssembly().GetLoadedTypes().Where(
	(t) => !t.IsInterface && !t.IsAbstract
);
```

The above types are passed to register many as **implementation** types. 
```cs
container.RegisterMany(fwTypes, ifAlreadyRegistered: IfAlreadyRegistered.Throw);
```

It does not mean RegisterMany won't try to use the interfaces and abstract classes as a **service** type.
To prevent it you need to pass a `serviceTypeCondition`:

```cs
container.RegisterMany(fwTypes,
   serviceTypeCondition: t => !t.IsAbsract, // excludes CommonBase class 
   ifAlreadyRegistered: IfAlreadyRegistered.Throw);
```

**Comment by Havunen** [comment]
@dadhi Oh, thanks a lot! I need to test that out :)

**Comment by dadhi** [comment]
@Havunen, Btw, be careful with non-public service types like in case of `IClass1` and `IClass` definitions.
You need to either make them `public` (why are they `internal` anyway?) or pass `nonPublicServiceTypes: true` to `RegisterMany`.

**Comment by Havunen** [comment]
@dadhi Yeah they should have been public, it was error in the test case here

**Comment by dadhi** [comment]
@Havunen, Added the test with a working sample.

**Comment by Havunen** [comment]
Thanks :)
