### ISSUE TITLE
Throw in same method as check may be 3 times slower (and used in hot paths, seems)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/DryIoc#127]
May be slow:

https://github.com/dadhi/DryIoc/blob/c2729e5e4d05be1143f95266d97efa986b032581/src/DryIoc/Container.cs#L10611

Seems right:
https://github.com/dotnet-fun/dotnet-system-except/blob/master/src/GenericClassExtensions.cs
https://github.com/dotnet-fun/dotnet-system-except/blob/master/benchmarks/NonNullVariants.cs

.NET Core 3 does not fixes it either. No seems it will be fixed..

**Comment by dadhi** [comment]
Need to benchmark a different approach against the current `Thow.It`

**Comment by dadhi** [comment]
Too small of thing to worry at the moment
