### ISSUE TITLE
Register Delegate throw's StackOverflow

### ISSUE THREAD

**Issue by dansiegel** [dadhi/DryIoc#128]
### Description

I'm working on some general container abstractions. With this the goal is to be able to provide a registration like:

```cs
void Register<T>(Func<IServiceProvider, T> factoryMethod)
{
    c.RegisterDelegate(typeof(T), r => factoryMethod(r.Resolve<IServiceProvider>());
}
```

The issue is when you call `c.Resolve<T>()` it appears to throw a StackOverflow thus killing my unit tests.

**Comment by dansiegel** [comment]
For reference you can see the tests in the [Prism.Container.Extensions](https://github.com/dansiegel/Prism.Container.Extensions/blob/master/tests/Prism.DryIoc.Extensions.Tests/ContainerTests.cs#L193-L209) repo.

**Comment by dadhi** [comment]
If `IServiceProvider` is MS one, then u don't need to resolve it, `r`esolver is already implementing it.

```cs
c.RegisterDelegate(typeof(T), r => factoryMethod(r));
```

For the rest will look when I have time. I am on vacation till 20th of May.

**Comment by dansiegel** [comment]
tried updating the one for IServiceProvider which yes it is the MS one, and what you have shown there seems to be throwing a SO Exception still because it totally kills the test runner the second I try to resolve the type.

**Comment by dadhi** [comment]
@dansiegel,

The sample is working for me: https://dotnetfiddle.net/46ZoI4

Could you make it fail?

**Comment by dansiegel** [comment]
not sure entirely what the issue was but I was able to get this resolved. Thanks!
