### ISSUE TITLE
Does .WithDependencyInjectionAdapter() really return a new container?

### ISSUE THREAD

**Issue by saciervo** [dadhi/DryIoc#129]
The documentation of `.WithDependencyInjectionAdapter()` claims that it adapts the passed container to Microsoft.DependencyInjection conventions, registers DryIoc implementations of `IServiceProvider` and `IServiceScopeFactory`, and returns NEW container.

But consider this code:

```
var container = tempContainer.WithDependencyInjectionAdapter(services, registerDescriptor);
tempContainer.Dispose();
container.Resolve<IFoo>();
```

Resolving IFoo ends up in an exception:

> DryIoc.ContainerException: 'Container is disposed and should not be used: "Container without Scope
 with Rules with {TrackingDisposableTransients, SelectLastRegisteredFactory} and without {ThrowOnRegisteringDisposableTransient}
 with FactorySelector=SelectLastRegisteredFactory
 with Made={FactoryMethod=ConstructorWithResolvableArguments} has been DISPOSED!
 You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace())"'

This would mean `tempContainer` is still in use inside the (adapted) `container`...  

But in my scenario, `tempContainer` is only used up to this point and **must not** be used further, hence the `Dispose()`. So I really need a new container. Is there a way to copy the registrations from `tempContainer` to another one? Resulting my code in something like this:

```
var container = new Container().CopyFrom(tempContainer).WithDependencyInjectionAdapter(services, registerDescriptor);
tempContainer.Dispose();
container.Resolve<IFoo>();
```

**Comment by dadhi** [comment]
You can use `.WithRegistrationsCopy()` or the underlying `.With(...)` method.

**Comment by saciervo** [comment]
Oh nice, didn't notice the method. So I wrote it like this:

```
var container = new Container().WithRegistrationsCopy(tempContainer).WithDependencyInjectionAdapter(services, registerDescriptor);
tempContainer.Dispose();
container.Resolve<IFoo>();
```

But it still throws the same exception.

**Comment by dadhi** [comment]
Strange, will check.

**Comment by saciervo** [comment]
Thanks, it looks like it works 👍

**Comment by CoskunSunali** [comment]
Sorry to resurrecting the issue. May I ask where did you get the `.CopyFrom(tempContainer)` method? I need to merge two Container instances or at least copy service registrations from one to another. Is there a known or suggested way of accomplishing this?

**Comment by dadhi** [comment]
@Coskun Depending on your case you may use `WithRegistrationsCopy(...)` or just the more powerful `With(...)` method.

**Comment by CoskunSunali** [comment]
@dadhi Thank you for the quick response.

My use case is multi-tenancy.

Imagine that I have two containers, containerParent and containerNew. `containerParent` contains already registered and resolved services. `containerNew` is just registrations and nothing has been resolved from it yet. I am trying to create a final container `containerChild` from those two previously mentioned.

Something like `containerChild = containerParent + containerNew`.

I guess one way of accomplishing this is to create the `containerChild` from `containerParent` using something like `CreateChild` before the new registrations start, make the registrations directly on the `containerChild` (skipping `containerNew`) then finalize it with `WithNoMoreRegistrationAllowed` in the end but I was just wondering if there is an easier way, or a better way.

**Comment by dadhi** [comment]
@CoskunSunali Your plan looks fine to me.

There is no predefined `CopyRegistrations` method yet.. but you may open a new issue with the feature request and the case description.

**Comment by CoskunSunali** [comment]
> Your plan looks fine to me.

Thank you @dadhi, since creating a new container using `CreateChild` is "cheap" based on what you wrote on the related documentation, I will go ahead with the mentioned approach instead of trying to merge two containers. There will not be many of these contains anyway, only a few, probably.

**Comment by CoskunSunali** [comment]
@dadhi, I realize you wrote `There is no predefined CopyRegistrations method yet`, however, I need one it seems. I will create the feature request as per your request but I would still like to make sure, is there a way to manually do it at the moment without getting you involved? If there is one, I will not need the feature request, if there is none, I will create one. Just wanted to make sure first.

**Comment by CoskunSunali** [comment]
P.S. I am looking for something similar to the `Populate` method that gets an `IServiceCollection` but it will get an `IRegistrator`, the complete `IContainer` or the `IResolverContext`, either one works for me. Just looking for a way.

**Comment by dadhi** [comment]
@CoskunSunali  Mmm, currently there is a `GetServiceRegistrations` method. So you need to get all registrations (containing type, key, and factory) and register them in another containet. There is a basic `IRegistrator.Register` method wich accepts the factory. All other Register overloads just a sugar on top of it.

**Comment by dadhi** [comment]
@CoskunSunali Here is the example

```cs
using System;
using DryIoc;
					
public class Program
{
	public static void Main()
	{
		var c = new Container();
		c.Register<A>();
		
		var c2 = new Container();
		foreach (var r in c.GetServiceRegistrations())
		{
			c2.Register(r.Factory, r.ServiceType, r.OptionalServiceKey, IfAlreadyRegistered.AppendNotKeyed, true);
		}
		
		var a = c2.Resolve<A>();
		
		Console.WriteLine(a);
	}
	
	class A {}
}
```

**Comment by CoskunSunali** [comment]
@dadhi Thanks for the example! I will migrate the example to my code tomorrow and will test the functionality. It looks like it will solve my problem.
