### ISSUE TITLE
Make New() method available on IResolver/IResolverContext interface

### ISSUE THREAD

**Issue by thezbyg** [dadhi/DryIoc#13]
Hi,
would it be possible to add New() method to IResolver or IResolverContext interface?
In DryIoc 2.x IContainer interface was used for containers and opened scopes, so code, that only had access to opened scope, could still create objects by calling New(). DryIoc 3.x now returns IResolverContext after opening scope, and there is no way to create an object without previous registration.

Example code that was valid in DryIoc 2.x, but not in DryIoc 3.x:
```
var container = new Container();
container.Register<Dependency>();
using (var scope = container.OpenScope())
{
	//somewhere deep in the code, where container value is not available
	scope.New<Object>();
}
```

Thanks for the great library.

**Comment by dadhi** [comment]
@thezbyg 
I have provided my comments in your PR #14 

You may look at my changes/commits in #8 for making some methods available in `IRegistrator` and why it was possible and non-breaking.

I am open for ideas, but currently, don't see how to move `New` to `IResolver` without breaking major things.

**Comment by dadhi** [comment]
I have closed the PR but let's keep issue open, to wait for better idea.

**Comment by dadhi** [comment]
@thezbyg 
Ok, I completely forgot (in this context) that `IContainer` is [always available](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RulesAndDefaultConventions.md#implicitly-available-services) 👍 

```cs
var container = new Container();
container.Register<Dependency>();
using (var scope = container.OpenScope())
{
	//somewhere deep in the code, where container value is not available
	scope.Resolve<IContainer>.New<Object>();
}
```
