### ISSUE TITLE
Resolving a component for the second time throws 

### ISSUE THREAD

**Issue by pikausp** [dadhi/DryIoc#130]
When a component is resolved for the second time using the `Resolve(Type, object[])` overload it throws `System.MemberAccessException: Cannot create an abstract class: System.Reflection.Emit.DynamicMethod` on iOS (emitting code is not possible there).

Any idea what is happening behind the scenes that causes this exception?

**Comment by dadhi** [comment]
Try this rule:

```cs

container = new Container(rules => rules
    .WithoutFastExpressionCompiler());

```

If only I have a way in compile or runtime to find out that I am on iOS, any ideas?

In addition linking this issue #90.

**Comment by pikausp** [comment]
Hi, this did fix the issue. I'm assuming it creates a performance hit? 

It's possible to check for OSX by using `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)`, but I'm assuming this includes Mac.

**Comment by dadhi** [comment]
This would be a very minor-minor startup hit.
Thanks for the code thingy.
Let's keep this issue open to see how to improve.

**Comment by dadhi** [comment]
.Net Core 3 adding two related capabilities flags IsDynamicCompilationSupported

**Comment by dadhi** [comment]
The v4.1.0-preview-01 is out with `Rules.WithUseInterpretation()` option.
Try it out.
