### ISSUE TITLE
Confusion about UseInstance and RegisterInstance documentation

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#135]
Hey!

Documentation here (https://bitbucket.org/dadhi/dryioc/wiki/RegisterResolve#markdown-header-useinstance) says this
> Note: The DryIoc version prior 3.0 also contains RegisterInstance method. The method is obsolete and its usages should be replaced with UseInstance.

So UseInstance is preferred way? But then I noticed in the source code all UseInstance methods are marked as Obsolete

https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.cs#L5571-L5629

I'm using latest version of DryIoc should I use `useInstance` or `registerInstance` ?

**Comment by dadhi** [comment]
Use `RegisterInstance`, I will update the docs on BB. But the up-to-date version of docs is here: https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RegisterResolve.md#registerinstance

**Comment by Havunen** [comment]
Seems like there are some `useInstace` -usages in official DryIoc packages.
https://github.com/dadhi/DryIoc/blob/9f111e8cc9a65076353e9360a84e553efb661f3d/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L87

https://github.com/dadhi/DryIoc/blob/be545dbd08bd9f750abac3f47225c91d08089bab/src/DryIocZero.WebApi/DryIocWebApi.cs#L71
