### ISSUE TITLE
Disposing a container created with "WithRegistrationsCopy" also disposes the original container

### ISSUE THREAD

**Issue by reinaldoarrosi** [dadhi/DryIoc#136]
If I have the following code

```csharp
var container = new Container();
container.Register<SomeService>(Reuse.Singleton);

var someService1 = container.Resolve<SomeService>();

using(var subContainer = container.WithRegistrationsCopy())
{
    var someService2 = subContainer.Resolve<SomeService>();
}

var someService3 = container.Resolve<SomeService>(); // this lines throws
```

When disposing the subContainer, it also disposes the container.

In #129 it is suggested to use `WithRegistrationsCopy().WithoutSingletonsAndCache()` but then the singleton scope is lost, and `someService2` will not resolve to the same instance as `someService1`.

I believe the correct behavior would be that containers created using `WithRegistrationsCopy` should not share the same singleton scope, but clone the singleton scope from the original container.

If this is considered a breaking change from current behavior, I suggest adding a `WithSingletonsCopy()` method (or something with a similar name).

**Comment by dadhi** [comment]
Maybe you're right. Need to process it.

Until then you may use the underlying `With` method:

```cs

container.With(
    container.Rules, 
    container.ScopeContext,
    RegistrySharing.CloneAndDropCache,
    container.SingletonScope.Clone());
```

Btw, the rest of `With..blah` methods just a sugar on top, kept for backward compatibility.

**Comment by reinaldoarrosi** [comment]
Great! That works for me.

**Comment by dadhi** [comment]
Will close then!

**Comment by dadhi** [comment]
added to the docs: https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/KindsOfChildContainer.md#the-child-container-for-each-test-disposed-at-end-of-the-test-without-disposing-the-parent
