### ISSUE TITLE
Print method has more complex code for Release than Debug

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#138]
There is some really confusing code which looks like error

https://github.com/dadhi/DryIoc/blame/master/src/DryIoc/Container.cs#L11359-L11364

```cs
        /// <summary>Default delegate to print Type details: by default prints Type FullName and
        /// skips namespace if it start with "System."</summary>
        public static Func<Type, string> GetTypeNameDefault = t =>
#if DEBUG
            t.Name;
#else
            t.FullName != null && t.Namespace != null && !t.Namespace.StartsWith("System") ? t.FullName : t.Name;
#endif
```

Is this intended or bug?

**Comment by dadhi** [comment]
Hmm, will check. Maybe it should be vice versa.

**Comment by dadhi** [comment]
It is by design to provide an intellegent (skip well known System ns) and detailed (use FullName) output in Release mode.
In Debug mode I want just a `Name` for shorter output cause I usually know what types are in question.
