### ISSUE TITLE
Container has been DISPOSED! Error

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#140]
Hey,

We are running into error `Container has been DISPOSED!` and I cannot understand what I'm doing wrong. I cannot reproduce this locally but it happens in server, and reproducing the error there can be done quickly by running our test suite.

Here are the relevant files:
```cs
namespace App.IoC
{
	public static class IocUtil
	{
		public static IContainer CreateContainer()
		{
			return new Container((rules) => 
				rules.WithoutFastExpressionCompiler().With(FactoryMethod.ConstructorWithResolvableArguments).WithCaptureContainerDisposeStackTrace()
			);
		}
	}
}

```

We have Web API project and we are using DryIoc.WebAPI

startup file
```vb
<Assembly: OwinStartup(GetType(Startup))>
Partial Public Class Startup
    Public Sub Configuration(app As IAppBuilder)
        Me.ConfigureCors(app)
        ConfigureOAuth(app)
        Dim config = System.Web.Http.GlobalConfiguration.Configuration
        SetIocRegistrations(config)
        app.UseWebApi(config)
       '
       ' Lots of other non-related configs happen here
       '
       GlobalConfiguration.Configuration.EnsureInitialized()
    End Sub

Private Sub SetIocRegistrations(config As HttpConfiguration)
	' Create container and call dryIoc.WithWebApi
	Dim container = IocUtil.CreateContainer().WithWebApi(config)

	' Set container to cache
	Framework.DependencyResolver.SetContainer(container)
		
	' All IoC registrations
	RestApiIocModule.Load(container)

	' previously we were using AutoFac 
	' container.BeginLifetimeScope(Autofac.Core.Lifetime.MatchingScopeLifetimeTags.RequestLifetimeScopeTag)
	Using scope = container.OpenScope(Reuse.WebRequestScopeName, True)
		Dim service1 = scope.Resolve(Of IService1)()
		Dim service2 = scope.Resolve(Of IService2)()
		Dim service3 = scope.Resolve(Of IService3)()
		Dim service4 = scope.Resolve(Of IService4)()

		config.Filters.Add(New CustomFilterAttribute(service1, service2, service3, service4))
	End Using
End Sub
```

Error Message
`
Message: Container is disposed and should not be used: "Container with ambient ScopeContext DryIoc.AsyncExecutionFlowScopeContext with Scope {Name=~WebRequestScopeName} with Rules with {CaptureContainerDisposeStackTrace} and without {UseFastExpressionCompilerIfPlatformSupported} with Made={FactoryMethod=ConstructorWithResolvableArguments} has been DISPOSED! You may include Dispose stack-trace into the message via: container.With(rules => rules.WithCaptureContainerDisposeStackTrace())"
`

Stack:
```
DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3):0
DryIoc.Container.ThrowIfContainerDisposed():28
DryIoc.Container.WithCurrentScope(IScope scope):0
DryIoc.WebApi.DryIocDependencyResolver.BeginScope():0
System.Net.Http.HttpRequestMessageExtensions.GetDependencyScope(HttpRequestMessage request):46
DryIoc.WebApi.RegisterRequestMessageHandler.RegisterInDependencyScope(HttpRequestMessage request):0
DryIoc.WebApi.RegisterRequestMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):0
System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):25
System.Web.Http.HttpServer+<SendAsync>d__24.MoveNext():214
```

Any ideas?

Thanks,
Havunen

**Comment by Havunen** [comment]
I have also tried 
```vb
app.UseDryIocWebApi() instead app.UseWebApi()
```

That resulted into the same error with little bit longer stack
```
DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3):0
DryIoc.Container.ThrowIfContainerDisposed():28
DryIoc.Container.WithCurrentScope(IScope scope):0
DryIoc.WebApi.DryIocDependencyResolver.BeginScope():0
System.Net.Http.HttpRequestMessageExtensions.GetDependencyScope(HttpRequestMessage request):46
DryIoc.WebApi.RegisterRequestMessageHandler.RegisterInDependencyScope(HttpRequestMessage request):0
DryIoc.WebApi.RegisterRequestMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):0
System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):25
DryIoc.WebApi.Owin.SetRequestDependencyScopeHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):40
System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):25
System.Web.Http.HttpServer+<SendAsync>d__24.MoveNext():214
```

**Comment by Havunen** [comment]
I will try `DryIocOwin -> app.UseDryIocOwinMiddleware()` see if that makes any difference

**Comment by Havunen** [comment]
When using `app.UseDryIocOwinMiddleware()` debugger stops quite many times here:
https://github.com/dadhi/DryIoc/blob/65d45f0c6444bff9f4d9b22b9a7b8e8c26580a1c/src/DryIoc.Owin/DryIocOwin.cs#L85

To exception:
`System.OperationCanceledException: 'The operation was canceled.'`

Call stack 
External code.

I think that happens when web request is aborted from client.

**Comment by Havunen** [comment]
`UseDryIocOwinMiddleware` did not solve the problem

**Comment by dadhi** [comment]
If it is a client issue, you may just catch the DryIoc exception and handle it as a part of failed request.

I will try to look, but not so soon. The code in Web extensions is quite simple, so you may play with it directly on your side.

**Comment by Havunen** [comment]
Based on the error it seems that the main container gets disposed ... :/ I cannot reproduce this locally, I will try do remote debugging on the server to see why it happens

**Comment by Havunen** [comment]
Remotely debugging I have found out that Container `_disposed` integer is still 0, but `_singletonScope.IsDisposed` is true. I will try to figure out next why that happens

**Comment by Havunen** [comment]
Omg... I found the reason one developer had made custom integrations to DryIoc - HangFire and that disposes main container... Sorry for this noise...
