### ISSUE TITLE
Q: IDisposable objects - how to handle them?

### ISSUE THREAD

**Issue by richbryant** [dadhi/DryIoc#141]
Just a question.

If I have a class instantiated as transient by DryIoc and that class has several properties which implement IDisposable (specifically, these are IObservable<T> implementations from the Reactive Extensions library), are there any special steps I should take to ensure these properties are disposed?

**Comment by dadhi** [comment]
Are you disposing of these properties in your class `Dispose` method?

**Comment by richbryant** [comment]
I can, certainly.  Would you recommend that?  If I do, will DryIoC invoke the Dispose method when disposing?

**Comment by dadhi** [comment]
https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ReuseAndScopes.cs#L57

**Comment by richbryant** [comment]
Thank you!
