### ISSUE TITLE
Add DI support for Webforms application

### ISSUE THREAD

**Issue by Im-PJ** [dadhi/DryIoc#143]
Starting with .NET 4.7.2 Webforms projects supports DI, there is an example for using Unity here https://github.com/aspnet/AspNetWebFormsDependencyInjection

I would like to use DryIOC with Webforms. Similar to the abov, Can DryIOC container adapter for webforms be provided. I have tried but its confusing. Atleast a sample project would help.

**Comment by dadhi** [comment]
Did you try [DryIoc.Web.dll](https://www.fuget.org/packages/DryIoc.Web.dll) package?

**Comment by Im-PJ** [comment]
Yes.. I have added above package to my webforms application. After that I followed this tutorial to set it up. 
[It uses Autofac but I tried similar steps with DryIOC]( https://www.natmarchand.fr/aspnet-dependency-injection-net472/)

However I'm getting error which is something related to dynamically feeding registrations. I'm pasting relevant lines from that tutorial for better understanding.

> we have to build an adapter that wraps the Autofac container and forwards. So we call Autofac if the type is registered else we rely on the Activator class. However, it won’t work well. In fact, Webform subclass the Webform objects (Pages, UserControls, MasterPage) at runtime making them impossible to register in the ContainerBuilder. Therefore, for all those objects we are going to end up in the case with the Activator.

> Hopefully, Autofac provides a way to dynamically declare registrations using the concept of RegistrationSource. By implementing one, we can then register at runtime our Webforms objects.

This is the RegistrationSource example of Autofac. Using Autofac with this concept works well in my application but I'm not able to use DryIOC in similar steps. 

`public class WebFormRegistrationSource : IRegistrationSource
    {
        public IEnumerable<IComponentRegistration> RegistrationsFor(Service service, Func<Service, IEnumerable<IComponentRegistration>> registrationAccessor)
        {
            if (service is IServiceWithType serviceWithType && serviceWithType.ServiceType.Namespace.StartsWith("ASP", true, CultureInfo.InvariantCulture))
            {
                return new[]
                {
                    RegistrationBuilder.ForType(serviceWithType.ServiceType).CreateRegistration()
                };
            }

            return Enumerable.Empty<IComponentRegistration>();
        }

        public bool IsAdapterForIndividualComponents => true;
    }`

If you can show how to achieve above code with DryIOC or any sample webforms project showing how DryIOC works, it would be highly useful. But it depends on your available time. For the moment, I'm using Autofac but would really want to use DryIOC.

**Comment by dadhi** [comment]
I think what you need here is DryIoc dynamic registration which should be similar to Autofac `IRegistrationSource` (https://autofaccn.readthedocs.io/en/latest/advanced/registration-sources.html).

I am lacking the documentation in this regard but here are [small tests](https://github.com/dadhi/DryIoc/blob/be545dbd08bd9f750abac3f47225c91d08089bab/test/DryIoc.UnitTests/DynamicRegistrationsTests.cs) to see how it works.

**Comment by dadhi** [comment]
Added to the docs: https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/FaqAutofacMigration.md#iregistrationsource-and-the-dynamic-registrations

**Comment by kliszaq** [comment]
@Im-PJ @dadhi 
Is there any chance to provide complete guide how to integrate DryIoC with the ASP.NET forms with the version >= 4.7.2 ?

kind regards,
Kamil

**Comment by dadhi** [comment]
I have a very little time to do it myself, but you can start fro the DryIoc.Web.dll package and I will help.

**Comment by dadhi** [comment]
closing.. but I would consiser fhe PRs
