### ISSUE TITLE
Strange facade and Use behaviour

### ISSUE THREAD

**Issue by amazedevil** [dadhi/DryIoc#149]
I run this code:

```c#
class A {
    public int c = 0;
}

class Program {
    static void Main(string[] args) {
        IContainer c = new Container();

        var f = c.CreateFacade();

        var a = new A() { c = 1 };

        f.Use(a);

        var f2 = c.CreateFacade();

        var a2 = new A() { c = 2 };

        f2.Use(a2);

        Console.Write("f: " + f.Resolve<A>().c + "\n");
        Console.Write("f2: " + f2.Resolve<A>().c + "\n");
        Console.Write("fp: " + c.Resolve<A>().c + "\n");

        Console.ReadKey();
    }
}
```

and, to my surprise, get following output:

```
f: 2
f2: 2
fp: 2
```

I would expect facades to store there own versions of A (as they are "standalone normal containers" according to docs), but instead, it's registration is falling through to c. I can't find any explanation of such behavour in documentation, maybe I've missed something, but if not - I think it's a bug of system or documentation.

**Comment by dadhi** [comment]
Thanks, will check.

**Comment by dadhi** [comment]
The documentation is wrong, will update. Thanks for finding.
