### ISSUE TITLE
Validate Call fails with OpenGeneric Registrations

### ISSUE THREAD

**Issue by Fruchuxs** [dadhi/DryIoc#15]
Originally from BitBucket, because I love the idea to migrate to GitHub: 
https://bitbucket.org/dadhi/dryioc/issues/597/validate-call-fails-with-opengeneric

**Comment by dadhi** [comment]
Just in time, this was fixed last Friday, and will be a part of v3.1 release.

**Comment by Fruchuxs** [comment]
Sorry for my late response, but I was occupied.


From @dadhi 
> Mmm, open-generic resolutions is not possible indeed, until you specify a concrete type arguments. How do you call a Validate?
> 
> Btw, if this is the only error - it may be safely ignored. Or better, you should be more specific about resolution roots to validate. e.g. narrow them to controllers for Web app.

For completness: We use the validate-Method just to test all service registrations in a Nunit-Test Case. If the test fails, we can check the message and adjust the regstration. Otherwhise we remove the registration from the test container. But to do this für all open generics is a little bit danger.

But thanks, I will await your release. :)

**Comment by dadhi** [comment]
fixed here: https://github.com/dadhi/DryIoc/commit/08af6540054a7fade1f75d032feafcfafeb5a83c
