### ISSUE TITLE
AutoConcreteTypeResolution should not consider a primitive type

### ISSUE THREAD

**Issue by jkvargas** [dadhi/DryIoc#16]
Follows the error in the comment,
I suppose that I must register something regarding that function: Func<String, Microsoft.Extensions.Logging.LogLevel, Boolean>. Can you guys provide me some direction? =)

Btw, I am using DryIoc 3.0.2 and DryIoc.Microsoft.DependencyInjection 2.1.0.

```
//      DryIoc.ContainerException: 'Unable to get constructor of Boolean using provided constructor selector when resolving Boolean {ReturnDefault} #571 with args [_String0]
  //in wrapper Func<String, Microsoft.Extensions.Logging.LogLevel, Boolean> { ReturnDefault} as parameter "filter" #11 with args [_String0]
  //in singleton Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider: Microsoft.Extensions.Logging.ILoggerProvider { ServiceKey = DefaultKey(0), ReturnDefault} #56
  //in wrapper IEnumerable<Microsoft.Extensions.Logging.ILoggerProvider> { ReturnDefault} as parameter "providers" #1
  //in singleton Microsoft.Extensions.Logging.LoggerFactory: Microsoft.Extensions.Logging.ILoggerFactory as parameter "factory" #42
  //in singleton Microsoft.Extensions.Logging.Logger<Microsoft.AspNetCore.Hosting.Internal.WebHost>: Microsoft.Extensions.Logging.ILogger<Microsoft.AspNetCore.Hosting.Internal.WebHost> #570
  //from container.
```
 
// Startup.cs
 
```
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
 
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(
                    Configuration.GetConnectionString("DataBaseIntranetCore")));
            services.AddDefaultIdentity<IdentityUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
 
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
 
            return services.ConfigureDI(Bootstrap.RegisterServices);
        }
```
 
// IocDiExtensions.cs
 
```
public static class IocDiExtensions
    {
        public static IServiceProvider ConfigureDI(this IServiceCollection serviceCollection, Action<IRegistrator> configureServices)
        {
            var container = new Container(rules => rules
                .WithoutThrowOnRegisteringDisposableTransient()
                .WithTrackingDisposableTransients()
                .WithAutoConcreteTypeResolution())
                .WithDependencyInjectionAdapter(serviceCollection);
 
            container.UseInstance(container);
 
            configureServices(container);
 
            return container.Resolve<IServiceProvider>();
        }
    }
```
 
// Bootstrap
 
```
public static void RegisterServices(IRegistrator registrator)
{
// ILogger here is something I made, is not the same from Microsoft.Extensions.Logging.ILogger

            registrator.Register<ILogger, LogWrapper>(Reuse.Transient);
            registrator.Register<IAppConfig, AppConfig>(Reuse.Transient);
 
            registrator.Register<ICoreDbContext>(made: Made.Of(() => new CoreDbContext()));
            registrator.Register<ICoreDbContext>(made: Made.Of(() => new CoreDbContext("DataBaseCoreRO")), serviceKey: "ReadOnly");
            registrator.Register<IContextFactory, ContextFactory>();

/// etc...
}
```

**Comment by dadhi** [comment]
> Func<String, Microsoft.Extensions.Logging.LogLevel, Boolean>

The func returns `bool`, so it should be registered.

How and what does it mean is up to you.
You may register a method returning `bool` (via Made.Of) and use service key to identify it.

**Comment by jkvargas** [comment]
dadhi, I believe I still need your help. I am running a asp.net core app. I tryed to follow examples around the internet but I am stuck.

I did try to minimize the code of my app, I just created a new mvc app with individual authentication using netcoreapp2.0. And I've tryed to integrate DryIoc.

`public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            var container = new Container(rules => rules
                .WithoutThrowOnRegisteringDisposableTransient()
                .WithTrackingDisposableTransients()
                .WithAutoConcreteTypeResolution());

            container.Register<IAppConfig, AppConfig>(Reuse.Transient);

            var newContainer = container.WithDependencyInjectionAdapter(services, throwIfUnresolved: type => type.Name.EndsWith("Controller"));

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();

            return newContainer.Resolve<IServiceProvider>();
        }`

It keeps returning "DryIoc.ContainerException: 'Unable to get constructor of Boolean using provided constructor selector when resolving Boolean {ReturnDefault} #101 with args [_String0]
  in wrapper Func<String, Microsoft.Extensions.Logging.LogLevel, Boolean> {ReturnDefault} as parameter "filter" #11 with args [_String0]
  in singleton Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider: Microsoft.Extensions.Logging.ILoggerProvider {ServiceKey=DefaultKey(0), ReturnDefault} #51
  in wrapper IEnumerable<Microsoft.Extensions.Logging.ILoggerProvider> {ReturnDefault} as parameter "providers" #1
  in singleton Microsoft.Extensions.Logging.LoggerFactory: Microsoft.Extensions.Logging.ILoggerFactory as parameter "factory" #41
  in singleton Microsoft.Extensions.Logging.Logger<Microsoft.AspNetCore.Hosting.Internal.WebHost>: Microsoft.Extensions.Logging.ILogger<Microsoft.AspNetCore.Hosting.Internal.WebHost> #100
  from container.'"

Isn't this a problem with the integration?

**Comment by dadhi** [comment]
Now looking at used setup and exception I have more clues, thanks.

What if you remove `WithAutoConcreteTypeResolution()` ?

Any reason you need to use it?

Looking at your example, I have an idea how to improve exception messsge when using Auto resolution.

When I have time, I will check more thoroughly.

**Comment by jkvargas** [comment]
Yeah, it seems that was the problem.
I can handle without WithAutoConcreteTypeResolution =)
Thanks man

**Comment by dadhi** [comment]
Cool, anyway need to improve some things.

`AutoConcreteTypeResolution` probably should not consider `Func` arguments.

**Comment by dadhi** [comment]
After some thoughts, the automatic resolution should not consider a primitive type, like `int`, but using a `Func<MyType>` actually is fine.
