### ISSUE TITLE
DryIoc 4.1.0-preview1 singleton decorators are not getting called

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#169]
DryIoc 4.1.0-preview1 singleton decorators

Singleton decorators are ignored for compiled expressions...

**Comment by Havunen** [comment]
I will try to write unit tests for this...

**Comment by dadhi** [comment]
This is unfortunate, likely due reordering in `GetExpressionOrDefault` or allowing to compile singleton decorators into Constant.
Yes, we need the test, cause currently everything is passing.

**Comment by Havunen** [comment]
@dadhi I opened PR with test case for this behavior.

**Comment by Havunen** [comment]
@dadhi Did you have a look at this issue yet? Is it difficult one?

**Comment by dadhi** [comment]
I have fixed it. will push today.

**Comment by dadhi** [comment]
I have published v4.1.0-preview-02 with the fix and the FEC with your PR.
