### ISSUE TITLE
Wrong IContainer resolved

### ISSUE THREAD

**Issue by Fruchuxs** [dadhi/DryIoc#171]
Hello, we use two containers: One container registred with some config classes and modules (classes with registrations) and the other one which is the "true" container.
The modules get the true container via constructor, but the modules are resolved by the first one. This worked with DryIoc 2.x and 3.x preview.

But now with 4.x, the module clases get the configure container, instead of the true container. But, if I resolve IContainer on the configure container, I get the true Container ...

It seems there goes something wrong.

Simplified example:
```c#
var container = new Container();
var configureContainer = new Container();
configureContainer.RegisterDelegate<IContainer>(r => container, ifAlreadyRegistered: IfAlreadyRegistered.Replace);

configureContainer.Register<Module>();

// init code ...
configureContainer.Resolve<Module>().Register();


Assert.True(configureContainer.IsRegistered<IFoo>()); // true, expected false
Assert.True(container.IsRegistered<IFoo>()); // false, expected true
Assert.True(object.IsReferenceEqual(configureContainer.Resolve<IContainer>(), container); // true


class Module {
private IContainer cnt;
public Module(IContainer cnt) {
   this.cnt = cnt;
}

public void Register() {
cnt.Register<IFoo, Foo>();
}
}

public interface IFoo {
}

public class Foo : IFoo {
}
```

**Comment by dadhi** [comment]
Thanks for the reproduction code. Will look.

**Comment by Fruchuxs** [comment]
Thanks.
But, I'm a little bit unhappy with the "v4.1.0" milestone Tag. After I reported several problems with the 3.x Version, we still stick on 3.1.0-preview-04 in a production system. Now I tried to update on a stable major release. I don't want to wait until 4.1 release and maybe find new bugs and problems with new features in this minor version.

**Comment by dadhi** [comment]
Ok, will try with 4.0.6 first.

**Comment by dadhi** [comment]
I have released v4.0.6 with the fix.

**Comment by Fruchuxs** [comment]
Thanks, you are awesome!

**Comment by Havunen** [comment]
@dadhi test case would be good :)

**Comment by dadhi** [comment]
> test case would be good :)

What do you mean?

**Comment by Havunen** [comment]
Oh, never mind I'm blind; I see you added tests 👍
