### ISSUE TITLE
[MS.DI] Error registration - no ILogger of Hosting.WebHost has been registered

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dadhi/DryIoc#172]
No service for type 'Microsoft.Extensions.Logging.ILogger`1[Microsoft.AspNetCore.Hosting.WebHost]' has been registered.

.net core 3-preview8

**Comment by dadhi** [comment]
> .net core 3-preview8

Did not try it yet. 
If you want, you may open a PR with the new project *.AspNetCore3_0** similar to https://github.com/dadhi/DryIoc/tree/master/src/DryIoc.Microsoft.DependencyInjection.AspNetCore2_1

**Comment by dadhi** [comment]
Related links:

- https://github.com/JasperFx/lamar/pull/189/files#diff-1
- https://github.com/aspnet/Logging/issues/691

**Comment by dadhi** [comment]
@VladislavAntonyuk 
Is it still reroducible for you?

**Comment by dadhi** [comment]
DryIoc.MS.DI v4 is out https://www.nuget.org/packages/DryIoc.Microsoft.DependencyInjection/4.0.0

and the new sample is pushed to the repo
https://github.com/dadhi/DryIoc/tree/master/samples/DryIoc.AspNetCore31.WebApi.Sample
