### ISSUE TITLE
Resolving Current Scope services on Application_PostAuthenticateRequest Method

### ISSUE THREAD

**Issue by arabasso** [dadhi/DryIoc#174]
Hello!

Is it possible in the Application_PostAuthenticateRequest method to resolve an InWebRequest service? I use NHIbernate 4 in an MVC 4 application and to avoid having to open a new session in the Application_PostAuthenticateRequest method, I would like to get the NHibernate session from the current HTTP request.

**Comment by dadhi** [comment]
hi @arabasso
I did not work with  MVC4, NHIbernate neither with `Application_PostAuthenticateRequest`.
So I suggest asking the question on StackOverflow, providing more details and the code snippet.

**Comment by arabasso** [comment]
My problem is how to get an NHibernate session inside the Application_PostAuthenticateRequest method in Global.asax using DryIoc without opening a new session. Here's a code example:

```
public class MvcApplication
    : HttpApplication
{
    protected void Application_PostAuthenticateRequest(
        object sender,
        EventArgs args)
    {
        var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];

        if (cookie == null) return;

        var ticket = FormsAuthentication.Decrypt(cookie.Value);

        if (ticket == null) return;

        var identity = new FormsIdentity(ticket);

        // If I do that, DependencyResolve opens a new NHibernate session.
        var session = DependencyResolver.Current.GetService(typeof(ISession));

        var userModel = session.Query<UserModel>().SingleOrDefault(w => w.Username == identity.Name);
    }
}
```
Using this way, DryIoc opens 2 NHibernate sessions in the same HTTP Request.

**Comment by arabasso** [comment]
The NHibernate Session is being logged as:

```
container.RegisterDelegate(rd =>
{
    var session = rd.Resolve<ISessionFactory>().OpenSession();

    session.FlushMode = FlushMode.Commit;

    return session;
}, Reuse.InWebRequest);
```
Bottom line: How do I get the current DryIoc request scope within the Global.asax Application_PostAuthenticateRequest method?

**Comment by dadhi** [comment]
- Do you have access to `HttpContext.Current` there?
- What is the type of returned `DependencyResolver.Current`?

**Comment by arabasso** [comment]
>     * Do you have access to `HttpContext.Current` there?
Yes.
>     * What is the type of returned `DependencyResolver.Current`?
`DryIoc.Mvc.DryIocDependencyResolver`, where the container was initialized with: `container.WithMvc();`

**Comment by dadhi** [comment]
Try from here...
```cs
var resolverContext = DependencyResolver.Current.GetService(typeof(IResolverContext));
```
And you'll get access to scope [IResolverContext](https://www.fuget.org/packages/DryIoc.dll/4.1.0-preview-02/lib/netstandard2.0/DryIoc.dll/DryIoc/IResolverContext).

Then you can use it for whatever, I don't know...
```cs

if (resolverContext.CurrentScope?.Name.Equals(Reuse.WebRequestScopeName))
    session = resolverContext.Resolve<ISession>();
else
{
   // not sure the what to do here
}
```

**Comment by arabasso** [comment]
> 
> 
> Try from here...
> 
> ```cs
> var resolverContext = DependencyResolver.Current.GetService(typeof(IResolverContext));
> ```
Did not work... This returns `null`. The problem is that apparently it is not possible to access the scope of the current HTTP request without having the memory reference returned by the OpenScope method.

Is there any way to bind the scope of DryIoc to the `HttpContext` in the `Application_BeginRequest()` and `Application_EndRequest()` methods?

**Comment by dadhi** [comment]
DryIoc.Web package does that - check the source DryIocWeb.cs, and you can probably do it yourself.

**Comment by arabasso** [comment]
OK, thank you!
