### ISSUE TITLE
Made.Of Factory cannot resolve single constructor if type has cctor

### ISSUE THREAD

**Issue by pamidur** [dadhi/DryIoc#177]
DryIoc v4.0.7
Exception: Unable to find a single constructor in Type ...

The problem is in DryIoc.ReflectionTools.SingleConstructor(Type type, Boolean includeNonPublic) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 11079. This method doesn't expect constructor to be static.

Sample:
```c#
    class MyClass : IDisposable
    {
        public MyClass() { }
        static MyClass() { }
        public void Dispose() => throw new NotImplementedException();
    }

    class Program
    {
        static void Main(string[] args)
        {
            var container = new Container();
            container.Register<IDisposable>(Reuse.Singleton, Made.Of(r => typeof(MyClass)));
            container.Resolve<IDisposable>();
        }
    }
```

**Comment by dadhi** [comment]
> ` Made.Of(r => typeof(MyClass))`

What is it supposed to do? I mean in comparison with `container.Register<IDisposable, MyClass>(Reuse.Singleton)`.

**Comment by pamidur** [comment]
I just simplified it down to this. The real is more like:
```c#
Made.Of(r => PluginLoader.GetPluginTypeByName(r.Container.Resolve<MyPlugins>().MySuperService))
```

**Comment by dadhi** [comment]
Made.Of is for different purpose - to use passed expression to parse a constructor, method, property or field to get the service. The expression won't be invoked, for this you need `RegisterDelegate`.

```
container.RegisterDelegate(r => PluginLoader.GetPluginTypeByName(r.Resolve<MyPlugins>().MySuperService));
```

**Comment by pamidur** [comment]
Thank you! It works for me.
