### ISSUE TITLE
How to Log Before and After Constructor Call

### ISSUE THREAD

**Issue by RehanSaeed** [dadhi/DryIoc#186]
I have a project using DryIoC 3 and would like to write a log before and after every constructor call to be able to time how long each constructor is taking to execute and make sure that nobody is calling `Task.Wait()`. Is that possible? I see that there are decorators and interceptors which seem very close to what I want but I don't seem to do exactly what I'm asking for.

**Comment by dadhi** [comment]
Here is closest to what you need without use of interception and dynamic proxies - https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Decorators.md#decorator-of-generic-t

The additional change is that you need a decorator of `Func<TService>`, then you can do whatever you want before and after calling a Func. Though with the cost of Func, but it may be neglectable in your case.

**Comment by RehanSaeed** [comment]
It's not clear to me, how I can use that code to do what I want. Here is a short code example:

```c#
public interface IService1 { }
public class Service1 : IService1 { }

var container = new Container();
container.Register<IService1, Service1>();
container.Register<IService2, Service2>();
// ...many more registrations.
container.Resolve<Application>();
```

I want to know how long it takes to call the constructor of `Service1`, `Service2`, etc. and the order in which they are created. If I wasn't using IoC, I'd want to do something like this:

```c#
public class Service1 : Service1
{
    public Service1()
    {
        using (Logger.MeasureTime(this, "Calling Service1 Constructor"))
        {
            // .... Code in Service1 constructor
        }
     }
}
```

**Comment by dadhi** [comment]
You need to register something like this as decorator of `object`, you may use a condition to filter the applicable services:

```cs
public static T Measure<T>(Func<T> getService)
    {
        // timer start
        var x = getService();
        // timer stop
        // collect timing
        return x;
    }
```

**Comment by RehanSaeed** [comment]
Thanks!
