### ISSUE TITLE
container.Resolve<T>craches on iOS

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dadhi/DryIoc#187]
/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.notsupported.cs:64
ExpressionCompiler.TryCompileBoundToFirstClosureParam (System.Type delegateType, FastExpressionCompiler.LightExpression.Expression bodyExpr, System.Collections.Generic.IReadOnlyList`1[T] paramExprs, System.Type[] closurePlusParamTypes, System.Type returnType)
FactoryDelegateCompiler.CompileToFactoryDelegate (FastExpressionCompiler.LightExpression.Expression expression, System.Boolean useFastExpressionCompiler, System.Boolean preferInterpretation)
IResolver.Resolve (System.Type serviceType, DryIoc.IfUnresolved ifUnresolved)
Resolver.Resolve[TService] (DryIoc.IResolver resolver, DryIoc.IfUnresolved ifUnresolved)

**Comment by dadhi** [comment]
What is DryIoc version?

**Comment by dadhi** [comment]
Try the solution from here 
https://github.com/dadhi/DryIoc/issues/156

**Comment by VladislavAntonyuk** [comment]
@dadhi latest preview. I have also tried with version 4.0.0. The same behavior. I will try your solution #156

**Comment by VladislavAntonyuk** [comment]
Also related issue: https://github.com/dadhi/DryIoc/issues/130
container = new Container(rules => rules.WithUseInterpretation()); solves the issue. Is there any impact on performance if I run it on non iOS devices?

**Comment by dadhi** [comment]
Maybe 4 times slower on 3rd and more resolutins (tested in this benchmark https://github.com/dadhi/DryIoc/blob/8e8aa8bd710f5a0d0a8ad14f457ea419fd5eb562/playground/Playground/RealisticUnitOfWorkBenchmark.cs)

If ossible, I would suggest to use platform #if-def or set this option after checking platform runtime capability.

**Comment by dadhi** [comment]
Using somth like this `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` or using `IsDynamicCompilationSupported` from the .Net Core 3.

I am personally not developing for iOS, so would be intesting to hear, what in the end did worked for you.

**Comment by VladislavAntonyuk** [comment]
OK, thank you, I am closing the issue and will reply to the related one.
