### ISSUE TITLE
DryIOC new Transient Disposable

### ISSUE THREAD

**Issue by brynhr** [dadhi/DryIoc#192]
I think I have come across a bug in .new whereby setting allowDisposableTransient to true on .register (not on the rules but on register) does not change if the disposable transient is allowed to be created. I have compared .new and .resolve and only .resolve seems to take into account this setup, whereas .new raises the exception saying that I need to set allowDisposableTransient to override the exception, which is not the observed behaviour.

**Comment by dadhi** [comment]
Please a small test or example app.

**Comment by brynhr** [comment]
Hi Maksim, have attached a repro project.
[ConsoleApp1.zip](https://github.com/dadhi/DryIoc/files/3815834/ConsoleApp1.zip)
