### ISSUE TITLE
Separate cs file generator for compile-time DI from DryIoc Container

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#213]
The idea:

- Create a template method-based abstraction for client to register services for compile-time generation, e.g. `CompileTimeModuleBase`.
- Add the `CompileTimeModuleBase.Generate()` method to produce the whole `
.generated.cs` file contents as a `string`.
- Add some thingy (maybe an exe program ) to dump the generated content into a file.
- Include the generated file into the consuming project.

**Comment by yallie** [comment]
Hello Maksim,

have you heard of this brand new feature of C# compiler?
https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/

I thought that C# generators may provide seamless integration for the 
code generation phase. If I understand it right, it works like Roslyn-based 
code analyzers: a class library that's added to a project via Nuget package 
and plugged into C# compiler pipeline. Like a code analyzer that can emit 
additional code while your project is being compiled. A modern replacement
for the "Reflection + T4 templates + post-build tasks" combination.

**Comment by dadhi** [comment]
Hi @yallie ,

I know about them and currently DryIoc uses T4, so the question is for migration path. Specifically:

1. How to make the SD a part of the library and publish them to NuGet? 
2. How to specify the registrations I want to generate at compile time? T4 allows to include the User-written "normal" container setup for this, e.g. like this one in MediatR samples  https://github.com/jbogard/MediatR/blob/b92ae61355349c32bc8d5c260022cfe710a8f84a/samples/MediatR.Examples.DryIocZero/Registrations.ttinclude#L21
3. When I should exect them out of preview and API stabilized? Honestly I don't have time to pursue a moving target.

**Comment by yallie** [comment]
1. Not sure if a source generator can be included in a library package. They will probably need to be extracted to a separate Nuget package.
2. Good point! I can only think of attributes in the source code. Perhaps code generators will eventually support custom properties loaded from the csproj-file.
3. I don't know if any official roadmap for them is currently published :)

**Comment by dadhi** [comment]
Currently it is possible to generate the valid graph expression by native DryIoc (and FastExpressionCompiler) tools like this:

```cs
var code = container.Resolve<LambdaExpression>(typeof(ARootService)).ToCSharpString();
```

The code is ready to be used by whatever other compile time utility.
The examples of the graph from the RealisticBenchmark are here:

- https://github.com/dadhi/DryIoc/blob/master/playground/Playground/RealisticUnitOfWork_GeneratedResolutionGraph.cs
-  https://github.com/dadhi/DryIoc/blob/master/playground/Playground/RealisticUnitOfWork_GeneratedResolutionGraph_MsDI.cs
