### ISSUE TITLE
RegisterInitializer<TService> causes additional call(s) to TService.Dispose when container is disposed

### ISSUE THREAD

**Issue by wjrogers** [dadhi/DryIoc#215]
Each `RegisterInitializer` action that applies to a service type causes the container to dispose resolved instances of that service an additional time when disposing the container. In the example below, `service1` is disposed twice, and `service2` is disposed three times.

DryIoc.dll 4.1.0

```csharp
using System;
using System.Threading;
using DryIoc;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            IService1 service1;
            IService2 service2;

            using (var container = new Container())
            {
                container.Register<IService1, Disposable1>(reuse: Reuse.Singleton);
                container.Register<IService2, Disposable2>(reuse: Reuse.Transient, setup: Setup.With(trackDisposableTransient: true));

                container.RegisterInitializer<IDisposable>((service, _) => Console.WriteLine(typeof(IDisposable)));
                container.RegisterInitializer<IService2>((service, _) => Console.WriteLine(typeof(IService2)));

                service1 = container.Resolve<IService1>();
                service2 = container.Resolve<IService2>();
            }

            Console.WriteLine(service1); // 2
            Console.WriteLine(service2); // 3
        }

        public interface IService1 : IDisposable { }
        public interface IService2 : IDisposable { }

        private abstract class Disposable
        {
            private int m_disposed_count;

            public void Dispose()
                => Interlocked.Increment(ref m_disposed_count);

            public override string ToString()
                => m_disposed_count.ToString();
        }

        private class Disposable1 : Disposable, IService1 { }
        private class Disposable2 : Disposable, IService2 { }
    }
}
```

**Comment by dadhi** [comment]
Thanks for finding.
Seems it is not critical but is not pleasant either. I am on vacation next 3 weeks so PR will be welcome. Will check myself when I have time TM :)

**Comment by dadhi** [comment]
I have found the root cause.
The `RegisterInitializer` decorator returns the same object after doing init action, and that object is also added into Singleton scope. So the object maybe added twice to the scope disposal collection - there is no check for identity. But adding the check impacts the performance. Need to think a bit more.

**Comment by dadhi** [comment]
Ok, this this DryIoc right ;)  I always have a configuration option thought away.
In this case I may prevent disposal of initializer decorator (which does not make sense anyway) via decorator setup `preventDisposal: true` option.
I will try it and report later.
