### ISSUE TITLE
DryIoc and IServiceProvider on Prism for Xamarin.Forms (DryIoc.Microsoft.DependencyInjection)

### ISSUE THREAD

**Issue by yankarinRG** [dadhi/DryIoc#217]
Hello, I've got a Prism application with DryIoc as container.
I'd like `IHttpClientFactory` to provide `HttpClient`s to my **typed clients**, which are like this:
```
public class ExampleService : IExampleService
{
    private readonly HttpClient _httpClient;

    public RepoService(HttpClient client)
    {
        _httpClient = client;
    }

    public async Task<IEnumerable<string>> GetExamplesAsync()
    {
        // Code deleted for brevity.
    }
}
```
In **App.xaml.cs** I register my typed client so they can be injected in viewmodels with the following:
```
public partial class App

// ...

protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    // Code deleted for brevity.
    containerRegistry.Register<IExampleService, ExampleService>();
}
```
And that's before trying to use `IHttpClientFactory`.

Now, to add it, we [should](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests#consumption-patterns)  `AddHttpClient()` on `IServiceCollection`. That's where I thought **DryIoc.Microsoft.DependencyInjection** was needed, so, still in **App.xaml.cs**, I wrote the following:
```
public partial class App

// ...

protected override IContainerExtension CreateContainerExtension()
{
    var services = new ServiceCollection();

    services.AddHttpClient<IExampleService, ExampleService>(c => {
        c.BaseAddress = new Uri("https://api.example.com/");
    });

    var container = new Container(CreateContainerRules())
        .WithDependencyInjectionAdapter(services);

    return new DryIocContainerExtension(container);
}
```

The problem is that in my **ExampleService** I'm getting **client** with the following specs:
`{
   "DefaultRequestHeaders":[
   ],
   "BaseAddress":null,
   "Timeout":"00:01:40",
   "MaxResponseContentBufferSize":2147483647
}`
whilst I expected **BaseAddress** to be https://api.example.com/, so the REST API call fails.

Do you know what is the correct pattern to use `IServiceProvider` when using DryIoc on Prism for Xamarin.Forms? Unfortunately there's no documentation or open source code available on the following matter.

Thanks you, and have a great day.

**Comment by dadhi** [comment]
Hi, 

Thanks for the a well explained question, but I am not using Prism with MS.DI personally, especially with the mix of `HttpClient` which is the topic of its own.

I would suggest to repost this question as-is to the StackOverflow with the `dryioc` and `prism`, `xamarin` tags. Prism has an active community there and I hope you get an answer.

**Comment by dadhi** [comment]
Maybe this issue is relevant https://github.com/dansiegel/Prism.Container.Extensions/issues/80
?
