### ISSUE TITLE
Usage on ASP.NET Core 3.1

### ISSUE THREAD

**Issue by ssteiner** [dadhi/DryIoc#219]
Sorry if that's really basic, but I'm unable to find any sample on how to use DryIoc with ASP.NET Core 3.x. The startup class' ConfigureServices method needs to be void.. so I can't call
`return new Container().WithDependencyInjectionAdapter(services).ConfigureServiceProvider<DryIocHelper>();`

as with the examples I've found. Similarly `services.AddDryIoc<DryIocHelper>()`

tells me there's no such thing as an AddDryIoc extension method. 

My project contains the DryIoc.Microsoft.DependencyInjection 3.0.3 package which as far as I understand is the correct one and latest.

**Comment by ssteiner** [comment]
Okay, so it seems I can answer my own question.

When you work with your generic HostBuilder, you append UseServiceProviderFactory

`var builder = Host.CreateDefaultBuilder(args)
                    .UseServiceProviderFactory(new DryIocServiceProviderFactory()) // register to use DryIoc`

And if you happen to already have a Container, you provide it to the DryIocServiceProviderFactory.

And in Startup.cs's ConfigureServices method, you add AddControllersAsServices() on the call that adds your controllers/MVC controllers.

Did I miss the documentation though? I only finally pieced it together by going through other open issues.

**Comment by dadhi** [comment]
You've figured it right, here is the api-doc for that, not very discoverable though: https://github.com/dadhi/DryIoc/blob/8c9b15f3c42ca46b8f91b60a26311bedae9b5066/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L271

I hope it will work for you, did not yet check it myself with ANC 3 and 3.1.
Please notify me if something goes off.

Btw, I did not yet created a `AddDryIoc()` because it will require additional reference to `HostBuilder` stuff - so it'll probably require creation of the new package, just for that extension method sugar. But maybe we can other useful stuff.
I am open for suggestions and PRs.

Ps.. I would be glad if you report facing this issue #172 

Thanks.

**Comment by ssteiner** [comment]
It appears to be working. I've not yet managed to test my complex controllers (it's a big port job of an existing app to .NET core), but my test controllers also get their registrations. I'm not using ILogger in my controllers so far but my own logging mechanism, but when I add an ILogger<MyController> to the constructor of my test controller, I get a logger and it logs to where it's supposed to. And that's without any kind of registration or configuration for logging in Startup.cs.

**Comment by dadhi** [comment]
Thanks for sharing.

**Comment by dadhi** [comment]
@ssteiner , 
Just in case, maybe you have a sample you can share?

**Comment by vdasus** [comment]
@ssteiner May be like below (It's working, but is it ok?)
``` csharp
    public class Program
    {
        public static void Main(string[] args) => CreateHostBuilder(args).Build().Run();

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseServiceProviderFactory(new DryIocServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseNLog();
    }
```

and  
``` csharp
    internal class DryIocServiceProviderFactory : IServiceProviderFactory<IContainer>
    {
        public IContainer CreateBuilder(IServiceCollection services)
            => new Container().WithDependencyInjectionAdapter(services);

        public IServiceProvider CreateServiceProvider(IContainer containerBuilder)
            => containerBuilder.ConfigureServiceProvider<CompositionRoot>();
    }
```

**Comment by dadhi** [comment]
@vdasus Please don't use `UseInstance`, use `Use` - no pun intended.

**Comment by dadhi** [comment]
DryIoc.MS.DI v4 is out https://www.nuget.org/packages/DryIoc.Microsoft.DependencyInjection/4.0.0

and the new sample is pushed to the repo
https://github.com/dadhi/DryIoc/tree/master/samples/DryIoc.AspNetCore31.WebApi.Sample
