### ISSUE TITLE
Is it possible to inject service into a method in MVC 5/webapi controller action? Constructor/properties would be way too many services to inject

### ISSUE THREAD

**Issue by rajasekarshanmugam** [dadhi/DryIoc#224]
DryIOC is perfect to inject services via constructor/properties. Would it be possible to inject services into a method by way of decorating the parameters with an attribute, if DryIOC is the dependency resolver? Would this be a MVC capability or can DryIOC can handle it on actions?

App environment is MVC5 with OWIN self hosted WebAPI on .NET 4.8.

ASP.NET core appears to do this via [FromServices] and unity seems to support method injection via an attribute - just few equivalents that we tried. Due to various constraints, it has to be made available in the above environment.

**Comment by dadhi** [comment]
Hello,

I am not an expert in Mvc and not using it personally, so it is hard to suggest something. But if Unity and othets can do it, DryIoc is 99% percent can do it to.
The whole extension is a single file with the small amount of the code https://github.com/dadhi/DryIoc/blob/master/src/DryIoc.Mvc/DryIocMvc.cs
You can try something and send a PR for review. I will help with the questions.

**Comment by rajasekarshanmugam** [comment]
Hi, still trying to find how/where the controller is invoked as a part of action method resolution and how would the DI resolution participate there.

**Comment by dadhi** [comment]
I think the question is better to be re-asked on StackOverflow. Closing for now.
