### ISSUE TITLE
Update DryIoc.CommonServiceLocator references

### ISSUE THREAD

**Issue by walli545** [dadhi/DryIoc#226]
Hi,

DryIocCommonServiceLocator in version 4.0.0 references **DryIoc 4.0.0** and **CommonServiceLocator 2.3.0**.
I think these should be updated **DryIoc 4.1.0** and **CommonServiceLocator 2.4.0** as this leads to errors when used in combination with never versions of Prism that use CSL >= 2.4.0.

This is the error that occurs:

> Could not load file or assembly 'CommonServiceLocator, Version=2.0.3.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I was able to fix this by adding a redirect in app.config, but i think this should not be necessary.

**Comment by dadhi** [comment]
thanks for finding, will do.

**Comment by dadhi** [comment]
Packages DryIoc.CommonServiceLocator.dll and DryIoc.CommonServiceLocator 4.1.0 are published to NuGet
