### ISSUE TITLE
Updated DryIoc from 4.0.4.0 to 4.1.0 in Unity Engine project, keyed register/resolve wont work anymore

### ISSUE THREAD

**Issue by almanesa** [dadhi/DryIoc#228]
I used DryIoc 4.0.4.0 netstandard 2.0 in a Unity project without a problem and tested if I can update it to 4.1.0 (netstandard 1.0 for iOS runtime compatibility) but keyed register/resolve won't work anymore. after registering 2 classes that implement an interface with different enum values as key, nor interface[] neither resolve by serviceKey won't work. calling GetServiceRegisteration on container returns one registration with last keyed register call, but even resolving with that key also fails.

I use Rider as IDE that has support for Unity editor test run beside normal standalone nunit test runner, if I run a test (on keyed register/resolve) with standalone test runner it would succeed but if I run it with unity editor test runner, it would fail, same as unity runtime.

**Comment by dadhi** [comment]
Woops, that's a lot. Will check that.

Couple of questions:

- Do you use any custom rules for container?
- Could you send or add via PR a test?

I suppose it something like this... right?

```cs
container.Register<Iface, A>(Keys.A);
container.Register<Iface, B>(Keys.B);

container.Resolve<Iface[]>(); // fails, how?
container.Resolve<Iface>(Keys.A); // fails, how?
```

**Comment by almanesa** [comment]
Yes just like that.

[UnityProject](https://drive.google.com/open?id=1ahrtYni7pdsaBDudEDzHylknRHUISKqD)

I'm using Unity 2019.2.21 (project can be opened with any version > 2019.2.X) with default settings.

**Comment by almanesa** [comment]
> Do you use any custom rules for container?
doesn't matter with or without rules, but in the main project, I am using WithoutFastExpressionCompiler

**Comment by dadhi** [comment]
Thanks for the info, will try to reproduce. Could you try `WithUseInterpretation()` instead of `WithoutFastExpressionCompiler()`? want to check something.

**Comment by almanesa** [comment]
> Thanks for the info, will try to reproduce. Could you try `WithUseInterpretation()` instead of `WithoutFastExpressionCompiler()`? want to check something.

unfortunately, It didn't help. 

by the way, are these rules supposed to be used exclusively? I thought I can use both simultaneously.

**Comment by dadhi** [comment]
Yes, you can both. I just wanted to quickly check my guess.

**Comment by dadhi** [comment]
Hi @almanesa 

I have released DryIoc.dll 4.1.1-preview-01 version.

Could you please check that it is working for you?

**Comment by almanesa** [comment]
Hi!
Yes, it does work now, Thank you very much.

**Comment by dadhi** [comment]
@almanesa Cool,
I will release non-preview version shortly.

**Comment by almanesa** [comment]
Very good, Thank you very much.
