### ISSUE TITLE
Additional default parameter for Made creation public API introduced binary incompatibility..

### ISSUE THREAD

**Issue by ryoasai** [dadhi/DryIoc#236]
Hello.

I found that many DLLs (including DryIoc.MefAttributeModel.dll 5.0.0, Prism.DryIoc v7.2.0.1422) that depend on DryIoc stopped working since DryIoc 4.1.0 release.
With the latest version of DryIoc they all give the following runtime Exception:

`System.MissingMethodException: 'Method not found: 'DryIoc.Made DryIoc.Made.Of(DryIoc.FactoryMethodSelector, DryIoc.ParameterSelector, DryIoc.PropertiesAndFieldsSelector, Boolean)'.'`

I suspect that this is caused by the binary incompatibility introduced by an additional default parameter bool isImplMemberDependsOnRequest = false in one of the Made factory methods.

I found that was introduced by the following commit.
[https://github.com/dadhi/DryIoc/commit/7a54f4c8d3e6f942597e740f6f80556c9f753f4e](url)

Since this change is made to a fundamental API, Made.of(), I suppose you should keep binary compatibility at least for the time being.
  
Can you reinstate the original four parameter method for keep the latest version compatible with them. Or can you release a new MefAttributeModel.dll ?

Thank you.

**Comment by dadhi** [comment]
Thanks for the notifying. Will check what is simpler to do.

**Comment by ryoasai** [comment]
Thank you very much for your quick reply!

**Comment by dadhi** [comment]
v4.1.2 is out on NuGet

**Comment by ryoasai** [comment]
I upgraded  DryIoc to 4.1.2 and I verified the problem was fixed.
Thank you again for the quick fix.
