### ISSUE TITLE
UseInstance with interface-based serviceType does not replace previous instance

### ISSUE THREAD

**Issue by detoxhby** [dadhi/DryIoc#237]
After using `IResolverContext.UseInstance` the first time, the next UseInstance with same interface-based serviceType (and even implementation type) will not replace previous instance.
(even with or without IfAlreadyRegistered.Replace)

Example:
```csharp
interface IUser
{
   string UniqueId { get; set; }
}

class User : IUser, IEquatable<User>
{
    public Guid Id { get; set; }
    string UniqueId { get; set; }
    // ...
   // IEquatable.Equals(User) and overriden object.Equals are provided
}

[Fact]
public void Test()
{
    // base ctor creates Scope = Container.OpenScope()
    var origUser = Scope.Resolve<IUser>(); // this is from normal registration
    var newUser = new User { Id = Guid.NewGuid() };
    
    Scope.UseInstance(newUser, IfAlreadyRegistered.Replace); // this is FINE, this instance is used
    Scope.UseInstance(origUser, IfAlreadyRegistered.Replace); // this is NOT happening
   // ... nor any subsequent calls UseInstance
}
```

---

### ~~not really for me~~ Solution

ℹ️ Using direct class type `User` will make it work properly.

This is not an option for me due to abstraction, I need to use the interface type.

---

Any help is appreciated if I can work around this problem.
(tried to override GetHashCode() as Container.UseInstance is based on that, but it is used on ServiceType which is the interface and `RuntimeHelpers.GetHashCode(typeof(IUser))` does not change during type, shouldn't be a problem)

**Comment by dadhi** [comment]
Thanks for posting. I will check.

**Comment by dadhi** [comment]
@detoxhby 
Please check my commit https://github.com/dadhi/DryIoc/commit/54e897cd38e46b2279bb83cc19051551438dec71#diff-74f9667b68d5a245baf32f72dac57ec3.

The `UseInstance` is obsolete (actually not in v4.1 yet but I won't be fixing the bugs for it)

Please use `Use` for replacing in scope or `RegisterInstance` for other scenarios.

I will release version 4.1.2 with the fix shortly.

**Comment by detoxhby** [comment]
Nice! 👍 

Btw I've tried `Use()` as well looking at the container code as it is (will be) marked as obsolete, but didn't work even for first time. I hope this cache invalidation will make it happen.

**Comment by dadhi** [comment]
v4.1.2 is out on NuGet

**Comment by detoxhby** [comment]
✅ Checked new version: works fine!

Thanks for the fast response, keep up the good work! :)
