### ISSUE TITLE
documentation: The Facade section of "child" containers article is irrelevant

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#238]
https://bitbucket.org/dadhi/dryioc/wiki/KindsOfChildContainer.md

None of provided examples are usable with 4.1.1.
WithFallbackContainer - is omitted
``` c#
var container = new Container();
    container.Register<IService, Service>();
    container.Register<Client>();

    var testFacade = container.CreateFacade();
    testFacade.Register<IService, TestService>();

    var client = testFacade.Resolve<Client>();
    Assert.IsInstanceOf<TestService>(client.Service);
```
container.CreateFacade() - is designed for different purposes.

**Comment by dadhi** [comment]
Hi, thanks for pointing the problem.
I will re-check the documents.

**Comment by dadhi** [comment]
Basically I have cleaned up the nonrelevant stuff from the doc https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/KindsOfChildContainer.md
