### ISSUE TITLE
WithUnknownServiceResolvers messes up resolving requests

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#240]
DryIoc.dll : 4.1.1
.net core 3.1

``` C#
    [TestClass]
    public class BugTests
    {
        interface IServiceA
        {
            
        }

        class ServiceA: IServiceA
        {
            
        }

        interface IServiceB
        {
            
        }

        class ServiceB: IServiceB
        {
            
        }

        interface IServiceC
        {
            
        }

        class ServiceC: IServiceC
        {
            public ServiceC(IServiceA a, IServiceB b)
            {
                
            }
        }
        [TestMethod]
        public async Task ReturnsCorrectInstance()
        {
            var container = new Container();
            container.Register <IServiceA, ServiceA>();
            container.Register<IServiceB, ServiceB>();

            var facade = new Container(Rules.Default.WithUnknownServiceResolvers(request =>
                new DelegateFactory(_ => starting.Resolve(request.ServiceType))));
            facade.Register<IServiceC, ServiceC>();

            var actual = facade.Resolve<IServiceC>();
            
            Assert.IsInstanceOfType(actual, typeof(ServiceC));
        }
    }
```

It throws NoConversionOperatorFoundWhenInterpretingTheConvertExpression. The request object for dependency A is actually a request object for dependency B.

**Comment by dadhi** [comment]
Thank you for finding and for the test especially. Will look when I have time.

**Comment by dadhi** [comment]
@dvabuzyarov 
I've remembered something.. cause I did not touch this feature for the long time.
Did you try `WithDynamicRegistrations` instead of `WithUnknownResolvers`?
Here is the usage examples https://github.com/dadhi/DryIoc/blob/be545dbd08bd9f750abac3f47225c91d08089bab/test/DryIoc.UnitTests/DynamicRegistrationsTests.cs

As I remember the former was supposed to fix the exact problem of the latter with `ResolveMany` and collection wrappers.
Sorry for the lack of docs - https://github.com/dadhi/DryIoc/issues/146

**Comment by dvabuzyarov** [comment]
@dadhi 
Actually I have a specific task to collect registrations from features in a project, so I need to create a basic container that would use to instantiate a feature composition root, and collect all registration of the feature. As all registrations are collected than a main container would be build on top of those registrations without feature compositions and another unnecessary dependencies.

At the moment I manage to complete it with decorators for IRegistrator and IContainer, but I will give another try to the approach with containers hierarchy.

**Comment by dvabuzyarov** [comment]
Here is an example what I am trying to achieve:
``` C#
[TestClass]
    public class ExampleTests
    {
        interface IServiceA
        {
            
        }

        interface IServiceB
        {
            
        }

        class ServiceA: IServiceA
        {
            
        }

        class ServiceB: IServiceB
        {
            
        }

        class FeatureCompositionRoot
        {
            public FeatureCompositionRoot(IServiceA serviceA, IRegistrator registrator)
            {
                registrator.Register<IServiceB, ServiceB>();
            }
        }

        [TestMethod]
        public async Task ReturnsRuntimeContainer()
        {
            var container = new Container(); // this container has registrations only
            container.Register<IServiceA, ServiceA>();
            container.Register<FeatureCompositionRoot>();

            var facade = new ChildContainer(container.Share_Registry); // this container has no registrations
            facade.Resolve<FeatureCompositionRoot>(); // owns the instance of FeatureCompositionRoot and has IServiceB registration

            var actual = facade.WithRegistrationsCopy(); // actual is a container only with registration of IServiceB
            
            Assert.AreEqual(1, actual.GetServiceRegistrations().Count());
        }
    }
```

I would be very grateful if you can tell me is it doable with DryIoc at the moment or not.

**Comment by dvabuzyarov** [comment]
@dadhi as I can see WithDynamicRegistrations does not help in my story.

**Comment by dadhi** [comment]
I am not sure what are trying to accomplish, the container hierarchy with some shared and some isolated registrations?

**Comment by dadhi** [comment]
Honestly I don't like such hiearchies because they usually mix registration and resolution responsibilities, and if you are adding the lifetime management on to - it becomes a hell.

Try other approaches, e.g. split registrations by key and create a derivative containers with the key used as a default one (there is a rule for that), or use named scope hierarchy - DryIoc will filter the registrations with reuse not matching the scope, etc. Check full `container.With(...)` version for sharing the state variants

**Comment by dvabuzyarov** [comment]
@dadhi 
Thanks for you time and response, finally I managed to achieve my goals with your help.
I am totally agree and understand your point, the only thing is that I want to have some control over the Registry. I just want to take some registrations from one container and transfer them to a new container. I think there is no complexity. Anyway this discussion is out of the original topic of this issue. If you are interested to see my use case we can meet on Skype.

**Comment by dadhi** [comment]
closing then, if there is still a missing functionality please open a separate issue
