### ISSUE TITLE
Validate call hangs when there are many singletons

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#242]
Hi,

If I change playground loadtest project LogicRegistrations to Singleton, then benchmark completes in 0.4seconds but validation takes so long that it crashes the process out of memory exception.

Steps to reproduce:

Change this code registerMany reuse to Reuse.Singleton 

https://github.com/dadhi/DryIoc/blob/master/playground/LoadTest/Registrations.cs#L575-L586

Run the project and see it takes very long to finish and/or crashes

**Comment by Havunen** [comment]
This happens in our real application too, and can be reproduced here using load test

**Comment by dadhi** [comment]
Hi there, Validate is switching off singleton optimizations to prevent the creation of the actual objects. 

Are you validating everything or only the roots / controllers?

**Comment by Havunen** [comment]
I'm not sure if what it validates when you call `container.Validate();` probably all types?

**Comment by dadhi** [comment]
> probably all types?

Yes, all the types. It means that all registered types (even if most of them are just the dependencies) will be **resolved**. So it is better to specify the `roots` explicitly or via the `condition`, e.g. `Validate(x => x.ServiceType.Name.EndsWith("Controller"))`

**Comment by Havunen** [comment]
ok, I will try that. I also tested DryIoc 4.0.7 completes this validation step in ~1sec

**Comment by dadhi** [comment]
> I also tested DryIoc 4.0.7 completes this validation step in ~1sec

That's strange, thanks for the info. Will profile it to see what's happening.

**Comment by dadhi** [comment]
Here are my results.
I am not sure about v4.0.7 but the fix is actually unrolling the whole object-graph, so it is actually validating something. I have lifted the `DependencyDepthToSplitObjectGraph` limit and did some optimizations to take Validation into account.

![image](https://user-images.githubusercontent.com/39516/76863607-c7723d00-6870-11ea-926a-613aa49e6b57.png)

**Comment by Havunen** [comment]
Hey, is there any chance to get this fix to v4 ? We would like to update but this is blocking issue.

**Comment by dadhi** [comment]
I will try.

**Comment by dadhi** [comment]
Here are the new results with changes from the #245 

```
container.Validate(x => x.ServiceType.Name.EndsWith("Controller"));

Validation finished - 00:01:21.60
```
```
container.Validate();

Validation finished - 00:02:49.32
```

Much better compared to the 3.43.09 min for controllers we had before.
@Havunen Is it sufficient for you? 
I am out of ideas for now.

**Comment by dadhi** [comment]
Ok.. this is fun. I have manually parallelized the validation like this:
```cs
bool IsController(ServiceRegistrationInfo x) => x.ServiceType.Name.EndsWith("Controller");

var controllers = container.GetServiceRegistrations()
    .Where(IsController).Select(x => x.ToServiceInfo()).ToArray();

var controllersPerCpu = new List<ServiceInfo>[Environment.ProcessorCount];
for (var i = 0; i < controllers.Length;)
    for (var j = 0; j < Environment.ProcessorCount && i < controllers.Length; j++, i++)
        (controllersPerCpu[j] ?? (controllersPerCpu[j] = new List<ServiceInfo>())).Add(controllers[i]);

var validationTasks = controllersPerCpu
    .Select(x => Task.Run(() => container.Validate(x.ToArray()))).ToArray();

var results = (await Task.WhenAll(validationTasks))
    .SelectMany(x => x).ToArray();
```

And now `Validation finished - 00:00:40.44`

**Comment by dadhi** [comment]
Found the new ideas for improvement so stay tuned...

**Comment by Havunen** [comment]
Hey.

I think 40seconds is already quite an improvement. 👍 
That should be fine

**Comment by dadhi** [comment]
@Havunen Ok, I went to some minor optimizations after profiling but it did not change  much.

**Comment by dadhi** [comment]
good enough
