### ISSUE TITLE
Multiple Registrations of same Service

### ISSUE THREAD

**Issue by MSThug** [dadhi/DryIoc#246]
I've read through the documentation at nauseam at this point but I'm not having much luck registering my services as I would expect. So here is what I'm trying to do.  

I have multiple view models I'm registering as a transient (I'm assuming this is the default) and with each model I'm attempting to also register an association with two different interfaces. The key interface being called IViewProvider.  The first view model that is registered seems to work.  However, subsequent registrations succeed in that there are no errors but later when I try to inject IEnumerable<IViewProvider> into one of my startup classes I only ever get the first registered view model. Below is the method I use to register my view and view model.

```
public void AddModule<TView, TViewModel>()
        where TView : class
        where TViewModel : class, IViewProvider, IRequiresInitialization
{
        this.container.Register<TView>();
        this.container.RegisterMany(new[] { typeof(IViewProvider), typeof(IRequiresInitialization) }, typeof(TViewModel));
}
```

To be clear I've tried RegisterMany and RegisterMapping with the same result.

My expectation was that I would have a new instance of each view model returned to me as an IViewProvider when I add IEnumerable<IViewProvider> to my startup class.

What am I misunderstanding here?

**Comment by dadhi** [comment]
Hi @MSThug 

I did not find any problem in v4.1.2 - [live code](https://dotnetfiddle.net/TU1xnV)

The full code:

```cs
using System;
using DryIoc;
					
public class Program
{
	public static void Main()
	{
		var container = new Container();
		
		AddModule<ExampleView, ExampleViewModel>(container);
		
		var x = container.Resolve<IViewProvider>();
		var y = container.Resolve<IRequiresInitialization>();
		
		Console.WriteLine("x is not the same as y: " + (x != y));
		Console.WriteLine("x is {0} and y is {1}", x.GetType(), y.GetType());
	}
	
	static void AddModule<TView, TViewModel>(IContainer container)
        where TView : class
        where TViewModel : class, IViewProvider, IRequiresInitialization
	{
		container.Register<TView>();
		container.RegisterMany(new[] { typeof(IViewProvider), typeof(IRequiresInitialization) }, typeof(TViewModel));
	}
	
	public interface IViewProvider {}
	internal interface IRequiresInitialization {}
	
	internal class ExampleViewModel : IViewProvider, IRequiresInitialization {}
	
	public class ExampleView {}
}
```

So far it is working according to the [docs](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RegisterResolve.md#registermany) when you explicitly specify the service types in the `RegisterMany` it will register them as long as the implementation type is implementing them. 
If you omit the service types and rely on DryIoc to figure them out - be sure to make them **public** or pass the `nonPublicServiceTypes: true`.

**Comment by MSThug** [comment]
Well I found this issue. For some reason my registration are coming in with IfAlreadyRegistered.Replace.  I was mistaken in thinking only the first registration is what I was seeing.  It was actually the last registration. Also, to be more clear I'm using Prism.DryIoc. I'm guessing there is something in there that is changing the default. I'm forcing it back to AppendNotKeyed since that is the default and now it works.

**Comment by dadhi** [comment]
Yeah, the modified rules are the first thing to look at. Glad, you found it.
