### ISSUE TITLE
RegisterServices extension issue with ConfigurePrimaryHttpMessageHandler and ConfigureHttpClient

### ISSUE THREAD

**Issue by sguryev** [dadhi/DryIoc#247]
I wanted to create named HttpClient with BaseAddress and ConfigurePrimaryHttpMessageHandler to handle GZip.

It looks like this calling chain doesn't work and last wins. So I can either have Handler or Config

```
containerRegistry.RegisterServices(s =>
{
    s.AddHttpClient("Name")
     .ConfigurePrimaryHttpMessageHandler(sp => new HttpClientHandler
     {
         AllowAutoRedirect = false,
         AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip
     })
     .ConfigureHttpClient(c =>
     {
         c.BaseAddress = new Uri("TODO");
     });
});
```

**Comment by dadhi** [comment]
Hi @sguryev 

I am not so much of a specialist in this topic and not sure that's even related to DryIoc. It would be better post you question on StackOverflow tagging with `dryioc` tag.

**Comment by sguryev** [comment]
Hi @dadhi thank you!

Yes I was under impression that it's DryIoc issue (I'm using Prism.DryIoc now). But I have same issue with Unity as well. So I guess it's something with Prims itself. 
I was able to make it work with Console App and HostBuilder.

Sorry!
