### ISSUE TITLE
Decorator with servicekey throws exception which gives invalid advice on how to fix the issue for the most common reason to use the servicekey

### ISSUE THREAD

**Issue by lassevk** [dadhi/DryIoc#25]
Was trying to register a service, for which there will be many concrete types, and add a decorator for one specific of them.

I tried the following code (this is LINQPad code, which is there are Dump calls in there):

    void Main()
    {
        var container = new Container();
        container.Register<IService, Service1>(serviceKey: "1");
        container.Register<IService, Service2>(serviceKey: "2");
        container.Register<IService, Decorator>(setup: Setup.Decorator, serviceKey: "1");
        
        $"Main.Before".Dump();
        foreach (var srv in container.Resolve<IEnumerable<IService>>())
            srv.Test();
        $"Main.After".Dump();
    }
    
    public interface IService
    {
        void Test();
    }
    
    public class Service1 : IService
    {
        public void Test() => $"Service1.Test()".Dump();
    }
    
    public class Service2 : IService
    {
        public void Test() => $"Service2.Test()".Dump();
    }
    
    public class Decorator : IService
    {
        private readonly IService _Service;
        public Decorator(IService service) => _Service = service;
    
        public void Test()
        {
            $"Decorator.Test()".Dump();
            _Service.Test();
        }
    }

This throws this exception:

> Registering Decorator 1 with not-null service key  does not make sense,because decorator may be applied to multiple service of any key.If you wanted to apply decorator to services of specific key please use `setup: Setup.DecoratorOf(serviceKey: blah)`

This advice does not work. First and foremost, there is no overload of ```Setup.DecoratorOf```` that has a `serviceKey` parameter. Instead there is an overload with `decorateeServiceKey`, but replacing it with that doesn't work either as then it doesn't decorate anything.

Instead I had to follow the advice from [here](https://bitbucket.org/dadhi/dryioc/wiki/Decorators) which gave me this code, that worked:

    container.Register<IService, Decorator>(setup: Setup.DecoratorWith(req => req.ServiceKey == "1"));

It would be nice if the exception gave the right advice (or that the overload be added or made to work, whichever is the case here)

**Comment by dadhi** [comment]
Thank you for pointing it out. 

Yes it should be `Decorator.Of(decorateeServiceKey: blah)`.

Strange that it was not working for you.

- I will fix the error message.
- Will check what's hapenning generally

**Comment by dadhi** [comment]
It is a little embarrassing, but there is indeed a bug here. 

Now fixed. The error message is also corrected.
I have also edited the dedicated section in the new version of docs:  https://github.com/dadhi/DryIoc/blob/master/Net45/DryIoc.Docs/Decorators.md#decorator-of-service-with-servicekey

**Comment by lassevk** [comment]
Speaking of fixed, do you have a plan for when new nuget packages that fixes this is deployed?

**Comment by lassevk** [comment]
Sounds good :)
