### ISSUE TITLE
Possibility to dispose singletons without disposing container.

### ISSUE THREAD

**Issue by mrukas** [dadhi/DryIoc#251]
Is there any possibility to unregister and dispose a registered singleton without disposing the corresponding container?

**Comment by dadhi** [comment]
Why? just curious.

You may dispose the singleton a nornal way by calling its Dispose method. 
But if you need to dispose its dependencies it requires the special kind of selectivity - what happens if other services depend on the same stuff?

**Comment by mrukas** [comment]
Im currently working on an plugin system for ASP.Net Core, were the user is possible to load and unload plugins during runtime. It works pretty well, but my problem is that i can't dispose the DI container because you can't replace the DI container asp.net core is using during runtime. If i would dispose the container i would have to create a new one an tell asp.net core to use it, sadly this is not possible during runtime.

**Comment by dadhi** [comment]
So you need some other approach then.

- Maybe you can isolate those plugins in the named scopes, then just drop the whole scope.
- Or you may copy the container with the separate singleton scope (using it `With(...)` methods) - but it probably will be hacking through the asp.net core abstractions.

**Comment by mrukas** [comment]
Sadly it is a pretty hacky solution. I needed to use a DI container thats able to register and unregister dependencies during runtime. I'm glad that DryIoc is able to do that. Will the singletons be disposed along with thr whole named scope? I need to assure that there arent any references left to my types from the loaded assembly.

**Comment by dadhi** [comment]
Here is the info on [Unregister](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md) - but the point it won't dispose the singleton.

Regarding named scope - I mean that you need to register your thing as `Reuse.ScopedTo(myPluginScopeName)` instead of singleton. Actually singleton by definition (at least for DryIoc) is something matching the lifetime of the container (application). Seems that your plugins are not singletons because they could be unloaded - I think the scope fits them better.

Btw, take the note from the doc above that if you won't to unload / unregister your plugin service, you better register it with `Setup.With(asResolutionCall: true)` - check the details https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md#make-injected-dependency-re-wireable-by-registering-it-asresolutioncall

**Comment by Havunen** [comment]
I agree with @dadhi here. Singleton by definition should be single instance per application lifetime. If you need to dispose Singleton then you should create custom scope.

**Comment by mrukas** [comment]
> 
> 
> Here is the info on [Unregister](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md) - the main point it won't dispose the already created singleton.
> 
> Regarding named scope - I mean that you need to register your thing as `Reuse.ScopedTo(myPluginScopeName)` instead of singleton. Actually singleton by definition (at least for DryIoc) is something matching the lifetime of the container (application). Seems that your plugins are not singletons because they could be unloaded - I think the scope fits them better.
> 
> Btw, take the note from the doc above that if you won't to unload / unregister your plugin service, you better register it with `Setup.With(asResolutionCall: true)` - check the details https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md#make-injected-dependency-re-wireable-by-registering-it-asresolutioncall

**Comment by mrukas** [comment]
> 
> 
> Here is the info on [Unregister](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md) - the main point it won't dispose the already created singleton.
> 
> Regarding named scope - I mean that you need to register your thing as `Reuse.ScopedTo(myPluginScopeName)` instead of singleton. Actually singleton by definition (at least for DryIoc) is something matching the lifetime of the container (application). Seems that your plugins are not singletons because they could be unloaded - I think the scope fits them better.
> 
> Btw, take the note from the doc above that if you won't to unload / unregister your plugin service, you better register it with `Setup.With(asResolutionCall: true)` - check the details https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md#make-injected-dependency-re-wireable-by-registering-it-asresolutioncall

Thanks for the help, but I'm still having a problem. 

If i register the services with `Reuse.ScopeTo(pluginName)` I need to open my scope manually by calling `container.OpenScope(pluginName)` and in this scope resolve my services by calling `Resolve` on the scope.

My Problem is that the services get resolved by calling GetService on the native IServiceProvider of my ASP.NET Core application. and therefore the services registered in a specific plugin scope are not found. I can't really change the way how these services get resolved, because this code is in external libraries loaded from Nuget packages.

Is there any way i can solve this? Maybe implementing an interface and write custom resolving logic?

Thanks in advance!

**Comment by dadhi** [comment]
> If i register the services with Reuse.ScopeTo(pluginName) I need to open my scope manually by calling container.OpenScope(pluginName)

No, you don't always need to OpenScope manually, instead you may use registration with `Setup.With(openResolutionScope: true)`. This is described in corresponding doc https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ReuseAndScopes.md#reusescopetotserviceservicekey

So I have an idea - if you will be able to introduce some roots for the plugin services, you may be able to dispose the the plugin sevices together with the root.

Or another idea, sorry... just thinking and writing it down.. use decorator. I would suggest to try it out.

For example, todo



> Is there any way i can solve this? Maybe implementing an interface and write custom resolving logic?

I would rather do it as a last-last resort.

**Comment by mrukas** [comment]
@dadhi I'm not quite sure if this is possible in my current situation. My problem is, that i do not have a specific service for a plugin. 
My plugins can register services on its own by adding their services to the IServiceCollection, after the app is already running. After the app has been started changes to the IServiceCollection do not really do anything. Therefore I extract the services added by the plugin to the IServiceCollection and register them manually in the DryIoc container. The problem is that some plugins would register services in this way:
` services.AddTransient<IService, Service>(provider =>
            {
             var service =  provider.GetService<IService2>
            });`

In the factory function the provider used to resolve IService2 does not know IService2 because i registered it in a scope with a specific name (plugin name) by `Reuse.ScopedTo(pluginName)`.
In fact all services of a plugin should be registered in a specific scope and this scope should be existing as long as the plugin is loaded and all services registered by this plugin should use this scope to resolve their services.

Would this behaviour be possible with decorators?

I'm not sure if its understandable what I'm trying to do. I know its a pretty complex and specific scenario. I'm just hoping that this is somehow possible.
Thanks for your help.

**Comment by dadhi** [comment]
>  i registered it in a scope with a specific name (plugin name) by Reuse.ScopedTo(pluginName)

You may register them normally as `Reuse.Scoped`, then they will be resolved/factoried from the nested scope in the decorator method. The decorator may be open-generic as in example accepting any service, or better it may filter by plugin namespace ...

**Comment by mrukas** [comment]
@dadhi Ah ok. I think i understand what you mean. Things starting to get clearer now. 👍 

Is there the possibility to pass a default value to the factory function when this syntax is being used: `      c.Register<IFoo>(Reuse.Scoped, Made.Of(_ => ServiceInfo.Of<FooFactory>(),
                f => f.GetOrCreate(Arg.Of<IResolverContext>(), Arg.Of<FactoryDelegate, Func<IFoo>>(), Arg.Of<string>())), setup: Setup.Decorator);`.

I would need to pass the pluginName to the factory, because i cant rely on the fact that external plugins use `var foo1 = scope.Resolve<IFoo>(new object[] { "1" });` and pass parameters when resolving the service.

Thanks!

**Comment by dadhi** [comment]
> I would need to pass the pluginName to the factory, because i cant rely on the fact that external plugins use var foo1 = scope.Resolve<IFoo>(new object[] { "1" })

You may pass it as a constant string, e.g. "fooBar", or as any custom value (even using the injection info) via `Arg.Index(n)` syntax. Look into this example to see how https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ExamplesContextBasedResolution.md#log4net-logger

> Is there the possibility to pass a default value to the factory function when this syntax is being used: c.Register<IFoo>(Reuse.Scoped, Made.Of(_ => ServiceInfo.Of<FooFactory>(), f => f.GetOrCreate(Arg.Of<IResolverContext>(), Arg.Of<FactoryDelegate, Func<IFoo>>(), Arg.Of<string>())), setup: Setup.Decorator);

Why do you use `Arg.Of<FactoryDelegate, Func<IFoo>>()` with the untyped `FactoryDelegate` returning object and the additional `Func`? 
Why not just `Arg.Of<FactoryDelegate<IFoo>>()` instead.

**Comment by mrukas** [comment]
Sorry this was my bad. I looked trough the tests in the link you send me. I thought the GetOrCreate [(https://github.com/dadhi/DryIoc/blob/dbdada17a31840bab4d134bfd788de6d50c8a20c/test/DryIoc.IssuesTests/GHIssue191_Optional_IResolverContext_argument_in_Func_of_service.cs#L33)](https://github.com/dadhi/DryIoc/blob/dbdada17a31840bab4d134bfd788de6d50c8a20c/test/DryIoc.IssuesTests/GHIssue191_Optional_IResolverContext_argument_in_Func_of_service.cs#L33) from the tests would be more similar to my use case than the GetOrCreate2, so i tried this type.

But its working now. I will now try to use the open generic decorator.

Thank you very much. This has been very helpfull for me.
Thank you also for this great project! 👍

**Comment by dadhi** [comment]
> I looked trough the tests in the link you send me.

Those tests are just examples - though coincidentally they also operate with the scopes.

> I will now try to use the open generic decorator

Don't forget to add the setup condition for them otherwise, they will be applied to everything putting the performance down (a bit), even if you just return the decorated service doing nothing. So the rule of thumb for decorators of any `T` - if you have the condition in decorator method, better move it into `setup: Decorator.With(condition: r => <your filter>)`

**Comment by mrukas** [comment]
Altough these are only examples, they are pretty similar to my case. I managed to get things working nearly as I need them.
I didn't want to use the Decorator.With condition because i do not really have a condition to check against. There is not really a base class or something that these services share. I wrote a function that does a little bit of relfection magic and registers the decorators only on the services i need.

It works and the scopes do get created by my decorators. I needed to register my decorators with Reuse.Transient, otherwise i wasn't able to resolve my services from the container directly without creating a new scope manually.

So in fact i do have my singletons now registered as scoped and the scope is available as long as my plugin is loaded.

Thank you very much!

**Comment by dadhi** [comment]
Cool!
Closing then.

**Comment by mrukas** [comment]
Sorry to bring up this laready closed topic, but I still have an issue.
It works, that my decoratos are creating the scopes for my plugins. These scopes should live as long as the plugin is loaded.

Sadly it now seems, that ASP.NET Core itself is disposing my scope. If I for example inject a service which has been registered with decorator in a controller, the scope gets created and the service injected. But after the controller method has run, the scope seems to get disposed by the framework. If the next request hits the controller method i get a `DryIoc.ContainerException: 'code: ScopeIsDisposed; ` exception.

Do you have any idea how i can handle this?

**Comment by dadhi** [comment]
Could you split the issue with preventDisposal into the separate isolated sample?

**Comment by dadhi** [comment]
closing as a stale
