### ISSUE TITLE
Project MVC5. Injection does not work in the controller with Areas.

### ISSUE THREAD

**Issue by itoop2019** [dadhi/DryIoc#252]
Hi!
Project MVC5. I do not have injection in the controller with Areas. In my example, these are Areas/Samsung/HistoryController.
https://localhost:44334/samsung/history
In the controller is not in areas - injection works.
Help...
![dryIoc-error-areas](https://user-images.githubusercontent.com/47772383/78014472-a6b9e500-7350-11ea-828a-979b285064a5.jpg)

**Comment by dadhi** [comment]
Hi @itoop2019б

Please add this optional argument into your `WithMvc(.., throwIfUnresolved: type => type.IsController())` method to recover the original DryIoc exception otherwise the provided info does not tell much.

**Comment by itoop2019** [comment]
link to my project:
https://drive.google.com/file/d/13xadpzlz9sa9TOTparFXdWecQu9Cq7cx/view?usp=sharing
![dryIoc-error-areas1](https://user-images.githubusercontent.com/47772383/78020338-f5b84800-7359-11ea-8034-dbf9a1313a0f.jpg)
![dryIoc-error-areas2](https://user-images.githubusercontent.com/47772383/78020341-f6e97500-7359-11ea-8805-957e47ac09d0.jpg)

**Comment by dadhi** [comment]
@itoop2019 I see from the message that `IPostDao` is not resolved. 
Did you register it... scoped?

**Comment by itoop2019** [comment]
Thanks!
I had two types of IPostDao))
Areas.Samsung.DAO.IPostDao and DAO.IPostDao
And I registered only one of them.
