### ISSUE TITLE
ResolveMany if singleton decorators decorates the first item only

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#254]
https://dotnetfiddle.net/E0b9WO 
This should work.

**Comment by dadhi** [comment]
Apparently `RegisterDelegate` works in v4.1.3 but broken in v4.1.4.
But `RegisterDelegateDecorator` is broken in both.

https://dotnetfiddle.net/E0b9WO

```cs
using System;
using System.Linq;
using DryIoc;
					
public class Program
{
	public static void Main()
	{
		var c = new Container();
		
		c.Register<I, A>(Reuse.Singleton);
		c.Register<I, B>(Reuse.Singleton);
		
		// works in 4.1.3 but doesn't in 4.1.4
		c.RegisterDelegate<I, I>(i => new D(i), setup: Setup.Decorator);
		
		// does not work
		//c.RegisterDelegateDecorator<I>(_ => i => new D(i));
		
		var ii = c.ResolveMany<I>().ToArray();
		
		Console.WriteLine(ii[0].GetType() + ", " + ii[1].GetType());
		Console.WriteLine(((D)ii[0]).Inner.GetType() + ", " + ((D)ii[1]).Inner.GetType());
	}
	
	interface I {}
	class A : I {}
	class B : I {}
	class D : I
	{
		public D(I i) { Inner = i; }
		
		public I Inner { get; set; }
	}
}
```

**Comment by hennys** [comment]
It also seems like 4.1.3 does not work either in case that the delegate is registered as Singleton as well: `c.RegisterDelegate<I, I>(i => new D(i), Reuse.Singleton, setup: Setup.Decorator);` 

So if you want the Decorator service to be a Singelton as well as the Decorated service, there no apparent way around that.

https://dotnetfiddle.net/ZcBKn5

**Comment by dadhi** [comment]
@hennys It is funny how this bug is so diverse and persistent. Thanks for the reporting. I will look.
