### ISSUE TITLE
Speed Optimization for short living applications

### ISSUE THREAD

**Issue by Fruchuxs** [dadhi/DryIoc#26]
We figured out, that we can speed up the executionen of an short living application (like a console application) with `Expression<TDelegate>.Compile(preferInterpretation: true)`, because of avoiding some JIT overhead.

Can you maybe add a rule to DryIoc, so we can switch between preferInterpretation: true and preferInterpretation: false for the compilation of the resolve trees?

**Comment by Fruchuxs** [comment]
We also tested the FEC, but the speed up was in our cases negligible.
Thanks for your acceptance.

**Comment by dadhi** [comment]
@Fruchuxs, what platform did you test?

**Comment by Fruchuxs** [comment]
Oh sorry, forget to advise:  .net core 2.1

**Comment by EamonNerbonne** [comment]
It's conceivable that on .net core 2.1 you might get a similar boost by enabling [tiered compilation](https://blogs.msdn.microsoft.com/dotnet/2018/08/02/tiered-compilation-preview-in-net-core-2-1/)

It's certainly worth trying out; if that really works well, it might render the interpretation of expression trees themselves moot (because the JIT would be interpreting IL, and the conversion to IL is fairly fast with FastExpressionCompiler).

**Comment by dadhi** [comment]
Hi @EamonNerbonne , are you suggesting add `<TieredCompilation>true</TieredCompilation>` and check?

**Comment by EamonNerbonne** [comment]
Yeah, that would be a start ;-).

But I have no experience with that (new) feature, so can't tell you about any gotchas - I mean I hope there aren't any, but it's conceivable it doesn't work with dynamically generated IL or some such thing.  Only one way to find out! ;-).

**Comment by Fruchuxs** [comment]
Will check but their measurements doesn't look promising.

**Comment by Fruchuxs** [comment]
**COMPlus_TieredCompilation**

true | false
-- | --
1,2543458 | 1,1927924
1,1643181 | 1,7478098
1,1927924 | 1,3724727
1,1572949 | 1,413623
*avg*  | *avg*  
1,1921878 | 1,431674475

Probes in seconds.
In my case it seems mostly faster, thanks for the info.

**Comment by EamonNerbonne** [comment]
Just a little worried about the high variance in those numbers - it might just be chance.

**Comment by Fruchuxs** [comment]
Yes, this is a general problem on my working machine (it's a laptop). As suggested [here](https://github.com/dadhi/DryIoc/issues/27#issuecomment-427792189). I assume it's a CPU boost / throttling Problem. But my measurements gives an idea that COMPlus_TieredCompilation=true is faster at cold start.

**Comment by dadhi** [comment]
@Fruchuxs ,

Cool actually. I was sceptical, but it is a visible difference. Moreover,  it affects dynamic methods as well. 

Thanks for trying!

**Comment by dadhi** [comment]
#45 should help.

**Comment by dadhi** [comment]
Here is the proof:

DryIoc v3:
```
                            Method |        Mean |      Error |     StdDev |  Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
---------------------------------- |------------:|-----------:|-----------:|-------:|--------:|------------:|------------:|------------:|--------------------:|
 BmarkMicrosoftDependencyInjection |    128.3 us |   1.591 us |   1.489 us |   1.00 |    0.00 |     13.7939 |           - |           - |            58.66 KB |
                      BmarkAutofac |    425.8 us |   2.081 us |   1.947 us |   3.32 |    0.05 |     76.6602 |      2.4414 |           - |           354.91 KB |
                  BmarkAutofacMsDi |    434.9 us |   1.827 us |   1.709 us |   3.39 |    0.03 |     80.0781 |      0.4883 |           - |           371.22 KB |
                        BmarkGrace | 17,839.6 us |  99.023 us |  87.781 us | 138.99 |    1.72 |    156.2500 |     62.5000 |           - |           781.49 KB |
                    BmarkGraceMsDi | 20,568.8 us | 116.222 us | 108.714 us | 160.39 |    2.00 |    187.5000 |     93.7500 |     31.2500 |           954.13 KB |
                       BmarkDryIoc | 47,340.9 us | 175.076 us | 146.196 us | 368.47 |    3.79 |     90.9091 |           - |           - |            759.4 KB |
                   BmarkDryIocMsDi | 46,669.8 us | 302.005 us | 282.496 us | 363.92 |    4.44 |    181.8182 |     90.9091 |           - |           855.37 KB |
```

DryIoc v4
```
                            Method |        Mean |       Error |      StdDev |  Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
---------------------------------- |------------:|------------:|------------:|-------:|--------:|------------:|------------:|------------:|--------------------:|
 BmarkMicrosoftDependencyInjection |    134.0 us |   2.1675 us |   2.0275 us |   1.00 |    0.00 |     13.7939 |      0.1221 |           - |            58.65 KB |
                       BmarkDryIoc |    145.3 us |   0.8318 us |   0.7374 us |   1.08 |    0.02 |     30.2734 |           - |           - |           140.35 KB |
                   BmarkDryIocMsDi |    161.6 us |   0.9626 us |   0.9004 us |   1.21 |    0.02 |     32.2266 |           - |           - |           149.19 KB |
                  BmarkAutofacMsDi |    665.2 us |   5.4804 us |   5.1264 us |   4.96 |    0.08 |    105.4688 |      3.9063 |           - |           487.64 KB |
                      BmarkAutofac |    673.2 us |   5.5615 us |   5.2022 us |   5.02 |    0.08 |    101.5625 |     18.5547 |           - |           470.39 KB |
                        BmarkGrace | 18,480.8 us | 100.5977 us |  89.1773 us | 137.83 |    2.35 |    156.2500 |     62.5000 |           - |           755.18 KB |
                    BmarkGraceMsDi | 21,640.4 us | 119.7309 us | 106.1383 us | 161.39 |    2.81 |    187.5000 |     93.7500 |     31.2500 |           926.88 KB |

```

**Comment by Fruchuxs** [comment]
Looks nice, now we need this Version out. :P 
Any release plans?

**Comment by enif-lee** [comment]
Wow... It's coooool
