### ISSUE TITLE
A single instance of controller cannot be used to handle multiple requests

### ISSUE THREAD

**Issue by itoop2019** [dadhi/DryIoc#260]
Hi Maksim!

I have a question, I don’t know where to write, I will write to you here.
Faced a problem that has already been described here:
https://bitbucket.org/dadhi/dryioc/issues/444/a-single-instance-of-controller-cannot-be

I would like to clarify - is there any solution to get away from this problem?

**Comment by dadhi** [comment]
Hmm, I am not working with MVC myself,
but it seems like controllers should be transient, here is the related SO answer.
https://stackoverflow.com/a/1792298/2492669

So you may opt-in for `Reuse.Transient` by specifying `controllerReuse` parameter https://github.com/dadhi/DryIoc/blob/master/src/DryIoc.Mvc/DryIocMvc.cs#L80
By default it would be `Reuse.InWebRequest`.

**Comment by itoop2019** [comment]
Thanks I got it.
I thought that it would be possible to breathe new life into the old project asp net MVC and take your container.
Now I see that it makes no sense. Too much to remake, easier to transfer to another technology, asp .net core.

I am very grateful to you for responding so quickly!
