### ISSUE TITLE
Dispose child container without disposing parent

### ISSUE THREAD

**Issue by mwhelan** [dadhi/DryIoc#269]
Hi

I am wanting to create the main container when my tests start, then create a child container for each test that is disposed at the end of the test. However, I was surprised to find that when I dispose the child container the parent is also disposed. Is there a way to change this behaviour?

```csharp
[Test]
public void should_dispose_child_without_disposing_parent()
{
    var parent = new Container();
    var child = parent.CreateFacade();  // same with WithRegistrationsCopy()
    child.Register<IService, Service>();

    child.Dispose();

    Assert.IsFalse(parent.IsDisposed);   // this line fails
}
```

Creating a child container with `parent.OpenScope()` works for disposing it without disposing the parent, but I don't think it lets me register items, which I would like to do.

Any advice much appreciated! Thanks.

**Comment by dadhi** [comment]
Related #259.

**Comment by mwhelan** [comment]
Thanks. So, it doesn't seem that it is possible at the moment. I look forward to hearing if this is the intended design or whether you might change it in the future.

**Comment by dadhi** [comment]
Check a more generic `.With(...)` method the possible options, e.g. #259 has an example. Meanwhile I will what's hapenning here.

> Creating a child container with parent.OpenScope() works for disposing it without disposing the parent, but I don't think it lets me register items

There is a way to add lightweight "registration" directly to scope via `Use` method:

```cs
var parent = new Container();
using (var test = parent.OpenScope())
{
    test.Use<IService>(new MockService());
}
```

**Comment by mwhelan** [comment]
OK, that's worth giving a go. Thanks again for the fast responses. Always appreciated.

**Comment by mwhelan** [comment]
Just to update, your suggestions of using more generic .With(...) method from 259 worked thanks. I can create a child container, override any registrations I want, and then when I dispose of the child the parent is no longer disposed as well.

```csharp
[Test]
public void child_lifecycle_should_be_independent_of_parent_lifecycle()
{
    var parent = new Container(rules => rules
        .WithConcreteTypeDynamicRegistrations());
    parent.Register<IService, Service>(Reuse.Singleton);

    // child can override parent registrations and parent is unchanged
    var child = CreateChildContainer(parent);
    child.UseInstance<IService>(new TestService(), IfAlreadyRegistered.Replace);
    child.Resolve<Concrete>().Service.ShouldBeOfType<TestService>();
    parent.Resolve<Concrete>().Service.ShouldBeOfType<Service>();
    
    // when child is disposed parent is unaffected
    child.Dispose();
    child.IsDisposed.ShouldBeTrue();
    parent.IsDisposed.ShouldBeFalse();
}

private IContainer CreateChildContainer(Container parent)
{
    var child = parent.With(
        parent.Rules,
        parent.ScopeContext,
        RegistrySharing.CloneAndDropCache,
        parent.SingletonScope.Clone());
    return child;
}

public interface IService { }
public class Service : IService { }
public class TestService : IService { }
public class Concrete
{
    public IService Service { get; }
    public Concrete(IService service)
    {
        Service = service;
    }
}
```

**Comment by dadhi** [comment]
@mwhelan Thanks for update, If you Ok I want to add this example to the docs.

**Comment by mwhelan** [comment]
Yes, that’s fine with me.
