### ISSUE TITLE
RegisterMapping does not respect initializers

### ISSUE THREAD

**Issue by MichalBrylka** [dadhi/DryIoc#272]
Hi,

I'm registering configuration items and decided it might be a good idea to validate them inside of initializers. Sometimes configuration items can be accessed via another service i.e. interface. Initializer is triggered if you request for original service, but not for the mapped one. 

I might consider registering initializers for interfaces as well but RegisterMapping seems to have only generic flavour and I have to register configurations via reflection - it might me possible but is cumbersome    

Here is a repro:
```csharp
//DryIoc.dll version=4.1.4
class InitializerWithMapping
{
    [Test]
    public void Example()
    {
        var container = new Container();

        var config = new Config(15);
        container.UseInstance(config);


        bool isValid = false;
        container.RegisterInitializer<Config>((setting, resolver) =>
            isValid = true //TODO perform validation logic 
        );

        container.RegisterMapping<IReadOnlyConfig, Config>();

        //var resolved = container.Resolve<Config>(); //this triggers validation 
        var resolved = container.Resolve<IReadOnlyConfig>();
        Assert.That(resolved.Number, Is.EqualTo(15)); //resolution works properly


        Assert.That(isValid, Is.True); //validation is not triggered
    }
}

interface IReadOnlyConfig
{
    int Number { get; }
}

class Config : IReadOnlyConfig
{
    public int Number { get; }

    public Config(int number) => Number = number;
}
```

**Comment by dadhi** [comment]
Hi @MichalBrylka 

The answer is to use [Decorators](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Decorators.md) directly.

Here we go https://dotnetfiddle.net/72C65Y

Full code:

```cs
using System;
using DryIoc;
					
public class Program
{
	public static void Main()
	{
        var container = new Container();

        var config = new Config(15);
		
		// NOTE: UseInstance does not work with decorators and initializer (which is kind of decorator in disguise)
        //container.UseInstance(config);	
		container.RegisterInstance(config); // or you may use `container.RegisterInstanceMany(config)` and avoid the call to RegisterMapping
        container.RegisterMapping<IReadOnlyConfig, Config>();
		
		// registers decorators for the Config and its public interfaces (maybe be constomized)
        container.RegisterMany<Config>(made: Made.Of(typeof(Program).GetMethod(nameof(ValidateConfig))), setup: Setup.Decorator);
		
		container.RegisterInstance<Action<Config>>(cfg => cfg.Number += 1);
        
        var validatedConfig         = container.Resolve<Config>();
		var validatedReadonlyConfig = container.Resolve<IReadOnlyConfig>();
    }
									   
	public static Config ValidateConfig(Config cfg, Action<Config> validator) {
		validator(cfg);
		Console.WriteLine($"Validating config with Number={cfg.Number}");
		return cfg;
	}
}

public interface IReadOnlyConfig
{
    int Number { get; set; }
}

public class Config : IReadOnlyConfig
{
    public int Number { get; set; }

    public Config(int number) => Number = number;	
}
```

**Comment by MichalBrylka** [comment]
@dadhi thanks for your quick response.
It kind of works - I mean with some polishing I can get what I want here without resorting to some hacks like building concrete RegisterInitializer method etc. 

But, in terms of initialization logic, how can we ensure, on IoC level, that initializer for concrete class can be called only once ? 

i.e.

``` csharp
var validatedReadonlyConfig = container.Resolve<IReadOnlyConfig>(); //call initializer here 
var validatedConfig = container.Resolve<Config>(); //here object is already initialized
```

**Comment by dadhi** [comment]
Make Decorator a singleton, but yes - you have multiple options:

```cs
        container.RegisterMany<Config>(made: Made.Of(typeof(Program).GetMethod(nameof(ValidateConfig))),
                                       //reuse: Reuse.Singleton;   //do this
									   setup: Setup.DecoratorWith(
                                           useDecorateeReuse: true //or that - I would prefer this acpproach, it also can be turn On in Container rules via `new Container(rules => rules.UseDecorateeReuseForDecorators)` 
                                       ));
```

**Comment by MichalBrylka** [comment]
nice, thanks.
but let's assume that you have own validator. We are registering it and would like to reuse. How can we do that with Made.Of (without ValidateConfig method)?
something like Made.Of((resolver, config) => resolver.Resolve<MyValidator>.Validate(config))

```csharp
//register with:  container.Register<MyValidator>(Reuse.Singleton);

public class MyValidator
{
    public void Validate(object instance) //parameter can be generic if needed
    {
        //TODO - add errors 
    }
}
```

**Comment by dadhi** [comment]
Like this maybe https://dotnetfiddle.net/72C65Y:
```
		var validator = new MyValidator();
		container.RegisterDelegate<Config, Config>(
            cfg => { validator.Validate(cfg); return cfg; },
			setup: Setup.DecoratorWith(useDecorateeReuse: true));
```

**Comment by MichalBrylka** [comment]
ok, superb. To be honest I'd still prefer that RegisterInitializer registration would call initializer once and before first resolution but since your proposals work for me - there is nothing else but give you another star and close the issue ;-)

**Comment by Leszek-Kowalski** [comment]
Hi,

I would still argue that the behavior of Initializers is counter-intuitive:
https://dotnetfiddle.net/xPDECq

I think RegisterMapping should respect Initializers as user would typically attach Initializer to the implementation, not service type.
@dadhi what`s your view on that ? Should the issue be reopened ?

**Comment by dadhi** [comment]
@Leszek-Kowalski 

Sometimes the implementation type is not known by Container e.g.
`container.RegisterDelegate<IService>(_ => CreateService())`. Until you call the delegate you don't know the implementation type - so you cannot attach the things to the implementation all the time, it is more of "implementation detail" pun intended.

That's why initializers and decorators in general designed around the service type which is always known. 

You may design your own thing for your case - like in this issue, so I would prefer to keep it closed.
