### ISSUE TITLE
DryIoc is magically property injecting a default (non-null) value

### ISSUE THREAD

**Issue by dansiegel** [dadhi/DryIoc#273]
# Description

Prism's INavigationService for Xamarin.Forms has a loose coupling with the Page that it needs to navigate from. It does this by implementing 2 interfaces and only being registered/resolved with one of them.

```cs
public class PageNavigationService : INavigationService, IPageAware
{
    private Page _page;
    Page IPageAware.Page
    {
        get => _page;
        set => _page = value;
    }
}
```

I am noticing that DryIoc is now resolving INavigationService, and then effectively doing this...

```cs
var navigationService = Resolver.Resolve(typeof(INavigationService));
va pa = (IPageAware)navigationService;
pa.Page = Resolver.Resolve(typeof(Xamarin.Forms.Page));
```

This creates an issue for us as the Page should be null until/unless we've set it to something. You can see our default rules that are now shared between Wpf, Xamarin.Forms, & Uno here.

https://github.com/PrismLibrary/Prism/blob/b6faee2a5571a2f8e7e68268bb36efbb81b88841/src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs#L24-L29

**Comment by dadhi** [comment]
Hi @dansiegel ,

I don't see anything related to property injection in the provided code link. So I wonder if you have other places with the container or those specific registration customizations.

Btw, I wonder why do you disable FastExpressionCompiler in the rules, FEC is the default and fastest option ongoing. If you need to support for interpretation on the specific platforms it is better to use `WithUseInterpretation`.

**Comment by dansiegel** [comment]
The only place we could really use it would be for WPF, and I believe there was an issue reported with the latest Prism.Container.Extension release where we added WithUseInterpretation... We don't do anything crazy with our registrations.
I'm not sure if it is doing it in the current release, but I was able to verify that this behavior is occurring in a branch where we're moving the Navigation Service to be a Scoped Service.

**Comment by dadhi** [comment]
Hmm, how I can test this behavior, any test to look at?

**Comment by dansiegel** [comment]
I found the issue... it seems there was a remnant of something special we were doing with DryIoc to resolve the NavigationService.

**Comment by dadhi** [comment]
Cool, Dan maybe you can quickly look at #274 , is it related?
