### ISSUE TITLE
Possible to register more services after IEnumerable<T> has been resolved once and add them to the collection automatically for future resolutions?

### ISSUE THREAD

**Issue by lassevk** [dadhi/DryIoc#275]
I noticed that an assumption I had in my projects, that I had never exercised until tonight, was incorrect.

The following code:

    void Main()
    {
        var container = new Container();
        container.Register<ITest, Test1>();
    
        var snapshot1 = container.Resolve<IEnumerable<ITest>>().ToList();
    
        container.Register<ITest, Test2>();
        var snapshot2 = container.Resolve<IEnumerable<ITest>>().ToList();
    
        Console.WriteLine(snapshot1.Count);
        Console.WriteLine(snapshot2.Count);
    }
    
    public interface ITest { }
    public class Test1 : ITest { }
    public class Test2 : ITest { }

Outputs 1 twice, the first resolution of `IEnumerable<ITest>` makes a snapshot of the currently registered services, and reuses it, even if I add another registration afterwards. My assumption was that resolving IEnumerables would calculate the contents each time, and thus output first 1, and then 2.

Is it possible to refresh the snapshot for the IEnumerable, or to disable such snapshots so that every time I resolve IEnumerable<Something>, it is recalculated?

**Comment by dadhi** [comment]
Yes, possible. Here is the info https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Wrappers.md#ienumerable-or-array-of-a

**Comment by dadhi** [comment]
Closing then
