### ISSUE TITLE
C# 9.0 compile time meta-programming

### ISSUE THREAD

**Issue by Havunen** [dadhi/DryIoc#277]
https://www.infoq.com/news/2020/05/c-sharp-source-generators/

What do you think about this? This could be new strategy for IoC container to be based on.

Using dummy placeholder attributes to decorate types with lifetime how they should be registered 
and then use compile time infomation to generate function to resolve the given type. To me it feels one could achieve close to 0 time overhead vs doing it by hand. And If one can debug that code it should be easy to fix possible issues.

**Comment by dadhi** [comment]
I doubt about SD to cover all use-cases. If they are not so different from T4 (but on compiler level) then we have the same problems but with another wrapping.

But... DryIoc has its own compile-time capabilities (based on T4), so I would expect it to be easily portable to SD.

My point is that SD is not a silver bullet, it won't solve fully the whole DI problem. My vision is that we need all capabilities: compile + runtime-based to handle both statically known and runtime calculated data.

**Comment by dadhi** [comment]
> Using dummy placeholder attributes to decorate types with lifetime how they should be registered

Btw,  you can do that with the DryIoc.MefAttributedModel extension from the start of DryIoc. At the time I have started to work on DryIoc, it was one of the primary goals.. Now things are shifted, but the extension is very capable at that regard.

**Comment by Havunen** [comment]
Im closing this as its not really an issue. Just an idea :)

**Comment by dadhi** [comment]
Let see to this whole SG buzz. I'll probably experiment with them anyway.
