### ISSUE TITLE
Lazy RegisterMapping to a singleton that gets removed

### ISSUE THREAD

**Issue by Artemigos** [dadhi/DryIoc#278]
I have a very weird use case for the container. What I need to achieve:

1. singleton instances that can be reset manually (old instance removed, new instance created when resolving)
1. multiple mappings to the same singleton that get updated when the singleton changes
1. the mappings do not get registered at once - one comes from a naming convetion, other are registered by hand

What I already did:

- for singletons I register them with `asResolutionCall: true`, and when the instance needs to be reset, I unregister and register again (again as signleton, again with `asResolutionCall: true`)
- to achieve multiple mappings with the same instance, I register the singleton as the implementation type, and use `RegisterMapping` for all interfaces, including the initial one - this way some of the mappings can be done after the initial registration (I also need to have implementation types explicitly in the registations list, so this helps)

Maybe it's better to explain this with code:

```csharp
public interface IService { }
public interface IOtherService { }
public class Service : IService, IOtherService { }

// naming convention registrations
container.Register<Service>(Reuse.Singleton, setup: Setup.With(asResolutionCall: true));
container.RegisterMapping<IService, Service>();
// manual registrations
container.RegisterMapping<IOtherService, Service>();

// application runs...
container.Resolve<Service>();
container.Resolve<IService>(); // this is the same instance as above
container.Resolve<IOtherService>(); // this is the same instance as above

// at some point - remove the singleton
container.Unregister<Service>();
container.Register<Service>(Reuse.Singleton, setup: Setup.With(asResolutionCall: true));

// later...
container.Resolve<Service>(); // this is a different instance than before
container.Resolve<IService>(); // this is the same instance as on line above
container.Resolve<IOtherService>(); // this is the same instance as on line above
```

This is where I run into problems - the `RegisterMapping` call caches the singleton it maps to regardless of the `asResolutionCall` flag, and I get the old instance for `IService` and `IOtherService`.

To mitigate this I tried to register a `DelegateFactory` instead of using `RegisterMapping`. Something like this:

```csharp
var factory = new DelegateFactory(ctx => ctx.Resolve(implementationType), knownImplementationType: implementationType);
container.Register(serviceType, factory);
```

This falls apart the moment open generics are involved. I've been looking throug avalable methods, parameters, read through most of documentation, looked at source code and I can't figure this out. I even considered writing my own `IReuse` or `Factory`, but that's easier said than done (I'm not sure what kind of behavior is expected from a factory).

This is my last resort - am I missing something? Is there a way to achieve this?

Btw, I am aware that I'm doing weird things here. The situation is that I'm swapping out a different IOC container and there's a lot of preexisting usage. I wish I could get rid of the singleton resetting in favor of scopes, but this is not something I can afford to do right now.

**Comment by dadhi** [comment]
@Artemigos Hi here,

So you essencially have two problems, replaceable singleton and mappings. Let's tackle them one by one.

Regarding replaceable singletom you may model it usine some kind of wrapper with replacing functionality. Here you may use DryIoc `Ref<T>` type but you may model it  like this:

```cs
public class SingletonRef<T>
{
    public X { get; private set; }
    public SingletonRef(T x) = X = x;
    public void Set(X x) => X = x;
}
```

Register the Ref type as singleton, it can be cached no problem, because we will operate on X.

Register X using `SingletonRef<X>.X` as factory. I will use RegisterDelegate but it may done via Made.Of as well
```cs

container.RegisterSingleton<SingletonRef<X>, X>(
    sref => sref.X);

```

Then whenever you want to replace X, tesolve its `SingletonRef<X>` and use set.

You may create a new X via `Container.New` to utilize the registered services...

**Comment by Artemigos** [comment]
Thanks for the response :)

The idea looked interesting, but it still doesn't handle open generics. This is what I'm doing:

```csharp
public class SingletonRef<T> : SingletonRef
{
    public SingletonRef(IContainer container)
        : base(container, typeof(T))
    {
    }

    public T Resolve()
    {
        return (T)base.ResolveObject();
    }
}

public abstract class SingletonRef
{
    private readonly IContainer container;
    private readonly Type implementationType;
    private object instance;

    protected SingletonRef(IContainer container, Type implementationType)
    {
        this.container = container ?? throw new ArgumentNullException(nameof(container));
        this.implementationType = implementationType ?? throw new ArgumentNullException(nameof(implementationType));
        this.instance = null;
    }

    public void Reset()
    {
        if (this.instance != null)
        {
            lock (this)
            {
                this.instance = null;
            }
        }
    }

    protected object ResolveObject()
    {
        var localInstance = this.instance;
        if (localInstance == null)
        {
            lock (this)
            {
                if (this.instance == null)
                {
                    this.instance = this.container.New(this.implementationType);
                }

                localInstance = this.instance;
            }
        }

        return localInstance;
    }
}

private static void RegisterSingleton(Container container, Type type)
{
    var refType = typeof(SingletonRef<>).MakeGenericType(type);
    container.Register(refType, Reuse.Singleton);
    container.Register(type, made: Made.Of(refType.GetMethod("Resolve"), ServiceInfo.Of(refType)));
}

private static void RegisterMapping(Container container, Type from, Type to)
{
    container.RegisterMapping(from, to);
}

private static void RemoveInstance(Container container, Type type)
{
    var refType = typeof(SingletonRef<>).MakeGenericType(type);
    if (container.IsRegistered(refType))
    {
        ((SingletonRef)container.Resolve(refType)).Reset();
    }
}
```

It works for plain types but the second line in `RegisterSingleton` method fails when trying to register an open generic:

```
DryIoc.ContainerException: 'code: RegisteringNotAGenericTypedefImplType; message: Unsupported registration of implementation SingletonRef<SingletonTest.Generic<>> which is not a generic type definition but contains generic parameters.
Consider to register generic type definition SingletonTest.SingletonRef<> instead.'
```

I've been attempting another idea that uses reflection based `Made.Of(...)` to get around the open generics, and defer the resolution of mappings. This is how I implemented it:

```csharp
private static void RemoveInstance(Container container, Type type)
{
    container.Unregister(type);
    container.Register(type, Reuse.Singleton, setup: Setup.With(asResolutionCall: true));
}

private static void RegisterSingleton(Container container, Type type)
{
    container.Register(type, Reuse.Singleton, setup: Setup.With(asResolutionCall: true));
}

private static void RegisterMapping(Container container, Type from, Type to)
{
    var resolveMethod = typeof(IResolver).GetMethod(nameof(IResolver.Resolve), new[] {typeof(Type), typeof(IfUnresolved)});
    container.Register(from, to, made: Made.Of(resolveMethod, ServiceInfo.Of(typeof(IResolver))));
}
```

It throws this:

```
DryIoc.ContainerException: 'code: RegisteredFactoryMethodResultTypesIsNotAssignableToImplementationType; message: Registered factory method return type Object should be assignable Or castable to implementation type SingletonTest.Class but it is not.'
```

I also think that DryIoc will not be able to figure out what I want in the `Type` parameter, so this probably isn't even worth pursuing. Instead I tried to use the generic `Resolve` methods, but this again doesn't want to work with open generic registrations.

If I can implement the methods `RegisterSingleton`, `RegisterMapping` and `RemoveInstance` to support also open generics, then I think I would have this solved.

Again, thanks for your help :)

**Comment by dadhi** [comment]
Ok here is the more simplified variant with open-generic and without the intermediate `RefSingleton` as I understood it - but probably I didn't.

https://dotnetfiddle.net/vEBLsB

```cs
using System;
using DryIoc;

public class Program
{
	public static void Main()
	{
		var c = new Container();

		c.Register<B>();
		
		c.RegisterMany(new[] { typeof(A<>) }, 
			reuse: Reuse.Singleton,
			setup: Setup.With(asResolutionCall: true));
	
		var i = c.Resolve<I<B>>();
		var j = c.Resolve<J<B>>();
		Console.WriteLine($"{i} == {j} is {i == j}");
		
		// we may decide to Dispose if the old A here
		(c.Resolve<A<B>>() as IDisposable)?.Dispose();
		
	    c.RegisterMany(new[] { typeof(A1<>) }, 
			reuse: Reuse.Singleton,
			ifAlreadyRegistered: IfAlreadyRegistered.Replace, // just replacing the old implementation 
			setup: Setup.With(asResolutionCall: true));
		
		i = c.Resolve<I<B>>();
		j = c.Resolve<J<B>>();
		Console.WriteLine($"{i} == {j} is {i == j}");
	}
				
	public interface I<T> {}
	public interface J<T> {}
	
	public class A<T> : I<T>, J<T> {
		public A(T b) {}	
	}
			
	public class B {}
	
	public class A1<T> : I<T>, J<T> { 
		public A1(T b) {}
	}
}
```

**Comment by Artemigos** [comment]
This wasn't *exactly* what I needed, but it put me on the right track and I found a solution. I will later share how I did it. Hopefully we will be using the library for a long time and maybe we will slowly move to better practices :)

**Comment by Artemigos** [comment]
I did more or less something like this:
(this isn't finalized, but works conceptually)

```csharp
public class RegistrationCache
{
    private readonly ConcurrentDictionary<Type, Type> cache = new ConcurrentDictionary<Type, Type>();
    private readonly ConcurrentDictionary<Type, HashSet<Type>> reverseCache = new ConcurrentDictionary<Type, HashSet<Type>>();

    public IReadOnlyDictionary<Type, Type> Cache => this.cache;

    public IReadOnlyCollection<Type> GetFromReverseCache(Type key)
    {
        return this.reverseCache[key];
    }

    public void RecordMapping(Type from, Type to)
    {
        this.cache[from] = to;
        this.reverseCache.AddOrUpdate(
            to,
            _ => new HashSet<Type> { from },
            (_, list) =>
            {
                list.Add(from);
                return list;
            });
    }
}

var container = new Container(rules => rules
    .WithDefaultIfAlreadyRegistered(IfAlreadyRegistered.Replace)
    .WithoutEagerCachingSingletonForFasterAccess());

private static void RemoveInstance(Container container, Type type)
{
    container.RegisterMany(cache.GetFromReverseCache(type).ToArray(), type, Reuse.Singleton, setup: Setup.With(asResolutionCall: true));
}

private static void RegisterSingleton(Container container, Type type)
{
    container.Register(type, Reuse.Singleton, setup: Setup.With(asResolutionCall: true));
    cache.RecordMapping(type, type);
}

private static void RegisterMapping(Container container, Type from, Type to)
{
    var newMappings = new HashSet<Type>(cache.GetFromReverseCache(to)) { from };
    container.RegisterMany(newMappings.ToArray(), to, Reuse.Singleton, setup: Setup.With(asResolutionCall: true));
    cache.RecordMapping(from, to);
}
```

This can be tested here: https://dotnetfiddle.net/U1YjQj

**Comment by dadhi** [comment]
Interesting, thanks for sharing. I will look into in detail later.
