### ISSUE TITLE
Possibility to make source files which are embedded to the project internal?

### ISSUE THREAD

**Issue by LegendaryB** [dadhi/DryIoc#280]
Hey,

when using DryIoc some source files are added to the project. For example the ImTools.cs
This class is public. When DryIoc is used in a library project these namespaces are visible to the "outside world". Would it be somehow possible to make them internal to supress this? I know that I could do that by hand but it would be needed to do this again when updating the DryIoc version right?

Kind Regards,
Daniel

**Comment by dadhi** [comment]
There is DryIoc.Internal source package where all public types made internal.

Just in case, if you need a dll there is DryIoc.dll package.

**Comment by LegendaryB** [comment]
Thanks for the quick response! 👍

**Comment by LegendaryB** [comment]
Sorry checked it now and when adding it as a nuget dependency the classes are still public. For example ImTools.cs

**Comment by dadhi** [comment]
Huh, strange will check.

**Comment by dadhi** [comment]
DryIoc.Internal v4.2 is released. You can check.

**Comment by LegendaryB** [comment]
Works like a charm, thank you @dadhi !
