### ISSUE TITLE
Cannot register grpc client using ms ioc and dryioc

### ISSUE THREAD

**Issue by jose8789** [dadhi/DryIoc#287]
Hi, I have written a prism wpf application that uses ms grpc to communicate with the backend service but I cannot register it using dryioc

            var serviceCollection = new ServiceCollection();
            serviceCollection.AddGrpcClient<ProvinceService.ProvinceServiceClient>(o =>
            {
                o.Address = new Uri("https://localhost:6006");
            });
            var container = containerRegistry.GetContainer();
            container.Register<IServiceScopeFactory, DryIocServiceScopeFactory>(Reuse.Singleton);
            container.Populate(serviceCollection);
bellow is the error 
...

 ---> System.InvalidOperationException: Could not resolve the address for gRPC client 'ProvinceServiceClient'.
   at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateCallInvoker(HttpClient httpClient, String name, GrpcClientFactoryOptions clientFactoryOptions)
   at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name)
   at Microsoft.Extensions.DependencyInjection.GrpcClientServiceExtensions.<>c__DisplayClass7_0`1.<AddGrpcHttpClient>b__0(IServiceProvider s)
   at DryIoc.Registrator.ToFactoryDelegate[TService](Func`2 f, IResolverContext r) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 7096

I am using packages
DryIoc.Microsoft.DependencyInjection 4.0.0
DryIoc 4.1.4

..

**Comment by dadhi** [comment]
Could you update DryIoc to the latest v4.2.1 and check if issue is reproduced. 
If yes - could you provide the full (smallish) sample app wich reproduce the issue?

**Comment by jose8789** [comment]
I dont know if I can update DryIoc to the latest as I am using the version that comes in with prism
But I will make a little sample that reproduced the issue

**Comment by dadhi** [comment]
Thanks.
For update you can go to csproj file and update the version attribute in the PackageReference.

**Comment by jose8789** [comment]
Unfortunetally I can not do it because there's prism comes with a version of dryioc if I want to update I would have to update the prism version itself

**Comment by dadhi** [comment]
I don't think the exception is related to Prism only.
Maybe you can create a simple ASP .Net Core app with the same small grpc setup. 

In addition I suggest to open issue at https://github.com/dansiegel/Prism.Container.Extensions

**Comment by dvabuzyarov** [comment]
> Unfortunetally I can not do it because there's prism comes with a version of dryioc if I want to update I would have to update the prism version itself

You can user the latest DryIoc with [Assembly Redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions).

**Comment by dadhi** [comment]
closing as no updates from the issue author
