### ISSUE TITLE
Recursive resolution ignores current scope .Use() instance

### ISSUE THREAD

**Issue by detoxhby** [dadhi/DryIoc#288]
The problems is represented by the following example code: https://dotnetfiddle.net/Nq2ImP

The problems persists even if the factory-based `.Use()` overload is used, no difference.

_Platform:_ .NET Core 3.1.5
_DryIoc version:_ 4.2.1

**Comment by dadhi** [comment]
Seems like the problem with the cache and the presense of AsyncExecutionFlow context makes it more obscure. Anyway, thanks for reporting. I will look.

**Comment by detoxhby** [comment]
> Seems like the problem with the cache and the presense of AsyncExecutionFlow context makes it more obscure. Anyway, thanks for reporting. I will look.

Using static context makes no difference, so it's probably related to resolution cache: https://dotnetfiddle.net/Cc4tUu

**Comment by detoxhby** [comment]
Can I help you with anything? Currently this bug is blocking one of our feature release. I don't want to rush you, just an approx. time would be fine about when will you able to investigate it.

Thanks!

**Comment by dadhi** [comment]
Will try to look Today

**Comment by dadhi** [comment]
Here is the working test - check `asResolutionCall` setup and check the results for explanation https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RulesAndDefaultConventions.md#injecting-dependency-asresolutioncall

But the problem still was there even with `asResolutionCall` - the good news is that fix is ready. I will release v4.2.2 shortly.

```cs
using NUnit.Framework;

namespace DryIoc.IssuesTests
{
    [TestFixture]
    public class GHIssue288_Recursive_resolution_ignores_current_scope_Use_instance
    {
        [Test]
        public void Test()
        {
            var c = new Container(scopeContext: new AsyncExecutionFlowScopeContext());

            c.Register<Child>(Made.Of(() => ChildFactory()), Reuse.Scoped,
                // NOTE: this is important to make the dependency 'dynamic' and be replaceable even if parent expression is cached
                // see https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RulesAndDefaultConventions.md#injecting-dependency-asresolutioncall
                Setup.With(asResolutionCall: true));
            
            c.Register<Parent>(Reuse.Scoped);

            // instance is resolved in outer scope
            using (var outer = c.OpenScope())
            {
                var outerParentInstance = c.Resolve<Parent>();
                Assert.IsNotNull(outerParentInstance);
                
                var outerChildInstance = c.Resolve<Child>();
                Assert.AreSame(outerParentInstance.Child, outerChildInstance);

                using (var _ = c.OpenScope())
                {
                    // inject instance
                    var inner = c.Resolve<IResolverContext>();
                    inner.Use(outerChildInstance);

                    // direct type resolution works
                    var innerChildInstance = c.Resolve<Child>();
                    Assert.AreSame(outerChildInstance, innerChildInstance);

                    // recursive type resolution skips the instance and calls the factory even though the instance is placed to the current scope
                    var innerParentInstance = c.Resolve<Parent>();
                    Assert.AreSame(innerChildInstance, innerParentInstance.Child);
                }
            }
        }

        public class Child
        {
            public int X { get; set; }
        }

        public class Parent
        {
            public readonly Child Child;
            public Parent(Child child) => Child = child;
        }

        public static Child ChildFactory() => new Child();
    }
}

``

**Comment by detoxhby** [comment]
What are the performance characterics using `asResolutionCall`? There are similar use cases in context of resolving the current user instance for every request and thus it is really hot code that will be called numerously.

**Comment by dadhi** [comment]
If you use `Use` to supply the service for Resolve then it is fast.
Otherwise it slightly slower but anyway it will use caches along the way.

**Comment by dadhi** [comment]
@detoxhby  Longer explanation: 

Basically there is no other way to patch Parent expression and the "patching" is slow by definition.
Using `asResolutionCall` will keep cached Parent expression intact at the cast of adding extra Resolve call which is still baked by resolution cache.

**Comment by dadhi** [comment]
@detoxhby Actually I will think about other possibilities, like replacing the service instance directly in Scope - but it will make things more complex and make more general cases without `Use` slower (**it should be proved though**). Also it is much more work. So I will release v4.2.2 as-is and postpone other things for the later.

I am open for ideas, help, and the new issues for the topic.

**Comment by detoxhby** [comment]
@dadhi thanks for the detailed explanation!

Thinking about the idea of `Use()` to do a full resolution process and then replace the already in-place instance for scope's cache. This way the factory wouldn't need any special treating and the only custom logic that would be necessary is the internal possibility to replace the direct instance as an "atomic" operation (or simply skip the call to the factory). I'm not sure if it is possible in a way of doing 2 phase swap to remain lock-free, but a higher level abstraction of letting the main resolver logic to have and pass on an optional instance would sounds better.
Memory usage caused by the extra stack param (which would be `null` for the 99% of time) may not worth it, as you said, need benchmark.
