### ISSUE TITLE
ServiceKey and ServiceProvider

### ISSUE THREAD

**Issue by SeriousM** [dadhi/DryIoc#293]
Hi Maksim, long time not seen :)! I hope you're fine.

I use dryioc combined with the serviceprovider.
Lets say I have a service in the serviceprovider IService and this IService is needed by other services in the serviceprovider.
Now I need a special version of IService for services in DryIoc, so I register IService with a service-key "special".
Now I have another service in DryIoc that needs the "default" IService (no servicekey) from serviceprovider but DryIoc resolver tells me that there is only the "special" registration and no other registration was found.
On the other hand when I register another IService with no servicekey in DryIoc the resolve works again - but this would mean alot of work and duplicate registrations and wrong settings.

I prepared two simple tests which demonstrate that the easy case is working (resolve IService direct with and without servicekey) but a dependent service that needs IService doesn't.

Is there a way to tell DryIoc to have a look into the serviceprovider registrations if the found registrations doesn't fit or is this a bug?

I hope you can help me!

Source:

Needed packages:
```xml
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.2.0" />

        <ProjectReference Include="..\..\src\DryIoc.Microsoft.DependencyInjection.AspNetCore2_1\DryIoc.Microsoft.DependencyInjection.AspNetCore2_1.csproj" />
```

```cs
using DryIoc.Microsoft.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using NUnit.Framework;

namespace DryIoc.IssuesTests
{
    [TestFixture]
    public class GenericServiceMix
    {
        [Test]
        public void ResolveDirect()
        {
            var services = new ServiceCollection();
            services.AddSingleton<MsDiServiceThatNeedsOptionsOption>(new MsDiServiceThatNeedsOptionsOption { Info = "A" });

            var container = new Container();
            container.Register<MsDiServiceThatNeedsOptionsOption>(
                serviceKey: "special",
                made: Made.Of(() => new MsDiServiceThatNeedsOptionsOption { Info = "B" }),
                reuse: Reuse.Singleton);

            var serviceContainer = container.WithDependencyInjectionAdapter(services);

            var resolvedMsDiService = serviceContainer.GetRequiredService<MsDiServiceThatNeedsOptionsOption>();

            Assert.NotNull(resolvedMsDiService);
            Assert.AreEqual("A", resolvedMsDiService.Info);

            var serviceFromDryIoc = serviceContainer.Resolve<MsDiServiceThatNeedsOptionsOption>(serviceKey: "special");

            Assert.NotNull(serviceFromDryIoc);
            Assert.AreEqual("B", serviceFromDryIoc.Info);

            var serviceFromMsDi = serviceContainer.Resolve<MsDiServiceThatNeedsOptionsOption>(serviceKey: null);

            Assert.NotNull(serviceFromMsDi);
            Assert.AreEqual("A", serviceFromMsDi.Info);
        }

        [Test]
        public void ResolveViaOptions()
        {
            var services = new ServiceCollection();
            services.AddOptions();

            services.AddSingleton<IMsDiServiceThatNeedsOptions, MsDiServiceThatNeedsOptions>();
            services.Configure<MsDiServiceThatNeedsOptionsOption>(c => c.Info = "Bob Builder");

            var container = new Container();

            container.Register<IDryIocServiceThatNeedsOptions, DryIocServiceThatNeedsOptions>(Reuse.Transient);
            
            // comment to avoid the "special" registation that just hides the default implementation
            container.Register<IOptions<MsDiServiceThatNeedsOptionsOption>>(
                serviceKey: "special",
                made: Made.Of(() => Options.Create(Arg.Index<MsDiServiceThatNeedsOptionsOption>(0)), 
                    r => new MsDiServiceThatNeedsOptionsOption { Info = "Alice Anger" }),
                reuse: Reuse.Singleton);

            var serviceContainer = container.WithDependencyInjectionAdapter(services);

            var resolvedMsDiService = serviceContainer.GetRequiredService<IMsDiServiceThatNeedsOptions>();

            Assert.NotNull(resolvedMsDiService);
            Assert.AreEqual("Bob Builder", resolvedMsDiService.GiveInfo());

            var resolvedDryIocService = serviceContainer.GetRequiredService<IDryIocServiceThatNeedsOptions>();

            Assert.NotNull(resolvedDryIocService);
            Assert.AreEqual("Bob Builder", resolvedDryIocService.GiveInfo());
        }

        public class DryIocServiceThatNeedsOptions : IDryIocServiceThatNeedsOptions
        {
            private readonly IMsDiServiceThatNeedsOptions msService;

            public DryIocServiceThatNeedsOptions(IMsDiServiceThatNeedsOptions msService)
            {
                this.msService = msService;
            }

            public string GiveInfo() => msService.GiveInfo();
        }

        public interface IDryIocServiceThatNeedsOptions
        {
            string GiveInfo();
        }

        public class MsDiServiceThatNeedsOptions : IMsDiServiceThatNeedsOptions
        {
            private readonly string info;

            public MsDiServiceThatNeedsOptions(IOptions<MsDiServiceThatNeedsOptionsOption> options)
            {
                info = options.Value.Info;
            }

            public string GiveInfo() => info;
        }

        public interface IMsDiServiceThatNeedsOptions
        {
            string GiveInfo();
        }

        public class MsDiServiceThatNeedsOptionsOption
        {
            public string Info { get; set; }
        }
    }
}
```

**Comment by dadhi** [comment]
Hi @SeriousM , 
I see that you are using AspNetCore2_1 package, is it the most?  Also, what is the referenced DryIoc version?

From the get-go I don't see a reason why keyed service is hiding the default one. I will check when I have time.

**Comment by SeriousM** [comment]
The dryioc version is the most recent one I've modified your test project,
that's why I needed 2.1 otherwise I would get version incompatibilities.

Thank you!

**Comment by dadhi** [comment]
Hi @SeriousM 

I have changed the registrations so that parameter with "special" service key is injected, 
but I fail to get the expected output for "Bob Builder" for MsDI. I am not knowledgeable with `Options` pattern, so I propose you to look. The full dotnet-script code will be in the next comment. See FIX and PROBLEM comments...

**Comment by dadhi** [comment]
#r "nuget: Microsoft.Extensions.DependencyInjection, 2.2.0"
#r "nuget: Microsoft.Extensions.Options, 1.0.0"
#r "nuget: DryIoc.Microsoft.DependencyInjection, 4.0.0"
#r "nuget: NUnit, 3.12.0"

using DryIoc;
using DryIoc.Microsoft.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using NUnit.Framework;

ResolveViaOptions();
WriteLine($"{nameof(ResolveViaOptions)} passed");

ResolveDirect();
WriteLine($"{nameof(ResolveDirect)} passed");

public void ResolveViaOptions()
{
    var container = new Container();

    var services = new ServiceCollection();
    services.AddOptions();
    services.Configure<MsDiServiceThatNeedsOptionsOption>(c => c.Info = "Bob Builder");

    // 1st FIX
    // services.AddSingleton<IMsDiServiceThatNeedsOptions, MsDiServiceThatNeedsOptions>();
    container.Register<IMsDiServiceThatNeedsOptions, MsDiServiceThatNeedsOptions>(
        Reuse.Singleton,
        made: Parameters.Of.Type<IOptions<MsDiServiceThatNeedsOptionsOption>>(serviceKey: "special"));

    container.Register<IDryIocServiceThatNeedsOptions, DryIocServiceThatNeedsOptions>(Reuse.Transient);

    // comment to avoid the "special" registation that just hides the default implementation
    container.Register<IOptions<MsDiServiceThatNeedsOptionsOption>>(
        serviceKey: "special",
        made: Made.Of(() => Options.Create(Arg.Index<MsDiServiceThatNeedsOptionsOption>(0)),
            r => new MsDiServiceThatNeedsOptionsOption { Info = "Alice Anger" }),
        reuse: Reuse.Singleton);

    var serviceContainer = container.WithDependencyInjectionAdapter(services);

    var resolvedMsDiService = serviceContainer.GetRequiredService<IMsDiServiceThatNeedsOptions>();

    // PROBLEM is it should be "Bob Builder"
    Assert.NotNull(resolvedMsDiService);
    Assert.AreEqual("Alice Anger", resolvedMsDiService.GiveInfo(), "MsDI");

    var resolvedDryIocService = serviceContainer.GetRequiredService<IDryIocServiceThatNeedsOptions>();

    Assert.NotNull(resolvedDryIocService);
    Assert.AreEqual("Alice Anger", resolvedDryIocService.GiveInfo(), "DiDI");
}

public void ResolveDirect()
{
    var services = new ServiceCollection();
    services.AddSingleton<MsDiServiceThatNeedsOptionsOption>(new MsDiServiceThatNeedsOptionsOption { Info = "A" });

    var container = new Container();
    container.Register<MsDiServiceThatNeedsOptionsOption>(
        serviceKey: "special",
        made: Made.Of(() => new MsDiServiceThatNeedsOptionsOption { Info = "B" }),
        reuse: Reuse.Singleton);

    var serviceContainer = container.WithDependencyInjectionAdapter(services);

    var resolvedMsDiService = serviceContainer.GetRequiredService<MsDiServiceThatNeedsOptionsOption>();

    Assert.NotNull(resolvedMsDiService);
    Assert.AreEqual("A", resolvedMsDiService.Info);

    var serviceFromDryIoc = serviceContainer.Resolve<MsDiServiceThatNeedsOptionsOption>(serviceKey: "special");

    Assert.NotNull(serviceFromDryIoc);
    Assert.AreEqual("B", serviceFromDryIoc.Info);

    var serviceFromMsDi = serviceContainer.Resolve<MsDiServiceThatNeedsOptionsOption>(serviceKey: null);

    Assert.NotNull(serviceFromMsDi);
    Assert.AreEqual("A", serviceFromMsDi.Info);
}

public class DryIocServiceThatNeedsOptions : IDryIocServiceThatNeedsOptions
{
    private readonly IMsDiServiceThatNeedsOptions msService;

    public DryIocServiceThatNeedsOptions(IMsDiServiceThatNeedsOptions msService)
    {
        this.msService = msService;
    }

    public string GiveInfo() => msService.GiveInfo();
}

public interface IDryIocServiceThatNeedsOptions
{
    string GiveInfo();
}

public class MsDiServiceThatNeedsOptions : IMsDiServiceThatNeedsOptions
{
    private readonly string info;

    public MsDiServiceThatNeedsOptions(IOptions<MsDiServiceThatNeedsOptionsOption> options)
    {
        info = options.Value.Info;
    }

    public string GiveInfo() => info;
}

public interface IMsDiServiceThatNeedsOptions
{
    string GiveInfo();
}

public class MsDiServiceThatNeedsOptionsOption
{
    public string Info { get; set; }
}
