### ISSUE TITLE
DryIoc.Microsoft.DependencyInjection 4.0 moves DryIocServiceProviderFactory inside DryIocAdapter?

### ISSUE THREAD

**Issue by wjrogers** [dadhi/DryIoc#299]
Hi,

I noticed that the latest version of DryIoc.Microsoft.DependencyInjection changes the service provider factory to a nested class inside `DryIocAdapter`. The inline documentation doesn't seem to reflect the change, and the sample ASP.NET Core 3.1 project doesn't compile when updated to DryIoc.Microsoft.DependencyInjection 4.0:

https://github.com/dadhi/DryIoc/blob/c7d989224a38264035e123d0e990e514706d4b44/samples/DryIoc.AspNetCore31.WebApi.Sample/Program.cs#L26

What's the "right" way to use this, now? Is there a new helper I missed? Or should I simply update the reference?

```csharp
.UseServiceProviderFactory(new DryIocAdapter.DryIocServiceProviderFactory(Startup.CreateMyPreConfiguredContainer()))
```

Thanks!

**Comment by dadhi** [comment]
@wjrogers Wooops, seems like I messed it up. Maybe random keypressing kicked in R# refactoring.
Thanks for catching, will revert it back.

**Comment by dadhi** [comment]
fixed
