### ISSUE TITLE
BitBucket wiki is down

### ISSUE THREAD

**Issue by Healios** [dadhi/DryIoc#305]
Hello

I just want to make you aware that the BitBucket wiki is down.

![image](https://user-images.githubusercontent.com/9387114/90774533-ed0be280-e2f7-11ea-8783-416e9762524c.png)

**Comment by dadhi** [comment]
@Healios Thanks.

This is a sign to move the docs.
Until then you can look them up directly here 
https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Home.md#users-guide

**Comment by dadhi** [comment]
The docs are updated and extended a bit, removing the bitbucket remains, all is available inside the docs/DryIoc.Docs folder with the help of 
https://github.com/dadhi/CsToMd.

The remaining part is to automate the doc gen on build and publish to ReadTheDocs.

**Comment by Healios** [comment]
Fantastic, thanks 👍

**Comment by dadhi** [comment]
@Healios Yeah, the docs are available from directly from the docs project in GitHub repo, GitHub is pointing to the same doc:
https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Home.md#users-guide
