### ISSUE TITLE
Create Unity3d package

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/DryIoc#31]
As part of my learning as how Unity3D works I will create unity package for your consideration and try run `hello world` with it.

https://github.com/grpc/grpc/blob/23b5b1a5a9c7084c5b64d4998ee15af0f77bd589/src/csharp/experimental/README.md

https://github.com/grpc/grpc/blob/44ed592cf0ec4b4c83d56366bc584f4719e42424/src/csharp/unitypackage/README.md

https://www.red-gate.com/simple-talk/dotnet/c-programming/extending-unity-editor-c/

http://hololenshelpwebsite.com/Blog/EntryId/3/Unity-5-Hello-World

**Comment by dzmitry-lahoda** [comment]
Seems there is no need to create package with Unity 2018 target .NET Standard 2.0. Sample will be enough.

1. Usual DI with trees and interpretation. To use after fixed for LINQ interpretation for Android IL2CPP https://fogbugz.unity3d.com/default.asp?1091189_1sqkebcrot7vvv9b
1.1 There are hooks which are run by Unity upon start. But registration here.
1.2. There are `start` routines so put some resolve here.
1.3. There is `update` ticks - put resolutions here for moving `square` ILogger and `ICalculator` and IFooBar<T> and IEventAggregator<T>(try register generic and resolve concrete, if not - work with concrete and document that).

2. DI Zero.
2.1. Create asmdef folder with usual project build by VS code
2.1. Build it to get tt run.
2.3. Same items as 1.
2.4 Document how to build and run.

**Comment by dzmitry-lahoda** [comment]
I will look into the issue I hope within some time frame. 

May be will do like 

https://github.com/PlayFab/PlayFabGameServer

StrangeIoC is a super-lightweight and highly extensible Inversion-of-Control framework, written specifically for C# and Unity.

**Comment by dadhi** [comment]
To not forget may be it make sense to add interpretation only mode (the Rule for that).

**Comment by dadhi** [comment]
@dzmitry-lahoda DryIoc now has a "fast" `Rules.WithUseInterpretation` mode. 
Maybe you can try to write a sample now?

**Comment by dadhi** [comment]
Likely Nope.
