### ISSUE TITLE
QUESTION : Resolve a dependancy in a model class using XF prism

### ISSUE THREAD

**Issue by LeoJHarris** [dadhi/DryIoc#313]
Hi @dadhi first of all nice work creating this sweet project,

I have a question though, i am using prism in my Xamarin forms project and I register services in my App.xaml.cs for the iOC container registration. I want to however get a dependancy service into a model instance, the model instances are being pulled from the server and so the contructor is not being called. If I were creating new instances then I could do constructor injection but right now the dependancy is null. 

What I was thinking of doing but I know its bad practise is hold a global variable instance of the container in app.xaml.cs class so any page in my application can access the container - only be required in this situation, but is there a better way to resolve the container or get hold of dependancy services in my model class when I am not creating new instances of them like this situation?

Trying to achieve some thing like this in a my model class and I do realize this doesnt even compile but you can see in my model class I have a IUserRepository service that I need.

```csharp
public string? GetActualContact() 
        {
            IUserRepository userRepository = DryIoc.Container.ContainerResolve<IUserRepository>(serviceKey: "userRepo"); // How to get access to the Container without declaring global varariable in app.xaml.cs. Need to get IUserRepository

            return  ContactRequestFlag == ContactRequestFlag.Approved ? (userRepository?.ReadPerson()!.UserInfo!.Uid != RequestedBy ? RequestedTo : RequestedBy) : string.Empty;
        }
```

**Comment by dadhi** [comment]
Hi @LeoJHarris 

This is more of a question than an issue, so I suggest to copy it to the StackOverflow and tag with the dryioc, prism, xamarin.

I am not a pro in a Xamarin Forms, so maybe other devs can help you there.

**Comment by LeoJHarris** [comment]
@dadhi no worries Ill reach out to brian thanks!

**Comment by LeoJHarris** [comment]
Got it working with following:

```csharp
private App App => (App)Xamarin.Forms.Application.Current;

        public string? GetActualContact() 
        {
            IUserRepository userRepository = App.Container.Resolve<IUserRepository>();

            return ContactRequestFlag == ContactRequestFlag.Approved ? (userRepository?.ReadPerson()!.UserInfo!.Uid != RequestedBy ? RequestedTo : RequestedBy) : string.Empty;
        }
```

Just encase anyone else stumbles across this 👍
