### ISSUE TITLE
Error for register IOptions<T> in prism  

### ISSUE THREAD

**Issue by SalimiHabib** [dadhi/DryIoc#317]
i have AgentOptions() as  below 
```
public class AgentOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentOptions" /> class.
        /// </summary>
        public AgentOptions()
        {
            WalletConfiguration = new WalletConfiguration { Id = "DefaultWallet" };
            WalletCredentials = new WalletCredentials { Key = "DefaultKey" };
        }
}
```
It add to service collection as below 
                ` services.AddOptions<AgentOptions>();`

And i need to inject this option  in view model constructor by using  `  IOptions<AgentOptions>`

but  i get this error :

**DryIoc.ContainerException
  Message=code: RegisteringOpenGenericRequiresFactoryProvider; message:
 Unable to register delegate factory for open-generic service Microsoft.Extensions.Options.IOptions<>.
You need to specify concrete (closed) service type returned by delegate.**

**Comment by dadhi** [comment]
@SalimiHabib Interesting, I will check what is going on.

**Comment by dadhi** [comment]
@SalimiHabib Hi again,

I have added the test with for the issue and it is working just fine: https://github.com/dadhi/DryIoc/blob/master/test/DryIoc.Microsoft.DependencyInjection.Specification.Tests/GHIssue317_Error_for_register_IOptions_in_prism.cs

Given the error info it seems, the culprit is the actual registration of the open-generic `Microsoft.Extensions.Options.IOptions<>` as a service type passed to the `RegisterDelegate`. 

Could you recheck on your side?

**Comment by dadhi** [comment]
@SalimiHabib 

I don't see from the `AddOptions`  implementation any use of descriptor with the `ImplementationFactory` (leading to the `RegisterDelegate`): https://source.dot.net/#Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs,4909ed65f60d1c84

**Comment by SalimiHabib** [comment]
@dadhi 
**Problem in full map view is as below :**

For implementing  [hyper-ledger Aries](https://github.com/hyperledger/aries-framework-dotnet) in project (xamarin form prism),there is samples and good guide about it , but all of them use Autofac for DI and , generic host  .
 **[sample  in xamarin form](https://github.com/hyperledger/aries-framework-dotnet/tree/master/samples/xamarin-forms)**   .

Developed extension to IServiceCollection make it easy to use builder pattern to add related service in DI ,but as you know prism dos'not support generic host to use this pattern .

**register type implementation  in prism is as below :**
```


`protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
         containerRegistry.RegisterServices(services =>
            {
               // services.AddSingleton<IPoolConfigurator, PoolConfigurator>();

                services.AddAriesFramework(builder => builder.RegisterEdgeAgent(
                  options: options =>
                  {
                      options.EndpointUri = "http://f6a90d4ee192.ngrok.io";

                      options.WalletConfiguration.StorageConfiguration =
                          new WalletConfiguration.WalletStorageConfiguration
                          {
                              Path = Path.Combine(
                                  path1: FileSystem.AppDataDirectory,
                                  path2: ".indy_client",
                                  path3: "wallets")
                          };
                      options.WalletConfiguration.Id = "MobileWallet";
                      options.WalletCredentials.Key = "SecretWalletKey";
                      options.RevocationRegistryDirectory = Path.Combine(
                          path1: FileSystem.AppDataDirectory,
                          path2: ".indy_client",
                          path3: "tails");

                      // Available network configurations (see PoolConfigurator.cs):
                      //   sovrin-live
                      //   sovrin-staging
                      //   sovrin-builder
                      //   bcovrin-test
                      //   local-test
                      options.PoolName = "local-test";
                  }, delayProvisioning: true));


            });`


```

after many times try  to add related service to IServiceCollection in prism all of them failed with different errors such as below :

`System.NotImplementedException
  Message=The method or operation is not implemented.`

**With stack trace** 

`  at Prism.Ioc.IExtendedContainerRegistryExtensions.RegisterScoped (Prism.Ioc.IContainerRegistry containerRegistry, System.Type serviceType, System.Type implementationType) [0x00015] in D:\a\1\s\src\Prism.Container.Extensions\IExtendedContainerRegistryExtensions.cs:158 
  at Prism.Ioc.IServiceProviderExtensions.RegisterTypesWithPrismContainer (Prism.Ioc.IContainerRegistry containerRegistry, Microsoft.Extensions.DependencyInjection.IServiceCollection services) [0x000f1] in D:\a\1\s\src\Prism.Container.Extensions\IServiceProviderExtensions.cs:51 
  at Prism.Ioc.IServiceCollectionExtensions.RegisterServices (Prism.Ioc.IContainerRegistry containerRegistry, System.Action`1[T] registerServices) [0x00021] in D:\a\1\s\src\Prism.Container.Extensions\IServiceCollectionExtensions.cs:29 
  at BlankApp1.App.RegisterTypes (Prism.Ioc.IContainerRegistry containerRegistry) [0x0000f] in G:\Users\Administrator\Source\Repos\BlankApp1\BlankApp1\App.xaml.cs:48 
  at Prism.PrismApplicationBase.Initialize () [0x00040] in /_/src/Forms/Prism.Forms/PrismApplicationBase.cs:147 
  at Prism.PrismApplicationBase.InitializeInternal () [0x00006] in /_/src/Forms/Prism.Forms/PrismApplicationBase.cs:94 
  at Prism.PrismApplicationBase..ctor (Prism.IPlatformInitializer platformInitializer) [0x00031] in /_/src/Forms/Prism.Forms/PrismApplicationBase.cs:72 
  at Prism.DryIoc.PrismApplication..ctor (Prism.IPlatformInitializer platformInitializer) [0x00000] in /_/src/Forms/Prism.DryIoc.Forms/PrismApplication.cs:25 
  at BlankApp1.App..ctor (Prism.IPlatformInitializer initializer) [0x00000] in G:\Users\Administrator\Source\Repos\BlankApp1\BlankApp1\App.xaml.cs:32 
  at BlankApp1.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0003d] in G:\Users\Administrator\Source\Repos\BlankApp1\BlankApp1.Android\MainActivity.cs:30 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <7d2292394f8c488b97f5bc2a0ac0240d>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.18(intptr,intptr,intptr)
`
and service that have more trouble is as below and only error that have been found related to agentOptions  in constructor .first post is related to this service :
 
        public DefaultProvisioningService(
            IWalletRecordService walletRecord,
            IWalletService walletService,
            IOptions<AgentOptions> agentOptions)
        {
            RecordService = walletRecord;
            WalletService = walletService;
            AgentOptions = agentOptions.Value;
        }

**Comment by dadhi** [comment]
@SalimiHabib I don't see the DryIoc in the stack trace. The example is not isolated enough to test it on my side.
So you may either isolate the code and add the PR with failing test OR/AND open the issue into the Prizm Xamarin forms repo.

**Comment by SalimiHabib** [comment]
I will go with  issue in Prism Xamarin forms.

Thank you  for  your time .
