### ISSUE TITLE
Does IHostedService run on application startup by DryIoc ?

### ISSUE THREAD

**Issue by SalimiHabib** [dadhi/DryIoc#318]
As you know `IHostedService  `interface use for create some Background task ,sequential task etc ...  ,  to start automatically by generic host before application startup (its  configurable ).
I use shiny in project , and  `Iservicecollection `in  `ConfigureServices `method of shiny startup show `AddHostedService`  extension method but after trying some service registration by  method , there is no outcome from container and service does not start automatically.

Today after googling i found `DryIoc.Microsoft.DependencyInjection` but i don't know that :

1- Is there any conflict to use  `DryIoc.Microsoft.DependencyInjection`  with shiny in prism that must be considered ?
2- Dose this solve `IHostedService  `automatic startup ?

thank you

**Comment by dadhi** [comment]
I don't know much about Shiny, and DryIoc.Microsoft.DependencyInjection does Not start the IHostedService. 

I would go the same route by opening issue Prism repo and maybe asking on the StackOverflow.

**Comment by SalimiHabib** [comment]
👍
