### ISSUE TITLE
[Idea] Integrate MediatR like middleware directly to DryIoc

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#32]
Cons:

- I already have (not accepted) [PR](https://github.com/jbogard/MediatR/pull/252) to MediatR 5, [here is my fork](https://github.com/dadhi/MediatR/tree/master/src/MediatR)
- Most of the MediatR code is for DI registration, will be dropped with direct integration
- The rest of the code is just a couple of middleware entities, for Request / Response and for Notifications
- I can come up with some new cool features... likely, probably :)
- Out-of-the-box solution with no dependencies

Cons:
- Stuff not related to DI.. at least ditectly
- Other?

Give me your likes or dislikes :)

**Comment by dadhi** [comment]
*gnoring dislikes..

An improved model for messages may look like:

```cs
interface IMessage<TRequest, TResponse> 
   where TResponse : U<NoResponse, Unit, IResponse<TRequest>> {}
```
Hmm.. ;-)

**Comment by dzmitry-lahoda** [comment]
Is it possible to get only some plumbing in DI and retain some implementation in example? I am afraid there should be tests from different domains (enterprise ui, server, desktop console, mobile, games, web sites, value in multi language micro service design) to ensure that messages are good.

**Comment by dadhi** [comment]
@dzmitry-lahoda,

> Is it possible to get only some plumbing in DI and retain some implementation in example?

My example above was a bit of joke :) I will be doing the simplest thing possible, so no pressing of Discriminated Unions. It also will be layers of abstraction as discussed in PR, so you can peek your thing.

**Comment by dzmitry-lahoda** [comment]
https://github.com/dadhi/DryIoc/commit/efdd045cb5c12423d7ed5f076f9c962c914b1c2b#diff-ecb85472b95ba475d6a564e8951d8baeR10461

**Comment by dadhi** [comment]
Ok, to this moment I have implemented MediatR ideas, but stripped to the core, to reveal the whole simplecity of it..

Now, after reading [Jeremy's take on this](https://jeremydmiller.com/2018/10/15/jasper-as-an-in-memory-bus-part-1/) I was thinking h9w to replace ad-hoc middleware idea with more DI controllable way. And the answer is.. tadah.. Decorator. Middleware is just a special case of decorating the target handler, then why don't just use a DryIoc decorators explicitly. The main benifit in addition to abstraction cut, would be controlling an order. I can just insert dercorator closer to handler, if I want. Then I have a decorators condition, reuse, stateless implementation via factory methods, etc. etc.

**Comment by dzmitry-lahoda** [comment]
May be add this as md file in documentation instead of releasing? I recall when Unity had mediator as sample in the book or as contrib project. Events are complex beasts with many possibilities regarding threading, order, resource usage, broadcasting, error handling, integration with event loops. So it looks that simplest approach may work in specific set, so experimental namespace would also work.

**Comment by dadhi** [comment]
I still release it in separate namespace. Easy to point someone to it. Documentation PR is welcome.

**Comment by dadhi** [comment]
Namespace `DryIoc.Messages` contains this thingy
