### ISSUE TITLE
Use Microsoft dependency with DryIoc in prism 

### ISSUE THREAD

**Issue by SalimiHabib** [dadhi/DryIoc#321]
hi
my setup:
```

`  <PackageReference Include="Prism.DryIoc.Extensions" Version="7.2.0.1054" />

    <PackageReference Include="Prism.Forms.Extended" Version="7.2.0.1054" />

    <PackageReference Include="Shiny.Prism" Version="7.2.0.1054" />
 `

```
i add som service to  `  protected override void RegisterTypes(IContainerRegistry containerRegistry) ` as below 

```

            containerRegistry.RegisterServices(services =>// PrismContainerExtension.Current.RegisterServices(x =>
            {
                // services.AddOptions<AgentOptions>();IPoolConfigurator,  PoolConfigurator

                services.AddLogging(logging => logging.AddConsole());
                services.Add(ServiceDescriptor.Singleton<ILoggerFactory, LoggerFactory>());
                services.Add(ServiceDescriptor.Singleton(typeof(ILogger<>), typeof(Logger<>)));


```

dryioc installed and used in xamarin only but other project that referenced and used by xamarin dos'n have  dryioc  you see in picture IServiceProvider is dryioc 

![image](https://user-images.githubusercontent.com/23046553/93662918-f57f4680-fa78-11ea-8ee5-d79392863fcc.png)

 we have error  for using ` Logger =  provider.GetRequiredService<ILogger<AgentBase>>();`  but as you see below source of error is Microsoft dependency 

![image](https://user-images.githubusercontent.com/23046553/93662956-4ee77580-fa79-11ea-91c9-4993a711d5ed.png)

is this correct and how it can be solved

**Comment by dadhi** [comment]
I am not using the Xamarin Prism personally so it is hard to answer. Please post the question on StackOverflow with dryioc, prism tags.

**Comment by SalimiHabib** [comment]
Thanks
