### ISSUE TITLE
Importing Constructor

### ISSUE THREAD

**Issue by starprog** [dadhi/DryIoc#324]
When upgrading from V5 to V6 and using Mef Attributes, Importing Constructor now throws an error stating that ImportingConstructor exists in both system component model and dryioc.

**Comment by dadhi** [comment]
Try to remove the reference to System.ComponentModel.Composition.

Btw, what is your target framework?

**Comment by dadhi** [comment]
@starprog ,
Did my suggestion helped?

**Comment by dadhi** [comment]
Please update DryIocAttriibutes.dll to v6.0.1. Hope it helps.

**Comment by starprog** [comment]
My apologies, I for some reason did not get notified on your reply but kept on working. I will check it out and let you know thanks.
