### ISSUE TITLE
Why is there no WithVariantGenericTypesInResolvedCollection?

### ISSUE THREAD

**Issue by jakeyeagley** [dadhi/DryIoc#328]
In ASP.net Core 3.1, VariantGenericTypesInResolvedCollection is now always disabled and it does not look like there's a way to enable it.

The SetMicrosoftDependencyInjectionRules will disable VariantGenericTypesInResolvedCollection here:

```
private static Rules SetMicrosoftDependencyInjectionRules(Rules rules)
        {
            rules._settings |= Settings.TrackingDisposableTransients;
            rules._settings &= ~Settings.ThrowOnRegisteringDisposableTransient;
###             rules._settings &= ~Settings.VariantGenericTypesInResolvedCollection;
            rules._factorySelector = SelectLastRegisteredFactory;
            rules._made._factoryMethod = DryIoc.FactoryMethod.ConstructorWithResolvableArguments;
            return rules;
        }

```

I also see a way to disable VariantGenericTypesInResolvedCollection here:

```
 public Rules WithoutVariantGenericTypesInResolvedCollection() =>
            WithSettings(_settings & ~Settings.VariantGenericTypesInResolvedCollection);
```

But I do not see a way to enable VariantGenericTypesInResolvedCollection.

Is my understanding correct, there is not a way to set VariantGenericTypesInResolvedCollection?
- If there is not a way to set VariantGenericTypesInResolvedCollection, why is there a way to disable it?
- If there is not a way to set VariantGenericTypesInResolvedCollection, is that by design?

I believe I can work around VariantGenericTypesInResolvedCollection being disable, however it would make the switch from ASP.net Framework to ASP.net Core easier for me if I could enable it.

**Comment by dadhi** [comment]
@jakeyeagley Thanks for reporting. The rule `WithVariant...` should be present but aparently I have deleted it by mistake. Will check.

Regarding the reason why it was excluded from the MS DI rules is that MS.DI does not support collection variance which may lead to unexpected results when resolving the framework components (unleast you know what you 're doing).
