### ISSUE TITLE
Delegate returning null throws exception RegisteredDelegateResultIsNotOfServiceType

### ISSUE THREAD

**Issue by publee** [dadhi/DryIoc#332]
Returning null from factory doesn't work:

```
container.RegisterDelegate(typeof(A), x => null);
var a = container.Resolve<A>(); //Exception RegisteredDelegateResultIsNotOfServiceType!!!
Assert.IsNull(a);
```

**Comment by dadhi** [comment]
@publee Thanks, looking.

**Comment by publee** [comment]
Wow, that was quick! 
Is there any workaround how to force resolve to null for specific type when we are using WithAutoConcreteTypeResolution?
Perhaps some RegisterInstance(type, null, ...), UseInstance(type, null, ...) overload?
Thank you.

**Comment by dadhi** [comment]
Let me test it, but you may try `Use` or
`RegisterInstance`. 
`UseInstance` is obsolete, don't use it.

**Comment by dadhi** [comment]
@publee 

Regarding the original issue if you look into the `RegisterDelegate` implementation https://github.com/dadhi/DryIoc/blob/130b91120a9d237d3de3d1e28c24e1a2be8ae430/src/DryIoc/Container.cs#L7382
you will see whete the check causing the exception added.

As a workaround until it fixed, you may just brew your own variant:

```cs

void RegisterDefault(IRegistrator r, Type serviceType) => r.Register(new DelegateFactory(r => null), serviceType, isStaticallyChecked: true);

```

**Comment by publee** [comment]
Proposed workaround works!!!
Thank you.
