### ISSUE TITLE
Reuse instance from parent scope in nested (child) scope

### ISSUE THREAD

**Issue by publee** [dadhi/DryIoc#333]
Hi,

I am trying to reuse instance in child scope, but container is always creating new one:

```
[Test]
public void TestNestedParentChildScope()
{
    var container = new Container(scopeContext: new AsyncExecutionFlowScopeContext());

    container.Register<A>(Reuse.Scoped);

    A a1;
    A a2;
    using (var s1 = container.OpenScope())
    {
        a1 = s1.Resolve<A>();
        using (var s2 = s1.OpenScope())
        {
            a2 = s2.Resolve<A>();
            Assert.AreSame(a1,a2);//This fails!!!
        }
        Assert.IsFalse(a1.IsDisposed);
        Assert.IsFalse(a2.IsDisposed);
    }
    Assert.IsTrue(a1.IsDisposed);
    Assert.IsTrue(a2.IsDisposed);
}

class A : IDisposable
{
    public void Dispose() => IsDisposed = true;
    public bool IsDisposed { get; private set; }
}
```

I believe the nested scope should first check if the parent scope already doesn't have the instance and only then create new instance.

Thank you.

**Comment by dadhi** [comment]
> I believe the nested scope should first check if the parent scope already doesn't have the instance and only then create new instance.

No, the `Reuse.Scoped` meant to create the instance in the nearest available scope with the matching name.
Here, you don't provide the names. 
But you can do this via `ScopedTo(name)` and then `OpenScope(name)` to open the matching scope.  
So this should work:

```cs
    var container = new Container(scopeContext: new AsyncExecutionFlowScopeContext());

    container.Register<A>(Reuse.ScopedTo("root"));

    A a1;
    A a2;
    using (var s1 = container.OpenScope("root"))
    {
        a1 = s1.Resolve<A>();
        using (var s2 = s1.OpenScope())
        {
            a2 = s2.Resolve<A>();
            Assert.AreSame(a1, a2);
        }
        Assert.IsFalse(a1.IsDisposed);
        Assert.IsFalse(a2.IsDisposed);
    }
    Assert.IsTrue(a1.IsDisposed);
    Assert.IsTrue(a2.IsDisposed);
```

**Comment by publee** [comment]
And how can I achieve my original goal (reuse from parent or create) without explicitly specifying the scope name in registration: `container.Register<A>(Reuse.ScopedTo("root"))`?

I tried to implement my own `IScope` where I would first check Parent, but it doesn't work because of casting to `(Scope)IScope`.

**Comment by dadhi** [comment]
Why do you need this, are you coming from the other IoC where this feature is available?
Curious, because I am hearing such request for the first time in a 6 years of working with IoCs.

**Comment by dadhi** [comment]
@publee Ok, when I am hearing the hard question regarding the not-implemented feature, my natural DryIoc answer will be [Decorators](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Decorators.md#decorators).
It is amost a mem in the DryIoc :)

I will play with the solution myself later. But briefly, you may register a static decorator method accepting your specific (or any) scoped service wrapped in `FactoryDelegate<IMyService> fac` as a parameter, plus accepting the `IResolverContext r` as a 2nd parameter. Then you may invoke the factory with the root scope instead of current one `return fac(r.Root)`.

**Comment by dadhi** [comment]
@publee It maybe be more complicated than I thought because we need to know first if service is created. For this we need the service `FactoryID` not the service type, so we can check via:

`var isCreated = r.Root.CurrentScope.TryGet(factoryId, our var service);`

The missing piece is the FactoryID... back to thinking.

**Comment by publee** [comment]
I am migrating project from Unity to DryIoc.

I am trying to replicate behavior of ChildContainer + ContainerControlledLifetimeManager
See https://www.tutorialsteacher.com/ioc/lifetime-manager-in-unity-container

I can mimic HierarchicalLifetimeManager by `Reuse.ScopedTo("CONTAINER")`+`container.OpenScope("CONTAINER")` on every child container
I can mimic PerResolveLifetimeManager by `Reuse.ScopedTo("PERRESOLVE")`+`container.OpenScope("PERRESOLVE")` on every resolve, but I am not sure about performance - would be nice to have kind of empty scope, which does not allocate memory upfront on creation.
But with replicating ContainerControlledLifetimeManager functionality looks like I am out of luck now :(
Thank you.

**Comment by dadhi** [comment]
@publee 

Got ya. Unity is reach but DryIoc is fine to :)

Here is the generic solution using the intersection of existing DryIoc functionaly (mainly decorator + wrapper). It is transparent enough if you remove the debug things and give it a nicer names. Should be performant, nothing too fancy is here.

https://dotnetfiddle.net/zl9FZU

Just a link (typed on phone), I will insert the full code here and add it into the docs later.

**Comment by publee** [comment]
Works!!!
Thanks again.

**Comment by dadhi** [comment]
Good. Let's keep it open until added to the docs.

**Comment by dadhi** [comment]
Added to the docs https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Decorators.md#reusing-the-scoped-service-from-the-parent-scope
