### ISSUE TITLE
MefAttributedModel: TypeLoadException in .NET Framework 4.6.1

### ISSUE THREAD

**Issue by OronDF343** [dadhi/DryIoc#339]
After upgrading to the latest NuGet package versions:

`    TypeLoadException: Could not load type 'System.ComponentModel.Composition.ExportFactory``1' from assembly 'DryIocAttributes, Version=6.0.1.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768'.`

At this line:

` var container = new Container().WithMefAttributedModel()`

I'm using System.ComponentModel.Composition from GAC (the NuGet package just adds a reference to the GAC). All projects in the solution currently target net461.

New package versions (not working): DryIoc.dll v4.5.0, DryIocAttributes.dll v6.0.1, DryIoc.MefAttributedModel.dll v6.0.1
Old package versions (working): DryIoc.dll v4.2.0, DryIocAttributes.dll v5.0.0, DryIoc.MefAttributedModel.dll v5.0.0

**Comment by dadhi** [comment]
@OronDF343 
:( sigh, 2will try out when I have time

**Comment by dadhi** [comment]
@OronDF343 Huh, I know what the problem is.
The **DryIocAttributes** was updated but not the **DryIoc.MefAttributedModel.dll** which still expects the ExportFactory in Attributes but not in the System.ComponentModel.Composition. 

So I need to update DryIoc.MefAttributedModel.dll

**Comment by dadhi** [comment]
@OronDF343 
I have released the DryIoc.MefAttributedModel.dll v6.0.2, try it out.

**Comment by OronDF343** [comment]
@dadhi 
Issue resolved, thanks for the quick fix!
