### ISSUE TITLE
Resolving Wrapped Keyed Services With Condition Fails

### ISSUE THREAD

**Issue by MaxHampton** [dadhi/DryIoc#34]
I'm using DryIoc in a Xamarin app, with Prism as the Mvvm framework. 

I recently updated Prism, which caused my DryIoc version to update from 2.x to 3.0.

In 2.x I was using a generic method to register types for specific services:

    public static void Register<TService, TImplementation, TFactory>
    (
      this IContainerRegistry This,
      object metadataKey
    ) where TImplementation : TService
    {
      This.GetContainer()
          .Register<TService, TImplementation>(
            setup: Setup.With(
              metadataKey,
              (RequestInfo r) => r.Parent.ServiceType.IsAssignableTo<TFactory>()));
    }

And I was able to resolve this using:

    TFactory
    (
      IEnumerable<Tuple<Func<TService>, metadataType>> serviceFactories 
    ){ }

In 3.0 this fails, in the constructor the enumerable is empty. The goal is to register keyed Service implementations, and resolve them as an enumerable in a specific parent. How should I update this for 3.0?

In 3.0, registration in the generic has changed slightly due to the removal of the RequestInfo class, and uses Request instead.

TFactory is also registered with the container.

Then, I have a registration:
```
containerRegistry.GetContainer().Register<TService>(
  setup: Setup.With(
    condition: r => !r.Parent.ServiceType.IsAssignableTo(typeof(TFactory))),
        made: Made.Of(
          r => ServiceInfo.Of<TFactory>(), 
          f => f.Create(Arg.Of<metadataType>())));
```
Which I use elsewhere through a constructor injected parameter as:
`
ctor
(
  Func<metadataType, TService>
)
`

**Comment by dadhi** [comment]
Mm, I will check Tomorrow.

But nothing crucial changed in regard to your registrations.

Maybe you can create a PR with complete failing test in `DryIoc.IssueTests` project?

**Comment by MaxHampton** [comment]
Sure, I'll take a look and see if I can get a PR put together for that, thanks for taking a look.

**Comment by MaxHampton** [comment]
I've had other things that I've been focusing on here, and have decided to postpone the Prism update. When I look at that upgrade in the near future I'll take a look at this again and create the repro if it is still an issue. I'll close this for now, thanks.
