### ISSUE TITLE
WaitForItemIsSet waits forever in v4.5.0

### ISSUE THREAD

**Issue by Nefarion** [dadhi/DryIoc#340]
I have a rather complicated setup, i made a PR with the failing test.

The same setup is working fine with 4.4.1, and it spins forever in 4.5.0.

[WaitForItemIsSet](https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.cs#L11657-L11664)

I think it is because dryioc is trying to resolve the `Arg.Of<Func<Session>>()` inside the `Made.Of` immediately instead of waiting until the instance is needed/needs to be constructed.

**Comment by dadhi** [comment]
> I think it is because dryioc is trying to resolve the Arg.Of<Func<Session>>() inside the Made.Of immediately instead of waiting until the instance is needed/needs to be constructed.

Thanks for the investigation.
I was even surprised that no issues where found after the v4.5 release - the changes were rather bold. Though I have a big regression suite.

Now it is a bit rfreshing

**Comment by dadhi** [comment]
Here is the working version of the test https://github.com/dadhi/DryIoc/blob/master/test/DryIoc.IssuesTests/GHIssue340_WaitForItemIsSet_does_never_end.cs

with regard to the fix in v4.5.1

**Comment by dadhi** [comment]
v4.5.1 is out on NuGet

**Comment by Nefarion** [comment]
@dadhi argh, yes i forgot to save the Func, not call it, my bad! Thanks for the fix!
