### ISSUE TITLE
Scope validation for Transient does not work as expected

### ISSUE THREAD

**Issue by dashkodo** [dadhi/DryIoc#343]
Validation work perfect when I'm trying to resolve scoped dependency into singleton
But when I'm trying to do the same with trainsient dependency resolved into singleton I'm actually capturing it.					

Reprosteps:
```

using System;
using DryIoc;
public class Program
{
	interface ILog{}	
	class HttpContextAccessor{}
	class ScopedLog: ILog{ public ScopedLog(HttpContextAccessor accessor){}}

	public static void Main()
	{
		var container = new Container();
		
		container.Register<HttpContextAccessor>(Reuse.Scoped); // throw exception as expected		
		//container.Register<HttpContextAccessor>(Reuse.Transient); // does not throw exception
		container.RegisterDelegate<HttpContextAccessor, ILog>(arg => new ScopedLog(arg), Reuse.Singleton);
		container.Validate();
        
		using (var scope = container.OpenScope())
                {
                      Console.WriteLine(scope.Resolve<ILog>().GetType());
                }
	}
}
```

**Comment by dadhi** [comment]
@dashkodo DryIoc does not prevent the Transient to be injected into Scoped or Singleton, because (at least originally) the idea is the Transient does not have a lifetine at all - you are saying that the service may be created anywhere or anytime. Usually those are stateless services or with the temporary state...

But I may add the rule to enable its validation.

**Comment by dadhi** [comment]
Here is existing issue #216

**Comment by dashkodo** [comment]
Cool, thanks

**Comment by dadhi** [comment]
Here is the related part of the docs https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ReuseAndScopes.md#reuse-lifespan-diagnostics

Tracking it here to fix some soelling errors and explain more on the Transient convention.
