### ISSUE TITLE
Scope is disposed before parent when using facade

### ISSUE THREAD

**Issue by LinkiPinki** [dadhi/DryIoc#344]
Hi there,

I was having trouble figuring out why a Service got disposed before I left the scope from which I resolved the service. Turns out I was able to reproduce it.

Inline Example:
```cs
IContainer root = new Container();

root.Register<MyDisposable>(Reuse.Scoped);

// this happens within the DryIoc-MsDI adapter when ASP handles an http request 
using var scope = root.OpenScope();
var ctx = root.WithCurrentScope(scope.CurrentScope);

// some service is resolved, that requires the disposable
ctx.Resolve<MyDisposable>();

// another service is resolved, that depends on `IContainer` which it will receive from the context given to ASP
// now, `container == ctx` which should be fine since the `WithCurrentScope` call returns an instance of `Container`
var container = ctx.Resolve<IContainer>();

// the service now creates a facade for and works with it. After it's done, the facade is disposed.
using (container.CreateFacade())
{
  // do anything at all, it doesn't matter
}

scope.Resolve<MyDisposable>(); // throws because scope is disposed
```

Example with classes and constructor injection:
```cs
using System;
using DryIoc;

public static class Program
{
public class MyDisposable : IDisposable
{
  public bool IsDisposed { get; private set; } = false;

  public void Dispose()
  {
    IsDisposed = true;
  }
}

public class RootService // might be an asp web controller or something similar
{
  private readonly ServiceThatNeedsDisposable _a;
  
  private readonly ServiceThatNeedsFacade _b;

  public RootService(ServiceThatNeedsDisposable a, 
                     ServiceThatNeedsFacade b)
  {
    _a = a;
    _b = b;
  }

  public void DoSomething()
  {
    _b.DoComplexStuff();
    Console.WriteLine(_a.DisposableInstance.IsDisposed); // Expected result: "False", Actual result: "True"
  }
}

public class ServiceThatNeedsDisposable
{
  public MyDisposable DisposableInstance { get; }

  public ServiceThatNeedsDisposable(MyDisposable d)
  {
    DisposableInstance = d;
  }
}

public class ServiceThatNeedsFacade
{
  private readonly IContainer _ctx;

  public ServiceThatNeedsFacade(IContainer ctx)
  {
    _ctx = ctx;
  }

  public void DoComplexStuff()
  {
    using var facade = _ctx.CreateFacade();
    
    // do something, no matter what
    // facade is disposed after call
  }
}

public static void Main()
{
  IContainer root = new Container();

  root.Register<MyDisposable>(Reuse.Scoped);
  root.Register<RootService>();
  root.Register<ServiceThatNeedsDisposable>();
  root.Register<ServiceThatNeedsFacade>();

  using var scope = root.OpenScope();
  using var ctx = root.WithCurrentScope(scope.CurrentScope);

  var service = ctx.Resolve<RootService>();
  service.DoSomething();
}
```

Turns out, that when calling `CreateFacade()` the `_ownCurrentScope` of the parent container is copied into the facade. When disposing the facade, it disposes that parent scope and therefore all services within.

My guess is, that the call to `IContainer.With()`  from `CreateFacade()` should provide a child Scope of the parent container scope or something along the lines.

Thanks in advance for looking into it.

**Comment by dadhi** [comment]
@LinkiPinki Thanks for the detailed reproduction samples.

As I understood `WithCurrentScope()` is something you've decided to use. Why do you need it? I mean the `scope` returned from the call to `OpenScope()` is the scoped `IResolverContext`. `OpenScope` internally calls `WithCurrentScope` - you don't need to.

```cs
using var scope = root.OpenScope();
  using var ctx = root.WithCurrentScope(scope.CurrentScope); // unnecessary

```

**Comment by LinkiPinki** [comment]
The call in question happens here](https://github.com/dadhi/DryIoc/blob/260e7f395fd701d197c77f8d8c4933cde05d27b4/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L255) in the Microsoft DI Adapter.

As far as my understanding goes, it is called every time before ASP creates a new Controller instance after capturing an HTTP request. In my example `ctx` represents the context that is used by ASP to resolve the controllers.

**Comment by dadhi** [comment]
@LinkiPinki 

As I remember, it was done for performance reasons. The `OpenScope()` in the `Container` should consider more conditions:

https://github.com/dadhi/DryIoc/blob/260e7f395fd701d197c77f8d8c4933cde05d27b4/src/DryIoc/Container.cs#L4737

Regarding the `CreateFacade` there is a note in the [docs](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/KindsOfChildContainer.md#facade) that the method is just a sugar for the more generic `With()` method. You may call it directly and provide any scope you need:

```cs
IContainer With(IResolverContext parent, Rules rules, IScopeContext scopeContext, RegistrySharing registrySharing, IScope singletonScope, IScope currentScope)
```

**Comment by LinkiPinki** [comment]
Hm, so what should I take from this? I've used this as a workaround already:

```cs
// private readonly IContainer _ctx

using (
  var facade = _ctx.With(
    _ctx,
    _ctx.Rules
        .WithDefaultRegistrationServiceKey(ContainerTools.FacadeKey)
        .WithFactorySelector(Rules.SelectKeyedOverDefaultFactory(ContainerTools.FacadeKey)),
    null,
    RegistrySharing.CloneButKeepCache,
    _ctx.SingletonScope,
    _ctx.CurrentScope == null ? null : new Scope(_ctx.CurrentScope)
  )
)
{
  // [...]
}
```

This is more-or-less exactly what `CreateFacade` does, except that I create a new child Scope as `currentScope`. In my opinion this is how a facade should work too, especially since it otherwise creates this odd issue with the disposable instances. I don't think updating the `CreateFacade` similar to this would be a breaking change, either.

**Comment by dadhi** [comment]
@LinkiPinki 

Good.. so basically you are opening a new scope if it was not already opened here:
```cs
_ctx.CurrentScope == null ? null : new Scope(_ctx.CurrentScope)
```

I don't think that in the current state it is the default behavior candidate.  
For me, it is hard to predict all the consequences of changing to this. 

Maybe it makes sense to add the optional parameter  `openScopeIfNotPresent` (think about the better name) for the `CreatefFacade`. What do you think?

**Comment by LinkiPinki** [comment]
@dadhi 

I'm not sure if I misunderstand you but I think I'm doing the opposite of what you're saying.

The last parameter of `.With` is becoming the `_ownCurrentScope` of the newly created container:

https://github.com/dadhi/DryIoc/blob/260e7f395fd701d197c77f8d8c4933cde05d27b4/src/DryIoc/Container.cs#L991-L1003

The current behavior is, that the facade receives the exact same scope as the source container. For root containers `null` is copied into the facade as scope and both containers hold no scope. When creating a facade from a scoped container, the facade will reference the same scope object. Upon disposal of the facade the parents `_ownCurrentScope` is disposed with it!

With my change a source container without an own scope still creates a facade without a scope. The behavior remains the same.  If the source container does have a scope attached, a new scope is created instead that references the scope of the source container **as parent**, instead of making it it's own scope.

Now that I've looked at it further I'm beginning to think that the issue might even be within the `With` function. When the source container has a scope attached and no `currentScope` argument is provided, it will always create a container that breaks `IDisposable` affiliations. Maybe creating a new child scope if no scope is provided explicitly would be an option.

For me the behavior looks invalid and not like a default that should be toggle-able.

**Comment by dadhi** [comment]
@LinkiPinki Sorry, you're right. I am seeing what I want to see :/

Now it makes sense. I will add the behavior into the upcoming version, or you may create the PR if you want to.

**Comment by LinkiPinki** [comment]
@dadhi Thank you! 

Question is, where should this behavior be?

Fixing it for `CreateFacade` would solve _my_ problem but won't stop you from using `With` (or `WithNoMoreRegistrationAllowed`) to create a container that breaks upon disposal.

Maybe it would make sense to include the child context instantiation in these functions?

**Comment by dadhi** [comment]
Not sure, but will think while adding it.

**Comment by dadhi** [comment]
@LinkiPinki  I will probaly change the original `CreateFacade` to clone the scopes (at the moment I have added separate `CreateFacadeAndCloneNodes`). It will probably break someone, but otherwise it maybe considered as fix (and the old behavior is simply restored via added `WithFacadeRules()`).
