### ISSUE TITLE
CommonServiceLocator and DryIoc 4.5.1

### ISSUE THREAD

**Issue by polyester941** [dadhi/DryIoc#345]
Hi,

In my project I installed DryIoc.CommonServiceLocator on latest version. As a dependency it installs DryIoc 4.1.1. After updating DryIoc to 4.5.1 compiling failed because DryIoc 4.1.1 cannot be found.
Can the CommonServiceLocator be used with 4.5.1?

Furthermore as far as I know Prism 8 for/with DryIoc demands version > 4.5

Thanks in advance.

**Comment by dadhi** [comment]
@polyester941 

Hi, I have checked the NuGet and the dependency saying `DryIoc.dll (>= 4.1.1)`
https://www.nuget.org/packages/DryIoc.CommonServiceLocator.dll/

So it should be fine to update to DryIoc v4.5, because it is not the major version change.

Are you really sure that the error is related to the version?

**Comment by polyester941** [comment]
Hi Maxim,
thanks for the response.
It is quite strange, as when running the application it works. But in unit test it fails with the error.
I set the locator via:
ServiceLocator.SetLocatorProvider(() => new DryIocServiceLocator(_container));

When trying to resolve via ServiceLocator.Current.GetInstance, I get the error
Could not load file or assembly 'DryIoc, Version=4.1.1.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

When using DryIoc 4.1.1. it works.

**Comment by polyester941** [comment]
Hi Maxim,

I ended up in adding to my app.config
<dependentAssembly>
	      <assemblyIdentity name="DryIoc" publicKeyToken="dfbf2bd50fcf7768" culture="neutral" />
	      <bindingRedirect oldVersion="4.1.1.0" newVersion="4.5.1.0" />
</dependentAssembly>

Then it works.

**Comment by dadhi** [comment]
Strange, the glitch in the system (it is not a new though).
