### ISSUE TITLE
The AsResolutionCall option and/or WithFuncAndLazyWithoutRegistration rule are not respected

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#347]
DryIoc.dll : 4.5.1
Framework: v4.6.2

The AsResolutionCall option and/or WithFuncAndLazyWithoutRegistration rule are not respected

```c#
       [Export(typeof(A))]
        [Reuse(ReuseType.Singleton)]
        class A
        {
            private readonly B _b;

            public A(B b) { _b = b; }
            public A Get() { return _b.Get(); }
        }

        [Export(typeof(B))]
        class B
        {
            private readonly Func<C> _c;

            public B(Func<C> c) { _c = c; }
            public A Get() { return _c().Get(); }
        }

        [Export(typeof(C))]
        [AsResolutionCall]
        class C
        {
            private readonly A _a;

            public C(A a) { _a = a; }
            public A Get() { return _a; }
        }
        
        [Test]
        public void RecursiveDependencyIssue()
        {
            var container = new Container(rules => rules
                .WithFuncAndLazyWithoutRegistration());
            container.RegisterExports(typeof(A), typeof(B), typeof(C));

            var serviceA = container.Resolve<A>();
            Assert.IsNotNull(serviceA);
            
            // throws Recursive dependency is detected when resolving
            var actual = serviceA.Get();
            Assert.AreSame(actual, serviceA);
        }
    }
```

but it works if the B class is implemented in this way
```c#
        [Export(typeof(B))]
        class B
        {
            private readonly IContainer _container;

            public B(IContainer container)
            {
                _container = container;
            }
            public A Get() { return _container.Resolve<C>().Get(); }
        }
```

as I understand the asResolutionCall option should change the way how the wrapper works internally to resolving the C from the container.

**Comment by dadhi** [comment]
@dvabuzyarov Thanks, will check. Maybe something related to the mef extension.

**Comment by dvabuzyarov** [comment]
Looks like the MEF attributes are not the root cause.

```C#
         class A
        {
            private readonly B _b;

            public A(B b) { _b = b; }
            public A Get() { return _b.Get(); }
        }

        class B
        {
            private readonly Func<C> _c;

            public B(Func<C> c) { _c = c; }
            public A Get() { return _c().Get(); }
        }

        class C
        {
            private readonly A _a;

            public C(A a) { _a = a; }
            public A Get() { return _a; }
        }
        
        [Test]
        public void RecursiveDependencyIssue()
        {
            var container = new Container();
            container.Register<A>(Reuse.Singleton);
            container.Register<B>();
            container.Register<C>(setup: Setup.With(asResolutionRoot: true));

            var serviceA = container.Resolve<A>();
            Assert.IsNotNull(serviceA);
                
            var actual = serviceA.Get();
            
            Assert.AreSame(actual, serviceA);
        }
```

this version produces the same issue.

**Comment by dadhi** [comment]
@dvabuzyarov Ok, this is the kind of problem that was hidden until now (for some reason) no-one hit it including me.

- First, `asResolutionCall` should allow the recursive dependency, and the docs are stating the same... as well as `WithFuncAndLazyWithoutRegistration` - so this is definitely a bug.
- Second, DryIoc may also use the split via `asResolutionCall` internally, for instance for the big graphs, or to enable dynamic dependency resolve based on condition.  In this case, it should preserve the check for the RecursiveDependency, and this leads to an issue.
- Third, There is another option which does not require the `asResolutionCall` nor the rule to allow the recursive dependency - using `Lazy<T>` instead of `Func<T>`. It works for your case because it relies on a different internal flag `StopRecursiveDependencyCheck`. What a mess ;) 

So I probably need to set `StopRecursiveDependencyCheck`  explicitly for the `asResolutionCall` and avoid for the internal split.

We'll see. Anyway thanks for highlighting it.

**Comment by dvabuzyarov** [comment]
Thanks for your work.  Just to let you know why I need to use "Func", I am migrating a pretty big project form Autofac to DryIoc. And "Func" is the native way for Autofac, so I have a lot of them. It will take a significant effort to replace all using of Func to Lazy.

Hope the fix will help. Until this the migration doesn't work and I have to cancel it. Thanks one more time.

**Comment by dadhi** [comment]
@dadhi I have fixed the issue, all your tests should work, Func including. I will release the new version in minutes.

**Comment by dvabuzyarov** [comment]
By the way I tried this config with Lazy and also doesn't work. I removed asResolutionCall and add WithFuncAndLazyWithoutRegistration rule to the container and got the same issue.

```c#
class A
        {
            private readonly B _b;

            public A(B b) { _b = b; }
            public A Get() { return _b.Get(); }
        }

        class B
        {
            private readonly Lazy<C> _c;

            public B(Lazy<C> c) { _c = c; }
            public A Get() { return _c.Value.Get(); }
        }

        class C
        {
            private readonly A _a;

            public C(A a) { _a = a; }
            public A Get() { return _a; }
        }
        
        [Test]
        public void RecursiveDependencyIssue()
        {
            var container = new Container(rules => rules
                .WithFuncAndLazyWithoutRegistration());
            container.Register<A>(Reuse.Singleton);
            container.Register<B>();
            container.Register<C>();

            var serviceA = container.Resolve<A>();
            Assert.IsNotNull(serviceA);
                
            var actual = serviceA.Get();
            
            Assert.AreSame(actual, serviceA);
        }
```

**Comment by dadhi** [comment]
In the current version `WithFuncAndLazyWithoutRegistration` will cause the issue. But you don't need it for Lazy to work.

In the new version all the things together would work.

Look into the test with Lazy I've added here https://github.com/dadhi/DryIoc/blob/6cfe229e8adf5406587706fa3d1699376d5135a3/test/DryIoc.IssuesTests/GHIssue347_The_AsResolutionCall_option_and_or_WithFuncAndLazyWithoutRegistration_rule_are_not_respected.cs#L40

**Comment by dvabuzyarov** [comment]
Perfect!

**Comment by dadhi** [comment]
V4.5.2 is out on nuget. May appear with some delay after indexing.
