### ISSUE TITLE
Create a child container without WithNoMoreRegistrationAllowed flag

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#348]
DryIoc: 4.5.2.

Hi

Just want to rise a question if it make sense to copy _isChangePermitted field of Registry class in scenario when a child container is made of a parent container with NoMoreRegistrationAllowed.

```c#
        [TestMethod]
        public void should_allow_registration_in_child_container()
        {
            var parent = new Container().WithNoMoreRegistrationAllowed();
            var child = parent.WithRegistrationsCopy();

            // Rises "Container does not allow further registrations."
            child.Register<Service>();
        }
```

I bet the main reason to have a copy container is to alter the existing registrations. And this ability is blocked in the about example.
I would propose to reset WithNoMoreRegistrationAllowed flag for a child container. Developers always have options to lock it again.

```c#
        [TestMethod]
        public void should_allow_registration_in_child_container()
        {
            var parent = new Container().WithNoMoreRegistrationAllowed();
            var child = parent.WithRegistrationsCopy();

            child.Register<Service>();

            // Lock it again
            child = child.WithNoMoreRegistrationAllowed();
        }
```

**Comment by dadhi** [comment]
@dvabuzyarov Maybe it will be more logical to expose the option in `WithRegistrationsCopy`. Let me think about it.

**Comment by dvabuzyarov** [comment]
Both ways work. It is hard to say what would be the best way for everyone. I can just share my case. I have a big legacy project with Autofac and now I prefer to lock the container, so that I ensure there is no extra registrations across the whole code base. But at some point I need to add several registration for a scope, and at this moment I am trapped, because there is no way to unlock it.

**Comment by dadhi** [comment]
@dvabuzyarov I see. will work on it.

**Comment by dadhi** [comment]
I've added the new overload for the base `With` and for the `WithRegistrationCopy` with the `IsRegistryChangePermitted` parameter.
