### ISSUE TITLE
ReuseAttribute treats ScopeName as string instead of object type

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#349]
DryIoc: 4.5.2

ReuseAttribute treats ScopeName parameter as string instead of object type.

```c#
    class ScopeMarker
    {
        
    }
    
    [Reuse(ReuseType.Scoped, typeof(ScopeMarker))]
    class Service
    {
        
    }

....
var scope = container.OpenScope(typeof(ScopeMarker));
scope.Resolve<Service>();
....
```

**Comment by dadhi** [comment]
@dvabuzyarov Ok.

**Comment by dadhi** [comment]
Now trying to add this in a non-braking way... good luck to me ;/

**Comment by dvabuzyarov** [comment]
Thanks. May I ask when the new version of the package will be available?

**Comment by dadhi** [comment]
@dvabuzyarov  Today or Tomorrow morning.

**Comment by dadhi** [comment]
@dvabuzyarov DryIocAttributes and DryIoc.MefAttributedModel v6.1.0 is out on NuGet
