### ISSUE TITLE
Wrong scoped resolve

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#350]
DryIoc: 4.5.2

```c#
         class A
        {
            public B B { get; }

            public A(B b)
            {
                B = b;
            }
        }

        class B
        {
            public IS S { get; }

            public B(IS s)
            {
                S = s;
            }
        }

        interface IS
        {
        }

        class S1 : IS
        {
        }

        class S2 : IS
        {
        }

        [Test]
        public void TheBug()
        {
            var container = new Container(rules => rules
                .WithMicrosoftDependencyInjectionRules()
                .WithFuncAndLazyWithoutRegistration());
            container.Register<A>();
            container.Register<B>();
            container.Register<IS, S1>(Reuse.ScopedTo("FirstScope"));
            container.Register<IS, S2>(Reuse.ScopedTo("SecondScope"));


            using (var scope = container.OpenScope("FirstScope"))
            {
               // no issue
                var a = scope.Resolve<A>();
                Assert.IsInstanceOf<S1>(a.B.S);
            }

            using (var context = container.OpenScope("SecondScope"))
            {
               // throws: DryIoc.ContainerException : code: Error.NoMatchedScopeFound; 
               // message: Unable to find matching scope with name "FirstScope" starting from 
               // the current scope {Name=SecondScope}.
                var a = context.Resolve<A>();
                Assert.IsInstanceOf<S2>(a.B.S);
            }
        }
```

Produced resolution expression in context of the second scope:
```c#
new A(new B(Convert(r.Resolve(Client.Export.Services.FilesDeleteServiceTests+IS, DefaultKey(0), Throw, null, Client.Export.Services.FilesDeleteServiceTests.B as parameter "b" FactoryId=145 (StopRecursiveDependencyCheck)
  in resolution root Client.Export.Services.FilesDeleteServiceTests.A FactoryId=144
  from container with scope {Name=FirstScope}
 with Rules with {TrackingDisposableTransients, FuncAndLazyWithoutRegistration} and without {ThrowOnRegisteringDisposableTransient, VariantGenericTypesInResolvedCollection}
 with FactorySelector=SelectLastRegisteredFactory
 with Made={FactoryMethod=ConstructorWithResolvableArguments}, null))))
```

it uses a cached expression from FirstScope for the parameter.

**Comment by dadhi** [comment]
@dvabuzyarov Just in case, why do you need the `WithFuncAndLazyWithoutRegistration`?

**Comment by dadhi** [comment]
@dvabuzyarov Btw, as you are migrating from the Autofac, maybe you have somthing to add or correct in https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/FaqAutofacMigration.md
?

**Comment by dvabuzyarov** [comment]
I am using Func for 2 cases:
1. Deal with the circular dependencies and here I think I need WithFuncAndLazyWithoutRegistration
2. Instantiate unites with custom parameters.

Since I am migrating a big legacy project from Autofac Func is widely spread across the project exactly for this purposes.

**Comment by dvabuzyarov** [comment]
> @dvabuzyarov Btw, as you are migrating from the Autofac, maybe you have something to add or correct in https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/FaqAutofacMigration.md
> ?

So far I would say the main obstacle is differences between scopes concept. In Autofac it is not only a lifetime boundary, but also a registration scope. DryIoc separates the scopes of lifetimes and registrations. And unfortunately there is no clean solution on DryIoc side that can match Autofac scopes usage. According to the repository issues developers are trying to use copy containers but have disposing issues. I think a clean example would be nice to have.

**Comment by dadhi** [comment]
Yeah, it is a hard topic. There are multiple reasons to that decision... 
Maybe you can provide the specific small Autofac example or examples with the scoped registrations - so I can think about translating them.

**Comment by dvabuzyarov** [comment]
I will prepare an example.

**Comment by dadhi** [comment]
> What do you think about the bug? Now it is a show stopper for me.

Looking at it right now.. hopefully, I will get something out of it and release the new version Today, hopefully.

**Comment by dvabuzyarov** [comment]
Thanks!

**Comment by dvabuzyarov** [comment]
Not sure, but looks like I found another bug or the same but in a different configuration.

```c#
 class A
        {
            public IB B { get; }

            public A(IB b)
            {
                B = b;
            }
        }

        interface IB
        {
            IS S { get; }
        }

        class B1 : IB
        {
            public IS S { get; }

            public B1(IS s)
            {
                S = s;
            }
        }

        class B2 : IB
        {
            public IS S { get; }

            public B2()
            {
                S = null;
            }
        }

        interface IS
        {
        }

        class S1 : IS
        {
        }

        class S2 : IS
        {
        }

        [Test]
        public void TheBug()
        {
            var container = new Container(rules => rules
                .WithMicrosoftDependencyInjectionRules()
                .WithFuncAndLazyWithoutRegistration());
            container.Register<A>();
            container.Register<IS, S1>(Reuse.ScopedTo("FirstScope"));
            container.Register<IB, B2>(Reuse.ScopedTo("SecondScope"));
            container.Register<IB, B1>();


            using (var scope = container.OpenScope("FirstScope"))
            {
                // no issue
                var a = scope.Resolve<A>();
                Assert.IsInstanceOf<B1>(a.B);
                Assert.IsInstanceOf<S1>(a.B.S);
            }

            using (var context = container.OpenScope("SecondScope"))
            {
               //DryIoc.ContainerException : code: Error.NoMatchedScopeFound;
               //message: Unable to find matching scope with name "FirstScope" starting from the current scope {Name=SecondScope}.
                var a = context.Resolve<A>();
                Assert.IsInstanceOf<B2>(a.B);
                Assert.IsNull(a.B.S);
            }
        }
``` 
If we put container.Register<IB, B1>(); right after registration of A service it would work. But I can't see any reason why it does not work with the provided registration sequence.

**Comment by dadhi** [comment]
@dvabuzyarov Confirmed. This is fun, considering that the registration order should not affect the resolution in this case.

**Comment by dvabuzyarov** [comment]
As I can see the root cause is the multiply registrations. In my opinion the generic registration should be in force whenever except "SecondScope" and in context of the second scope the special registration should be taken.

**Comment by dadhi** [comment]
@dvabuzyarov The problem is again the mix of the `SelectLastRegisteredFactory` (here comes the order) in the `MicrosoftDependencyInjectionRules` and the scope matching.
So, do you need the `SelectLastRegisteredFactory` and the `MicrosoftDependencyInjectionRules` in general?

**Comment by dadhi** [comment]
> As I can see the root cause is the multiply registrations. In my opinion the generic registration should be in force everywhere except "SecondScope" and in context of the second scope the special registration should be taken.

There is a lot of rules taken place here, not only the scope matching, other include the Registration Selection (e.g. SelectLastRegisteredFactory), condition matching (and at the end condition absence or presence), metadata, `Setup.PreferInSingleServiceResolve`... so it is hard to devise a fully deterministic strategy.

Back to your case, this is indeed not a bug (in the current design):
- Both `B1` and `B2` are matching in the "SecondScope", 
so what to select depends on the `SelectLastRegisteredFactory`.
- In the case of `B1` registered last - it would be selected, but it has the dependency `S` which requires the "FirstScope". So it fails.
- In the case of `B2` registered last - it would be selected, and as it doesn't require `S`, it succeeds.

**Comment by dadhi** [comment]
@dvabuzyarov So in your place, 

- I would rather remove the `SelectLastRegisteredFactory` from the equation,
- or ensure the registration order
- or avoid both specific scope bound and not bound registrations.

Anyway it will be PITA to understand what should happen in this setup.

**Comment by dadhi** [comment]
@dvabuzyarov I even have this example in the docs https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RulesAndDefaultConventions.md#implicit-registration-selection-based-on-scope

3rd example.

**Comment by dvabuzyarov** [comment]
Maxim, thanks. I will play with it. Some notes:

-  I am using Attributes for registration and I have't found a way how to specify the registration order.

- It looks like a good example for Autofac migration, since Autofac will give priority to scope registrations over the parent. So would assume the scope is produce a boundary for registration rules, like SelectLastRegisteredFactory or request conditions (so they make competition within the scope) and only if scope rules fails then we can use rules from parent container/scope.

**Comment by dadhi** [comment]
@dvabuzyarov 

I am also thinking that maybe it is fine.
When no factory selection is in place I have the rule to prefer the registration with the minimal lifespan, excluding the Transients,  and prefer the matching named over unnamed scoped registrations.
So from the Transient, Scoped, and Singleton -> a Scoped will be selected.

> I am using Attributes for registration and I haven't found a way how to specify the registration order.

Yep, currently, there is no way, except for Decorator where it was important from the start.

**Comment by dadhi** [comment]
Ok, it seems that only logical non-breaking exit in this situation is adding another rule...
I would probably add this rule into the MS DI rules as well (with ability to opt-out).

Probably it will be  `Rules.ApplyFactorySelectionAsTheLastResort` or similar.

**Comment by dvabuzyarov** [comment]
Well, at the moment I am getting feeling that the API is already pretty complicated.

I have some ideas in mind that could be useful.
1. Can you have a next distribution channel for the package similar to list-tags for npm? If you do, then you can publish new version on the next channel for testing and if it is good then publish it on the current channel. I can see that NuGet doesn't support such feature and offers to [use optional suffix](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning)
2. What about the rule called specific-to-general? When we have several registrations can we go from the most specific to less? 
3. Yesterday I was trying to implement AutoMockin feature on DryIoc and all provided examples are useless. I will come back with this story later on. But due using it I found out that the API is not enough to implement it in useful way. 
4. The registration attributes are not extensible, I can offer another way to organise it, so custom attributes could be incorporated on a project level. I will come back later with it.

The workaround works for me, so feel free to close this thread.

**Comment by dadhi** [comment]
> The workaround works for me, so feel free to close this thread.

What exact workaround?

> What about the rule called specific-to-general? When we have several registrations can we go from the most specific to less?

Not sure I understood this.

> Yesterday I was trying to implement AutoMockin feature on DryIoc and all provided examples are useless. I will come back with this story later on. But due using it I found out that the API is not enough to implement it in useful way.

Yeah, it would be helpful to see what's missing.

**Comment by dvabuzyarov** [comment]
1. I mean I removed the SelectLastRegisteredFactory rule and now it works.
2. If we have 2 or more registration there should be precedence rules when we need only one instance. Very common practice to start with the most specific version and if it failed go further with less specific. How to determine the specificity is another question.

**Comment by dadhi** [comment]
> If we have 2 or more registration there should be precedence rules when we need only one instance. Very common practice to start with the most specific version and if it failed go further with less specific. How to determine the specificity is another question.

I have the rules in place, probably it is a good idea to document them in one place. Will do.

**Comment by dvabuzyarov** [comment]
DryIoc: 4.6.0
```c#
        class A
        {
            public IB B { get; }

            public A(IB b)
            {
                B = b;
            }
        }

        interface IB
        {
            IS S { get; }
        }

        class B1 : IB
        {
            public IS S { get; }

            public B1(IS s)
            {
                S = s;
            }
        }

        interface IS
        {
        }

        class S1 : IS
        {
        }

        class Scope1
        {
        }

        [Test]
        public void TheBug()
        {
            var container = new Container();
            container.Register<A>();
            container.Register<IB, B1>();
            container.Register<IS, S1>(Reuse.ScopedTo(typeof(Scope1)));

            using (var scope = container.OpenScope(typeof(Scope1)))
            {
                // throws DryIoc.ContainerException : code: Error.NoMatchedScopeFound;
                // message: Unable to find matching scope with name
                var a = scope.Resolve<A>();
                Assert.IsInstanceOf<B1>(a.B);
                Assert.IsInstanceOf<S1>(a.B.S);
            }
        }
```

it works when scope name is a string rather than a type.

**Comment by dadhi** [comment]
> it works when scope name is a string rather than a type.

Wut? :( ll check

**Comment by dadhi** [comment]
@dvabuzyarov 

> it works when scope name is a string rather than a type.

Add the explicit parameter name `Reuse.ScopedTo(name: typeof(Scope1))` . The problem is that it is a different overload accepting the type.
It was a bad decision to add the overload instead of given it a different name. But until now no one uncovered this.
Will think how to address this better in the next release.
