### ISSUE TITLE
Provide a way to add new temporary registrations

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#353]
Hi

I need a clean way to add new temporary registrations. At some point I need to run a unit-of-work that uses custom implementations. When the unit-of-work is completed those registrations are not needed anymore and could be disposed of. It sounds like it works for a child container, but at the moment there is [an issue with disposing of parent container](https://github.com/dadhi/DryIoc/issues/338). A solution using scopes does not work either, as does not [allow the registrations to be overriden.](https://github.com/dadhi/DryIoc/issues/350).

```c#
interface IDep
{
    
}
class D1: IDep
{
    
}

class D2: IDep
{
    
}

class UnitOfWork: IDisposable
{
    public UnitOfWork(IDep d)
    {
        
    }

    public void Dispose()
    {
    }
}

var container = new Container(rules => rules.WithoutThrowOnRegisteringDisposableTransient());
container.Register<IDep, D1>();
container.Register<UnitOfWork>();

// now I need a robust way to override IDep registration
using (var child = container.CreateFacade())
{
    child.Register<IDep, D2>();
    using (var unit = child.Resolve<UnitOfWork>())
    {
        // unit work                    
    }
}
// at this point I want only D2 to be disposed,
// not instances from parent container nor parent it self should be affected
```

**Comment by dadhi** [comment]
@dvabuzyarov Ok, 

I will check your example later.
Couple of things I see at the moment:

- Register in facade with the `IfAlreadyRegistered.Replace` (maybe it should be default for the facade rules)
- I think in v4.6 disposing in the facade should not affect parent, because scopes are cloned.

**Comment by dadhi** [comment]
> Register in facade with the IfAlreadyRegistered.Replace

You don't need this because the facade marks all registrations in it as keyed and adds the rule prefer them over the default.

**Comment by dadhi** [comment]
@dvabuzyarov 

I have added the form of Child container (with help of #358) to fix the example from the #338

The creation of Child container (the sugar coating for the With method) is looking like this:

```cs
        private static IContainer CreateChildContainer(IContainer parent, 
            IfAlreadyRegistered childRegistrationPolicy = IfAlreadyRegistered.Replace) =>
            parent.With(
                parent.Parent,
                parent.Rules.WithDefaultIfAlreadyRegistered(childRegistrationPolicy),
                parent.ScopeContext,
                RegistrySharing.CloneAndDropCache, 
                parent.SingletonScope.CloneAndDropDisposables(),
                parent.CurrentScope ?.CloneAndDropDisposables());
```

Before proceeding with it I want to hear your feedback - should I add it into the Container API or not and what is the final form.
To help the decision I will probably release the v4.7.0-preview-01 version first.

**Comment by dvabuzyarov** [comment]
Can I try v4.7.0-preview-01 out?

**Comment by dadhi** [comment]
A bit later, I will post here.

**Comment by dadhi** [comment]
Added the `CreateChild` looking like this:

```cs
/// <summary>The "child" container detached from the parent:
/// Child creation has O(1) cost - it is cheap thanks to the fast immutable collections cloning.
/// Child has all parent registrations copied, then the registrations added or removed in the child are not affecting the parent.
/// By default child will use the parent <see cref="IfAlreadyRegistered"/> policy - you may specify `IfAlreadyRegistered.Replace` to "shadow" the parent registrations
/// Child has an access to the scoped services and singletons already created by parent.
/// Child can be disposed without affecting the parent, disposing the child will dispose only the scoped services and singletons created in the child and not in the parent (can be opt-out)</summary>
public static IContainer CreateChild(this IContainer container, 
    IfAlreadyRegistered? ifAlreadyRegistered = null, Rules newRules = null, bool withDisposables = false)
{
    var rules = newRules != null && newRules != container.Rules ? newRules : container.Rules;
    return container.With(
        container.Parent,
        ifAlreadyRegistered == null ? rules : rules.WithDefaultIfAlreadyRegistered(ifAlreadyRegistered.Value),
        container.ScopeContext,
        RegistrySharing.CloneAndDropCache,
        container.SingletonScope.Clone(withDisposables),
        container.CurrentScope ?.Clone(withDisposables));
}
```

**Comment by dadhi** [comment]
@dadhi It is here https://www.nuget.org/packages/DryIoc.dll/4.7.0-preview-01

**Comment by dvabuzyarov** [comment]
Finally it works. I tired out several approaches with scopes and child containers. No one worked out.
I will do a better review of the final solution at my side. It is just a preliminary note.

**Comment by dvabuzyarov** [comment]
Hi

I did a review and here are the outcomes:
I am creating a new child container in order to add temporary registrations. Objects from thous registrations are lived in a live scope, so actually the scope mechanism should be used for the scenario. But it needs to use specific registrations, and at the moment I don't know how to achieve that. The lib provides a way to associate registration with a scope (ScopeTo method), but it does not work in my case.  I would propose to start trying implement this scenario with existing API and see what is missed.

**Comment by dadhi** [comment]
I am not fully aware of your scenario, but you may also check `Use` methods which are simplified version of adding services directly into scope.

**Comment by dadhi** [comment]
seems like resolved
