### ISSUE TITLE
Add and surface the Scope.Clone(withDisposables=false) to enable more ChildContainer scenarios

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#358]
The method will clone the scope factories and already created services,
but will drop the disposables thus ensuring that only the new disposables added in clone will be disposed.

Related #338, #353

**Comment by dadhi** [comment]
Renamed again to `Scope.Clone(withDisposables=false)`  to simplify the propagation of `withDisposables` flag.

**Comment by dvabuzyarov** [comment]
that looks promising! Thanks.
