### ISSUE TITLE
Any samples on bootstrapping WebAPI with DryIocZero?

### ISSUE THREAD

**Issue by katit** [dadhi/DryIoc#36]
I'm looking at https://github.com/dadhi/DryIoc/tree/master/src/DryIocZero.WebApi

Seems like this is what I need but is there any sample on using it? Can't see any in documentation.

Basics would be how do I setup WebAPI to use IoC and how do I add dependencies (I guess in .ttinclude file?)

**Comment by dadhi** [comment]
For the moment I have only this project as an attempt of [DryIocZero.WebApi extension](https://github.com/dadhi/DryIoc/tree/master/src/DryIocZero.WebApi).

If you need a "real" sample of registrations you may look at [MediatR sample](https://github.com/jbogard/MediatR/tree/master/samples/MediatR.Examples.DryIocZero).

If you have a specific question, please ask. I would love to have a end-to-end sample with DIZero.

**Comment by dadhi** [comment]
There is an also same of arbitrary registrations in IoC Performance benchmark: https://github.com/danielpalme/IocPerformance/blob/master/IocPerformance/Adapters/DryIocZero/Registrations.ttinclude

**Comment by katit** [comment]
Trying to work with ttinclude and can't figure out what is wrong

Section where I declare binary and namespace:
```
<#@ assembly Name="System.Core" #>
<#@ assembly Name="$(DryIocAssembly)" #>
<#@ import Namespace="DryIoc" #>
<#@ import Namespace="ImTools" #>
<#// TODO: Insert assemblies and namespaces of your services to be registered in container #>
**<#@ assembly Name="$(SolutionDir)Ditat.WebApi\bin\Ditat.WebApi.dll" #> 
<#@ import Namespace="Ditat.WebApi.Services" #>** 
```


When right-click on .tt and "Run custom tool" I get errors:

```
Error		Compiling transformation: The call is ambiguous between the following methods or properties: 'ImTools.ArrayTools.EmptyIfNull<T>(T[])' and 'ImTools.ArrayTools.EmptyIfNull<T>(T[])'	Ditat.WebApi	D:\CodeWorkspace\...\Ditat.WebApi\DryIocZero\Container.Generated.tt	44	

Error		Compiling transformation: The call is ambiguous between the following methods or properties: 'ImTools.ArrayTools.One<T>(T)' and 'ImTools.ArrayTools.One<T>(T)'	Ditat.WebApi	D:\CodeWorkspace\...\Ditat.WebApi\\DryIocZero\Registrations.ttinclude	41	

```

**Comment by dadhi** [comment]
For some reason you have imported (transiently) DryIoc twice.

**Comment by katit** [comment]
Any suggestion on where I should look to resolve? I don't have DryIoc in reference for sure. I did add .prop file to .proj file as prescribed so now it look like this:

<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\DryIocZero.4.0.0\build\DryIocZero.props" Condition="Exists('..\packages\DryIocZero.4.0.0\build\DryIocZero.props')" />
  <Import Project="..\packages\Microsoft.Net.Compilers.2.9.0\build\Microsoft.Net.Compilers.props" Condition="Exists('..\packages\Microsoft.Net.Compilers.2.9.0\build\Microsoft.Net.Compilers.props')" />
  <Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" Condition="Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <Import Project="Properties\DryIocZero.props" />
  <PropertyGroup>

**Comment by dadhi** [comment]
Could you share the whole sample project you have so far?

**Comment by katit** [comment]
[WebAPIDryIoC.zip](https://github.com/dadhi/DryIoc/files/2526127/WebAPIDryIoC.zip)

See attached. I started from scratch:
1. Plain hellow world WebAPI project with all updated nuget libs, etc.
2. Installed DryIoCZero, fixed 2 things (path in .tt file and name in .props file)
3. Added WebAPI DryIoC .cs file (but it doesn't do anything yet)
4. Added assembly and namespace to .ttinclude and now I get same error running .tt

**Comment by dadhi** [comment]
Thanks, will check.

**Comment by dadhi** [comment]
DryIocZero functionality is merged with DryIoc. So I will try to come-up with the example of compile-time registrations

**Comment by dadhi** [comment]
Not now
