### ISSUE TITLE
Something similar 2 NInjectModule ? 

### ISSUE THREAD

**Issue by sigmarsson** [dadhi/DryIoc#361]
NInject has this abstract class to derive from and make unit tests capable to configure themself in a heartbeat. 
Have you got this concept something similar to inject the registration into a container, therefore utilize the same registration in production and in testing as well ?

**Comment by dadhi** [comment]
@sigmarsson Here is some info https://github.com/dadhi/DryIoc/issues/326#issuecomment-708936145

**Comment by sigmarsson** [comment]
Splendid.

Thank you for your rapid response!
