### ISSUE TITLE
Add .NET Standard 2.1 target for v5 to enable some performance optimizations for .NET Core

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#362]

**Comment by dadhi** [comment]
- [X] DryIoc itself
- [ ] extensions and companions

**Comment by Havunen** [comment]
.NET 6 is out already :)

**Comment by dadhi** [comment]
@Havunen Yep, I was planning to release v5 earlier but did not manage until the Nov 9. Will be coming in the upcoming days.
I need to cut corners though and skip the compile-time gen for v5 - moving to the next, hopefully the minor version.

**Comment by dadhi** [comment]
@Havunen I completely forgot that you may try v5 preview version even now.

**Comment by dadhi** [comment]
DryIoc is done,  the extensions will follow separately
