### ISSUE TITLE
MediatR - Polymorphic Notification

### ISSUE THREAD

**Issue by mpaul31** [dadhi/DryIoc#37]
Hello,

I have the following two classes I use for notifications:

    public class InventoryNotificationBase : INotification
    {
    }

    public class InventoryNotificationReceived : InventoryNotificationBase, INotification
    {
    }

And here is my handler:

    public class InventoryDenormalizer : 
        INotificationHandler<InventoryNotificationBase>,
        INotificationHandler<InventoryNotificationReceived>
    {

        public Task Handle(InventoryNotificationReceived notification, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;  // This is called twice.
        }

        public Task Handle(InventoryNotificationBase notification, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;  // This is never called.
        }
    }

Here is the publishing code:

`mediator.Publish(new InventoryNotificationReceived());`

The behavior I am noticing is the `INotificationHandler<InventoryNotificationReceived>` is being called twice and the `INotificationHandler<InventoryNotificationBase>` is never called.

However, I would have expected each handler to have been called once. 

Thoughts?

Thanks for the awesome DI Container!

**Comment by dadhi** [comment]
Hi,
Could you create a complete test in DryIoc.IssueTests project?

**Comment by mpaul31** [comment]
OK but do you agree this is a bug? Sorry not trying to be rude I just need to figure out if I need to swap DI containers if it is until a fix is made.

**Comment by dadhi** [comment]
I don't understand this fully. If I see, play with complete sample / test, it will speedup things.
I doubt that the problem is in DryIoc, cause we talk about basic feature. But again, hard to be sure until I see a full example.

**Comment by dadhi** [comment]
Ohh, what version of DryIoc do you use? 

Now I have remembered that "maybe" related issue was fixed in v3.1 (now in preview). Try it out if you are using a lesser version.

**Comment by mpaul31** [comment]
> Ohh, what version of DryIoc do you use?
> 
> Now I have remembered that "maybe" related issue was fixed in v3.1 (now in preview). Try it out if you are using a lesser version.

The preview version did **not** resolve the issue.

**Comment by dadhi** [comment]
Hopefully, will have time to check.

**Comment by dadhi** [comment]
Hi @mpaul31,

I have added the [tests](https://github.com/dadhi/DryIoc/blob/master/test/DryIoc.IssuesTests/GHIssue37_MediatR_Polymorphic_Notification.cs) to demonstrate that it cannot be "simply" achievable. So it is not a DryIoc fault, nor the MediatR's. I tried the case without containers and MediatR with the same results.

First, you need to figure out how you would do it by hand, then we think how to automate it with libs.

**Comment by mpaul31** [comment]
Thank you for looking into this. I’ll try some other things in the office next week.

**Comment by dadhi** [comment]
In order to support such a notification we should construct something like this:

```cs
Func<N, Task> Handler =
    async n => await Task.WhenAll(new[] {  
        ((INHandler<N>)new NHandler()).Handle(n),
        ((INHandler<K>)new NHandler()).Handle(n)
    });

class K {}
class N : K {}
```

**Comment by mpaul31** [comment]
I was able to resolve this by moving the INotification marker interface to a base class.

thanks for your help!
