### ISSUE TITLE
IResolverContext vs IContainer

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#374]
Hi Maksim,

I'm trying to upgrade a project that uses DryIoc v2.x and a custom [NancyFx bootstrapper](https://github.com/lucascebertin/Nancy.Bootstrappers.DryIoc/blob/master/src/Nancy.Bootstrappers.DryIoc/DryIocNancyBootstrapper.cs).

Nancy bootstrapper creates a request-scoped container using [OpenScope](https://github.com/lucascebertin/Nancy.Bootstrappers.DryIoc/blob/master/src/Nancy.Bootstrappers.DryIoc/DryIocNancyBootstrapper.cs#L13):

```csharp
protected override IContainer CreateRequestContainer(NancyContext context)
{
    return ApplicationContainer.OpenScope(Reuse.WebRequestScopeName);
}
```

DryIoc used to return `IContainer` instance from `OpenScope` method, but now it returns `IResolverContext`.
Sorry for the stupid question, but is there a way to get the container out of the resolver context?
I see that `IResolverContext` has `Use` and `UseInstance` methods for registration of the scoped services.

**Comment by dadhi** [comment]
> is there a way to get the container out of the resolver context?

`resolverContext.Resolve<IContainer>()`

> I see that IResolverContext has Use and UseInstance methods

Use `Use` :)  the `UseInstance` is obsolete coming forward.

**Comment by yallie** [comment]
Oh, thanks a lot! :)
