### ISSUE TITLE
NullReferenceException on Unregister

### ISSUE THREAD

**Issue by eocron** [dadhi/DryIoc#390]
Using unregister on keyed registrations result in NRE across all Resolve methods:
Version: all versions (tested on 2.* and 4.7.*)
**Actual:**

        [TestMethod]
        public void Repro()
        {
            var implementationType1 = typeof(A);
            var implementationType2 = typeof(B);
            var interfaceType       = typeof(ITargetInterface);
            var container           = new Container();
            container.Register(interfaceType, implementationType1, serviceKey: "foo");
            container.Register(interfaceType, implementationType2, serviceKey: "bar");

            container.Unregister(interfaceType, serviceKey:"foo");

            Assert.ThrowsException<ContainerException>(()=> container.Resolve(interfaceType, "foo")); //<---throws NRE
            container.Resolve(interfaceType, "foo", IfUnresolved.ReturnDefault); //<---throws NRE
            container.ResolveMany(interfaceType, ResolveManyBehavior.AsFixedArray);//<---throws NRE
        }

**Expected:**
Resolve with key with optional -> return default
Resolve with key - > throws ContainerException
ResolveMany for interface -> returns single registered service

**PS:**
Also throws on `container.ClearCache(interfaceType);`

**Comment by dadhi** [comment]
thanks, will look.

**Comment by dadhi** [comment]
The version v4.7.5 with the fix is out

**Comment by eocron** [comment]
Thank you!
