### ISSUE TITLE
ASP.NET Core 6 sample

### ISSUE THREAD

**Issue by timrhaynes** [dadhi/DryIoc#396]
The existing ASP.NET Core sample targets version 3.1.2 of the sdk, and does not work when targeting the latest version of ASP.NET Core (5 as of this writing). Would like a sample that works under ASP.NET Core 5 or higher.

**Comment by dadhi** [comment]
@timrhaynes Ok, I will look when time permits. Meanwhile the help in conversion will be greatly apreciated.

**Comment by timrhaynes** [comment]
> @timrhaynes Ok, I will look when time permits. Meanwhile the help in conversion will be greatly apreciated.

Thank you. In the meantime, I have posted a question on how to solve a problem with my attempt, in the Discussions page.
https://github.com/dadhi/DryIoc/discussions/398
