### ISSUE TITLE
IRegistrator is missing generic version of RegisterPlaceholder

### ISSUE THREAD

**Issue by penenkel** [dadhi/DryIoc#415]
Hi, it seems that the registration role does not have the generic variant of `RegisterPlaceholder`, whereas `IContainer` has both. I expected parity between `IContainer` and `IRegistrator` with regard to registration overloads.

- `IRegistrator.RegisterPlaceholder<TServiceType>()` <-- missing
- `IRegistrator.RegisterPlaceholder(Type serviceType)`
- `IContainer.RegisterPlaceholder<TServiceType>()`  <-- exists
- `IContainer.RegisterPlaceholder(Type serviceType)`

**Comment by dadhi** [comment]
@penenkel Nice finding, will add.
