### ISSUE TITLE
Resolving interfaces with covariant type parameter fails when using RegisterMapping

### ISSUE THREAD

**Issue by t-castelan** [dadhi/DryIoc#418]
We built some extension methods around `RegisterMapping` to register multiple types with a single call. So we are using it quite frequently. Now we ran into a problem that we cannot resolve an interface type with a covariant type parameter, when registering it by `RegisterMapping`. See the following example:

```csharp
var container = new Container();
// Register the implementation as itself
container.Register(Made.Of(() => new List<SubClass>()));
// Register the interface with base type parameter
container.RegisterMapping<IReadOnlyList<BaseClass>, List<SubClass>>();

// Resolving IReadOnlyList<BaseClass> crashes here
var baseClassList = container.Resolve<IReadOnlyList<BaseClass>>();
```

The following is the message of the thrown exception:
```
DryIoc.ContainerException : code: Error.RegisteringImplementationNotAssignableToServiceType;
message: Registering implementation type List<SubClass> is not assignable to service type IReadOnlyList<BaseClass>.
```

I will provide a failing test and some working tests containing alternatives/workarounds that are sufficient for us, now. But it would be nice, if this issue got fixed.

**Comment by dadhi** [comment]
@t-castelan Thanks for reporting and especially for the test. Will look.

**Comment by dadhi** [comment]
@t-castelan  Forgot about this thingy, will look next.
