### ISSUE TITLE
Incompatibility problem?

### ISSUE THREAD

**Issue by jkvargas** [dadhi/DryIoc#42]
System.MissingMethodException: Method not found: 'DryIoc.Setup DryIoc.Setup.With(System.Object, System.Func`2<DryIoc.Request,Boolean>, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Int32)'.
  at at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.WithDependencyInjectionAdapter(IContainer container, IEnumerable`1 descriptors, Func`3 registerDescriptor, Func`2 throwIfUnresolved)

I am using:
DryIoc.Microsoft.DependencyInjection 2.2.0-preview-01
DryIoc.dll 3.1.0-preview-05

**Comment by dadhi** [comment]
Thank you, will check, maybe will release a new matching previews. Stable versions are not completed yet.

**Comment by dadhi** [comment]
I have published a new compatible preview: https://www.nuget.org/packages/DryIoc.Microsoft.DependencyInjection/2.2.0-preview-02
