### ISSUE TITLE
when im install DryIoc its let my porject ‘s IntelliSense slow much

### ISSUE THREAD

**Issue by sgf** [dadhi/DryIoc#426]
At first I thought that I had installed an unknown VS plug-in by mistake, which caused the VS response to be very slow, so I uninstalled all the plug-ins one by one, and even uninstalled all the plug-ins in the end.
Even uninstalled VS2019, and then reinstalled. But still to no avail. So I endured it until I wrote another project and found that no other project had this problem.
So the problem must lie in this project, because the project is a winform project, so I doubt it is caused by the poor performance of the WInform-Designer produced by the Microsoft department of VS2019.
But this is not the problem. Eventually I started to doubt DryIoc, because this project is very unusual and I have to install some source files.
I uninstalled the nuget package first, and then recompiled the project.
Then I typed a character, and the response speed of VS2019 was magically restored.
The project after installing DryIoc will cause: ServiceHub.RoslynCodeAnalysisService.exe High CPU.
And will cause: devenv.exe High CPU.
And it will lead to: IntelliSense Very Slow, including code suggestions and implementation interface suggestions, refactoring suggestions, etc.

**Comment by dadhi** [comment]
Install DryIoc.dll package instead of DryIoc.

**Comment by sgf** [comment]
ok,thanks
