### ISSUE TITLE
Internal constructors are not supported

### ISSUE THREAD

**Issue by Serg046** [dadhi/DryIoc#427]
The following code fails with `Unable to select single public constructor from implementation type Test2 because it does not have one`:
```csharp
public static void Main()
{
  var container = new Container();
  container.Register<Test>();
  Console.WriteLine(container.Resolve<Test>().GetType().FullName);
  container.Register<Test2>(); // Fails here
  Console.WriteLine(container.Resolve<Test2>().GetType().FullName);
}

internal class Test
{
  public Test(){}
}

internal class Test2
{
  internal Test2(){}
}
```
while it works for `Test`. You can run it here https://dotnetfiddle.net/3pvqeb.

**Comment by dadhi** [comment]
Thus is by design, if you need the non-public constructors you need to be explicit.
Change the `Test2` registration to:

```cs
container.Register<Test2>(made: Made.Of(FactoryMethod.Constructor(includeNonPublic: true)));
```

**Comment by Serg046** [comment]
Indeed https://dotnetfiddle.net/pECAQK, thank you and sorry to have bothered you

**Comment by dadhi** [comment]
no problem 👍
