### ISSUE TITLE
Circular dependency with Func/Lazy on Scoped Transient

### ISSUE THREAD

**Issue by hutterm** [dadhi/DryIoc#439]
I was testing around a bit of DryIoc's capabilities and I'm quite impressed!
Please advise if I'm doing something wrong here or my expectations are false:

```c#
        [Fact]
        public void IsScopedRegistrationCorrect()
        {
            var c = new Container();

            c.Register<DCS>(setup: Setup.With(openResolutionScope: true));
            c.Register<IncVM>();

            var si=c.Resolve<DCS>();
            var incVM = si.IncFunc();
            incVM.Dcs.Value.Should().Be(si); //fails
        }

        class DCS
        {
            public Func<IncVM> IncFunc { get; }

            public DCS(Func<IncVM> incFunc)
            {
                IncFunc = incFunc;
            }
        }

        class IncVM
        {
            public Lazy<DCS> Dcs { get; }

            public IncVM(Lazy<DCS> dcs)
            {
                Dcs = dcs;
            }
        }

```
I tried also without the Lazy in IncVM, but then the container complains about circular dependency.
After reading the whole manual I'm still not quite sure WHY Func doesn't resolve circular dependencies (or rather only with `WithFuncAndLazyWithoutRegistration()` )

But anyways, in this test I was expecting the `Func` to resolve the lazy `DCS` of the same scope. Is that not the case?

**Comment by dadhi** [comment]
@hutterm Hi, thanks for praising :)

The use of `openResolutionScope` guarantee that the new scope will be opened when resolving or injecting the DCS, then from this scope the DCS will be resolved.

So your situation is treaky if you want the same DCS instance. The question is why do you need it to be the same.. may be you can add another type  for the business model and keep the DCS as surrogate (point in object graph) with only goal of opening the scope.

```
        class UsefulX {}

        class DCS
        {
            public Func<IncVM> IncFunc { get; }
            public UsefulX X { get; }

            public DCS(Func<IncVM> incFunc, UsefulX x)
            {
                IncFunc = incFunc;
                X = x;
            }
        }

        c.Register<UsefulX>(Reuse.ScopedTo("blah"));
        var s = c.OpenScope("blah");
        s.Resolve<DCS>();
        // verify that X property is the same whatever nesting is, 
        // as long as the root is resolved from the blah scope

```

**Comment by dadhi** [comment]
Closing or be free to convert to reopen with the new comments and convert to discussion.
