### ISSUE TITLE
DryIoc.WebApi conflicts and newer version of dependent packages

### ISSUE THREAD

**Issue by AndreyTomilinXmpi** [dadhi/DryIoc#444]
Hi,
Recently I wanted to update packages of several libraries I use.
I see that the DryIoc is used by many developers and it's very strange to get such errors. Or maybe I miss something simple.

1. The DryIoc.WebApi.dll package and System.Web.Http dependency
   It depends on the System.Web.Http 5.2.6.0.
   When creating a new Web Api application in 4.7.2 framework (which use the System.Web.Http 5.2.7.0) I get this error:

> Could not load file or assembly 'System.Web.Http, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> === Pre-bind state information ===
> LOG: DisplayName = System.Web.Http, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
>  (Fully-specified)
> LOG: Appbase = file:///...
> LOG: Initial PrivatePath = ...
> Calling assembly : DryIoc.WebApi, Version=4.0.0.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768.

2. The DryIoc.WebApi.dll package and DryIoc.dll dependency
   It depends on the DryIoc.dll 4.0.0.0.
   When using the DryIoc.dll 4.8.1.0 I get this error:

> Could not load file or assembly 'DryIoc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> === Pre-bind state information ===
> LOG: DisplayName = DryIoc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768
>  (Fully-specified)
> LOG: Appbase = file:///...
> LOG: Initial PrivatePath = ...
> Calling assembly : DryIoc.WebApi, Version=4.0.0.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768.

Thanks,
Andrey

**Comment by dadhi** [comment]
Hi. So the solution is the updating of DryIoc.WebApi deps? 
I am open for the PR then.

**Comment by AndreyTomilinXmpi** [comment]
Looks so. Also, if possible (and I think it is) to make dependencies from some specific minimal version and all newer versions.
Or create several versions of DryIoc.WebApi works with different versions of depended packages. 
Not sure which way is better

Anyway thanks for the fast reply

**Comment by dadhi** [comment]
@AndreyTomilinXmpi The new v4.1 of DryIoc.WebApi and friends is out.
