### ISSUE TITLE
Resolving a record without registration causes a StackOverflowException

### ISSUE THREAD

**Issue by joelweiss** [dadhi/DryIoc#446]
The following code will throw a StackOverflowException, am I missing something?
[.Net Fiddle](https://dotnetfiddle.net/RZNCKb)
```csharp
void Main()
{
    var container = new Container(Rules.Default.WithAutoConcreteTypeResolution());
    //container.Register<Foo>();
    container.Resolve<Foo>();
}

public record Foo { };
```

**Comment by dadhi** [comment]
@joelweiss 

The problem that record generates the protected "copy" constructor in addition to the default constructor,
and DryIoc prefers the former because it has more parameters. Instead, DryIoc should prefer public over the non-public constructors first.

**Comment by dadhi** [comment]
@joelweiss 

Moreover, I think that using the `protected` constructor for the injection is wrong because it normally supposed to be called by the other constructor of the inherited class. So I may just exclude the protected constructors from the most resolvable constructor lookup.

**Comment by dadhi** [comment]
@joelweiss 

OK. The change with excluding the `protected` will be breaking and need to be more thoughtful.
But for the specific case with AutoConcrete type resolution will be enough to filter out recursive constructors with the same type as parameter.

**Comment by joelweiss** [comment]
@dadhi Thanks.

What is the difference when registering explicitly, why didn't it throw then?

**Comment by dadhi** [comment]
@joelweiss Explicit registration looks up for the single public constructor, otherwise throws by default.
