### ISSUE TITLE
Optional dependency shouldn't treat its own dependencies as optional

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#449]
Hi Maksim!

Consider a class with an optional dependency:

```csharp
public class Computer
{
  [Import(AllowDefault = true)]
  private IHardDrive HardDrive { get; set; } // a computer can work without a hard drive
}
```

If `IHardDrive` is registered in the container, it's imported, otherwise the import is ignored. So far so good.

Now, consider an implementation of `IHardDrive` that itself has a required dependency:

```csharp
public class SamsungHardDrive : IHardDrive
{
  [Import]
  private ILogicBoard LogicBoard { get; set; } // a hard drive cannot work without a logic board
}
```

If `ILogicBoard` is registered in the container, both `IHardDrive` and `ILogicBoard` should be imported.
If `ILogicBoard` is not registered, `IHardDrive` shouldn't be imported.

But it turns out that in the latter case `IHardDrive` is imported and its `ILogicBoard` is not set.
The container produces a computer with a broken hard drive that's missing a logic board.
Accessing the hard drive throws a null reference exception.

Perhaps I'm missing some container settings? 
Let me create a unit test demonstrating this issue.

**Comment by dadhi** [comment]
@yallie Hi here, it supposed to work, so I will look. Thanks as usual for posting with the PR.

**Comment by yallie** [comment]
Thanks a lot Maksim! That's awesome! 🚀

**Comment by yallie** [comment]
Looks like it's still broken 🤔
If optional dependency it lazy, it's still resolved even if it's missing its own dependencies...

**Comment by dadhi** [comment]
@yallie Before doing anything on the last case of Lazy dependency with a send dependency. 
I am questioning if I need to check this in principle because it should stay lazy, right?
If I try to follow the dependencies I need to potentially materialize the Types, load things, prevent caching and singleton creation...
So I can try to do some if this, by setting the special flag in Request and checking it on each nested level, but it is a comlex rask and probably there will be holes.

What do you think?

**Comment by yallie** [comment]
>I am questioning if I need to check this in principle, because it should stay lazy, right?
>If I try to follow the dependencies I need to potentially materialize the Types, load things, prevent caching and singleton creation...

That's an interesting question...
It used to work in DryIoc v2, but I didn't know if it instantiated singletons, etc.
Perhaps it should throw when accessing Lazy.Value property?

**Comment by yallie** [comment]
Everything works great! 👍
Thanks a lot Maksim!

**Comment by dadhi** [comment]
@yallie I have released DI v4.8.7 and DI.MEF v6.2.0 which point the latest DI.

**Comment by yallie** [comment]
Thanks a lot!

**Comment by dadhi** [comment]
Thanks to you @yallie for the interesting issues and the PRs.
