### ISSUE TITLE
Compiler-generated type as a service

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#451]
Hi Maksim,

I've updated my app to the last version of DryIoc and found that it's not starting up.
The application couldn't resolve its settings class generated from App.settings file.

I found the exact commit where the breaking change was introduced: 2aaedc43b551eebba95d007f508aea10104dce6d
Then I tried to extract the failing setup into a minimal reproducible unit test and it turned out to be tricky.

I was thinking it was the unusual setup (exported static property) that was problematic.
But finally I discovered that the issue was the `CompilerGeneratedAttribute`.
I'll create the pull request demonstrating the issue.

Can we disable the rule that ignores the compiler-generated classes as a services?
Does it really help speeding up service resolution?

**Comment by yallie** [comment]
Thank you! 🙏

**Comment by yallie** [comment]
Looks like SettingsSingleFileGenerator tool incorrectly uses `CompilerGeneratedAttribute` instead of 
the `GeneratedCodeAttribute` which should be used. The same issue with StronglyTypedResourceBuilder.

Related MSDN blog post: [Correct usage of the CompilerGeneratedAttribute and the GeneratedCodeAttribute](https://web.archive.org/web/20150828105809/http://blogs.msdn.com/b/codeanalysis/archive/2007/04/27/correct-usage-of-the-compilergeneratedattribute-and-the-generatedcodeattribute.aspx).
Even Microsoft's own tools don't use the right attributes.

Unfortunately, there seems to be no way to instruct the tools to avoid emitting the attribute...

**Comment by dadhi** [comment]
Thanks for the link. It is always good to have a broader look at the problem.

**Comment by yallie** [comment]
I'm disappointed that CompilerGenerated attribute doesn't actually mean that the code is compiler-generated.
Sometimes C# compiler doesn't apply it to the generated code, and sometimes the attribute is misused by code generation tools.

**Comment by yallie** [comment]
Hmm, interesting...
Is there any benefit from static compile-time service registrations, apart from the faster start-up?
As far as I've seen, DryIoc service discovery and registration is blazing fast, compared to other containers.
For typical applications service registration would take less than a second, and other startup tasks 
like looking up something in the database would require much more time anyway. Am I missing something?

**Comment by yallie** [comment]
Oh, I see, thanks for the insight. 
Compile-time errors vs runtime errors look like the most important point to me :)
I've seen too much cryptic runtime errors in MEF times...

**Comment by dadhi** [comment]
@yallie What is the name of the class generated from App.settings? 
Does it start with '<>'?

**Comment by yallie** [comment]
No, class name is derived from the settings file name: `MyAppConfig.settings` → `MyAppConfig.Designer.cs`.
Similar to resx resource file generator's behavior.
