### ISSUE TITLE
One more regression

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#456]
Hello Maksim,

Looks like I've found one more regression, sorry...
Breaking change was introduced in the recent commit 5946550811b5c882cba7e92b6536eb3e75f97e2b, ~5 commits ago.
It seems to be related to some combination of singletons and lazy wrappers.
But I haven't prepared an isolated unit test yet.
I'll update the title when I find what exactly was broken.

**Comment by dadhi** [comment]
@yallie I am still working on it in the scope of #435 

It is a real PITA. This one is preventing me to conclude the release of the next bug-fix version. 
Up to now I have tried 3 or 4 approaches - and have another one in mind.
Will be doing Today or on the weekend.

**Comment by yallie** [comment]
I couldn't reproduce the issue as an isolated unit test, but now I see that it's fixed in the latest commit.
I guess I can close this issue.
