### ISSUE TITLE
Operation is not supported on this platform exception on Xamarin iOS

### ISSUE THREAD

**Issue by yunusefendi52** [dadhi/DryIoc#46]
I am trying to update to the latest preview version (3.1.0-preview-06) but there is an exception when trying to `Resolve`, the exception is "Operation is not supported on this platform exception" with System.Reflection.Emit on iOS, `Resolve` works tho on version 3.0.2

Thanks..

**Comment by dadhi** [comment]
Ok, thanks for reporting. Will check.

**Comment by dadhi** [comment]
@5yunus2efendi Hello again,

I have released a new `DryIoc.dll.3.1.0-preview-07` package with the option to turn off FEC support #39 (which is most likely causing your problem).

To use it, create the Container like this:
```cs
var container = new Container(rules => rules.WithoutFastExpressionCompiler());
```

Please check did it help.

**Comment by 5yunus2efendi** [comment]
Sorry for the delay, it's working now.

**Comment by uksreejith** [comment]
For me, WithoutFastExpressionCompiler fixed PlatformNotSupportedException on UWP too.
