### ISSUE TITLE
Transient IDisposable factory method with custom constructor args

### ISSUE THREAD

**Issue by InKahootz** [dadhi/DryIoc#461]
I've run into an issue where I have a 'hidden' factory that implements `IDisposable` that returns an object (Jetbrains.Lifetime) so the requesting object doesn't have to implement `IDisposable`. They only have to request a `Lifetime` and add cleanup actions to that. 

When the scope is disposed, the hidden `IDisposable` factory will be disposed which will terminate the Lifetime.  

The Lifetime's Id should come from the original requesting object's type name. However, the issue is that the very first resolve of `Lifetime` sets the id for the factory and that same Id is used for all the other creations of the factory. 

https://dotnetfiddle.net/BQCdR4

```csharp
#nullable enable
using System;

using DryIoc;

using JetBrains.Lifetimes;

public class Program
{
    public static void Main()
    {
        var c = new Container();
        
        // Resolver should receive type name of original requester
        c.Register<LifetimeResolver>(
            made: Parameters.Of.Type<string>(r => r.Parent.Parent.ImplementationType.Name),
            setup: Setup.With(trackDisposableTransient: true));
        c.Register<Lifetime>(Reuse.Scoped,
            made: Made.Of(r => ServiceInfo.Of<LifetimeResolver>(), f => f.GetValue()));
        c.Register<A>();
        c.Register<B>();
        c.Register<C>();

        using var aScope = c.OpenScope();
        var a = aScope.Resolve<A>();

        using var bScope = c.OpenScope();
        var b = bScope.Resolve<B>();

        Console.WriteLine($"A Lifetime Id should be A: {a.Lifetime.Id}");
        Console.WriteLine($"B Lifetime Id should be B: {b.Lifetime.Id}");
        Console.WriteLine($"B's C Lifetime Id should be B: {b.C.Lifetime.Id}");

        Console.WriteLine($"A and B Lifetimes are different: {!a.Lifetime.Equals(b.Lifetime)}");
        Console.WriteLine($"B and C Lifetimes are same: {b.Lifetime.Equals(b.C.Lifetime)}");

        aScope.Dispose();
        bScope.Dispose();

        c.Dispose();

        c.Dispose();
    }

    public class LifetimeResolver : IDisposable
    {
        private string? _id;
        private LifetimeDefinition? _def;

        public LifetimeResolver(string? id)
        {
            _id = id;
        }

        public Lifetime GetValue()
        {
            if (_def is null)
            {
                _def = Lifetime.Define(Lifetime.Eternal, _id, (Action<LifetimeDefinition>?)default);
            }

            return _def.Lifetime;
        }

        public void Dispose() => _def?.Terminate();
    }

    public abstract class L
    {
        public Lifetime Lifetime { get; }
        protected L(Lifetime l) => Lifetime = l;
    }
    public class A : L
    {
        public A(Lifetime aLifetime) : base(aLifetime) { }
    }

    public class B : L
    {
        public C C { get; }
        public B(Lifetime bLifetime, C c) : base(bLifetime) => C = c;
    }

    public class C
    {
        public Lifetime Lifetime { get; }
        public C(Lifetime l) => Lifetime = l;
    }
}
```

The output: 
```
A Lifetime Id should be A: A
B Lifetime Id should be B: A
B's C Lifetime Id should be B: A
A and B Lifetimes are different: True
B and C Lifetimes are same: True
```

There's no issue with the instancing of the Lifetimes, but the Ids being injected are not what I expected.
Is there a proper way for the `LifetimeResolver` to receive the correct type name every time?

DryIoc v4.8.7
JetBrains.Lifetimes: 2022.1.4

**Comment by dadhi** [comment]
@InKahootz Thanks for the sample. I did not worked with JB.Lifetimes so I will need some time to make sense of it.

**Comment by InKahootz** [comment]
If you need a sample without Lifetimes, I could do that. It was just the catalyst that help me find it.The only problem is that my factory instance that is IDisposable receives the wrong string during requests.   From: Maksim VolkauSent: Friday, March 4, 2022 5:18 PMTo: dadhi/DryIocCc: Hank McCord; MentionSubject: Re: [dadhi/DryIoc] Transient IDisposable factory method with custom constructor args (Issue ***@***.*** Thanks for the sample. I did not worked with JB.Lifetimes so I will need some time to make sense of it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by dadhi** [comment]
@InKahootz The problem is in caching. If you want something dynamic - like inject the different Lifetime based on its object graph, you need to set `setup: Setup.With(asResolutionCall: true)`.  Check my test https://github.com/dadhi/DryIoc/commit/4d46671cb6d9552d445acdbb5e7924ba0796a5fd and the [docs](https://github.com/dadhi/DryIoc/blob/43638a71315d6be326df7e211649d436594aff48/docs/DryIoc.Docs/UnregisterAndResolutionCache.md#make-injected-dependency-re-wireable-by-registering-it-asresolutioncall)
Maybe I need to rename it to DynamicSomething already...

<iframe src="https://github.com/sponsors/dadhi/button" title="Sponsor dadhi" height="35" width="116" style="border: 0;"></iframe>

**Comment by InKahootz** [comment]
I appreciate you looking into it!
