### ISSUE TITLE
RegisterMany Question

### ISSUE THREAD

**Issue by mpaul31** [dadhi/DryIoc#49]
Hello,

I am trying to use the RegisterMany function restricting to the following two interfaces (MediatR):

```
INotificationHandler<>
IRequestHandler<,>
```
```
container.RegisterMany(new[]
{
    typeof(VehicleDenormalizer).GetAssembly(),
}, Registrator.Interfaces);
```

How could I use the `RegisterMany` to only register the two interfaces?

Thanks!

**Comment by dadhi** [comment]
I think the questions are better to be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/dryiochttps://stackoverflow.com/questions/tagged/dryioc).

But nevertheless you may try:
```cs
container.RegisterMany(new[]
{
    typeof(VehicleDenormalizer).GetAssembly(),
}, type => {
   if (!type.IsInterface() || !type.IsGeneric())
       return false;
   var openGenericInterfaceType = type.GetGenericTypeDefinition();
   if (openGenericInterfaceType == typeof(INotificationHandler<>) ||
       openGenericInterfaceType == typeof(IRequestHandler<,>))
       return true;
    return false;
});
```

**Comment by mpaul31** [comment]
ok thank you I will ask all further questions on stack!
