### ISSUE TITLE
Questions about property / field can not be injected

### ISSUE THREAD

**Issue by GameBelial** [dadhi/DryIoc#50]
I have two definitions of tool classes:
```csharp
    public interface ITool
    {
        void Print();
    }

    public class Tool : ITool
    {
        public void Print()
        {
            Console.WriteLine("I'm Tool.");
        }
    }

    public class DefaultTool : ITool
    {
        public void Print()
        {
            Console.WriteLine("Null.");
        }
    }
```

Interceptor definition:
```csharp
    public class TestInterceptor : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            Console.WriteLine("At Interceptor ...");
        }
    }
```

I injected the tool class as an attribute, but the parsed behavior is completely different:
```csharp
    public interface IApplicationImpl
    {
        void UseTool();
    }
    
    public class ApplicationImpl :IApplicationImpl
    {
        public ITool Tool { get; set; }

        public ApplicationImpl()
        {
            Tool = new DefaultTool();
        }
        
        public void UseTool()
        {
            Tool.Print();
        }
    }
```
I did this test:
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var c = new Container(r=>r.WithTrackingDisposableTransients());
            c.Register<ITool,Tool>();
            c.Register<TestInterceptor>();
            c.RegisterMany(new[]{typeof(IApplicationImpl),typeof(ApplicationImpl)},typeof(ApplicationImpl),Reuse.Transient,PropertiesAndFields.Auto);
            c.Intercept<ApplicationImpl,TestInterceptor>();
            
            // no.1
            c.Resolve<IApplicationImpl>().UseTool();
            // no.2
            c.Resolve<ApplicationImpl>().UseTool();
            
            Console.ReadKey();
        }
    }
```

**Comment by GameBelial** [comment]
The output I get is this:
```
I'm Tool.
Null.
```
The output I want to get is like this:
```
I'm Tool.
I'm Tool.
```
This means that property injection does not work properly in the type being delegated.

**Comment by GameBelial** [comment]
Sorry, my English is very poor.

**Comment by dadhi** [comment]
Strange.

Couple of questions:

- Does it work if you put `ITool` into constructor of `ApplicationImpl`?
- Why are you intercepting implementation and not the interface here `c.Intercept<ApplicationImpl,TestInterceptor>();` ?

**Comment by GameBelial** [comment]
@dadhi If the ITool object is injected in the constructor, it will work.

Because I will use it in the Controller, and in IServiceProvider I can only parse the specific implementation type.

**Comment by GameBelial** [comment]
@dadhi ok, thanks.

**Comment by GameBelial** [comment]
@dadhi 
![tim 20181115103339](https://user-images.githubusercontent.com/3907132/48526250-edc14a80-e8c1-11e8-8e26-a4dd555ae248.png)

I found that if the interface is bound to the interceptor, the properties can be parsed normally.

![tim 20181115103729](https://user-images.githubusercontent.com/3907132/48526402-8061e980-e8c2-11e8-98bc-4b1e49eb8e76.png)

The implementation type is bound to the interceptor and the property cannot be resolved.

**Comment by GameBelial** [comment]
@dadhi 
I tried again, and if the property is injected with the PropertiesAndFields.Auto parameter, the property injection works fine.
But the interceptor still can't work.

**Comment by dadhi** [comment]
Ehhh, Ok. Thanks for solving it on your own. 

I am by no means an interception expert and not a `Castle.Core` expert either. But I want to improve and simplify the question answering in future, so I will add your case as a regression test into the `IssuesTests` project.

**Comment by dadhi** [comment]
Hi @GameBelial 

There were additional problems with the interception example. I have fixed it both in the old wiki and a new DryIoc.Docs project.

Please look at my [commit](https://github.com/dadhi/DryIoc/commit/7f0fc5be97626c1f02b3159622a8fd5fb18f94ad).

You need to replace `CreateClassProxyType` with `CreateClassProxyTypeWithTarget`. Otherwise Castle Dynamic proxy does not pass the real class / implementation into the generated proxy constructor.

You also should not forget to call `invocation.Proceed()` in the interceptor, to invoke the real implementation.

**Comment by GameBelial** [comment]
@dadhi 
Thank you for your reminder, but I also found another problem. If multiple interceptors are added for an interface, the real type information cannot be obtained directly inside the interceptor.
However, this situation I did not find in Castle Windsor.

Because I am trying to replace the Castle Windsor of [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate) with DryIoc.

Demo Code:
```csharp
    public class TestInterceptor : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            invocation.Proceed();
            Console.WriteLine("At Interceptor 1...");
        }
    }

    public class TestInterceptor2 : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            invocation.Proceed();
            Console.WriteLine("At Interceptor 2...");
        }
    }
    
    public class TestInterceptor3 : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            var unproxiedType = invocation.TargetType;
            
            invocation.Proceed();
            Console.WriteLine("At Interceptor 3...");
        }
    }

    public interface IApplicationImpl
    {
        void UseTool();
    }
    
    public class ApplicationImpl :IApplicationImpl
    {
        public void UseTool()
        {
            Console.WriteLine("I'm ApplicationImpl.");
        }
    }
```

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var c = new Container(r=>r.WithTrackingDisposableTransients());
            c.Register<TestInterceptor>();
            c.Register<TestInterceptor2>();
            c.Register<TestInterceptor3>();
            
            c.RegisterMany(new[]{typeof(IApplicationImpl),typeof(ApplicationImpl)},typeof(ApplicationImpl),Reuse.Transient,PropertiesAndFields.Auto);
            
            c.Intercept<IApplicationImpl,TestInterceptor>();
            c.Intercept<IApplicationImpl,TestInterceptor2>();
            c.Intercept<IApplicationImpl,TestInterceptor3>();
            
            c.Resolve<IApplicationImpl>().UseTool();

            Console.ReadKey();
        }
    }
```

![tim 20181116103956](https://user-images.githubusercontent.com/3907132/48594550-f8481680-e98b-11e8-87b9-e5b6622348d5.png)

In this case I have to recursively get the type of real agent.
If the HTTP API interface is called frequently if the controller is being proxied, the performance of the interface will be poor.

**Comment by dadhi** [comment]
That's because each intercept creates its own proxy on top of previous one, creating a decorator chain.

I think, for multiple interceptors we need to add Api to pass array of interceptors into `CreateClassProxyTypeWithTarget`. 

Probably it will already work if you register all interceptors to one interceptor interface, and then pass this interface to `Intercept` method.

**Comment by GameBelial** [comment]
Thank you. I added a new interface, Custom Interceptor, which inherits from IInterceptor. All of my interceptors implement the ICustomInterceptor interface. When I injected the interceptor, I passed the ICustomInterceptor interface and its implementation type. Now he is working normally.

new code:
```csharp
    public interface IApplicationImpl
    {
        void UseTool();
    }
    
    public class ApplicationImpl :IApplicationImpl
    {
        public void UseTool()
        {
            Console.WriteLine("I'm ApplicationImpl.");
        }
    }

    public class TestInterceptor : ICustomInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            invocation.Proceed();
            Console.WriteLine("At Interceptor 1...");
        }
    }

    public class TestInterceptor2 : ICustomInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            invocation.Proceed();
            Console.WriteLine("At Interceptor 2...");
        }
    }
    
    public class TestInterceptor3 : ICustomInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            var unproxiedType = invocation.TargetType;
            
            invocation.Proceed();
            Console.WriteLine("At Interceptor 3...");
        }
    }

    public interface ICustomInterceptor : IInterceptor
    {
        
    }
```

use it:
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var c = new Container(r=>r.WithTrackingDisposableTransients());
            c.Register<ICustomInterceptor,TestInterceptor>();
            c.Register<ICustomInterceptor,TestInterceptor2>();
            c.Register<ICustomInterceptor,TestInterceptor3>();
            
            c.RegisterMany(new[]{typeof(IApplicationImpl),typeof(ApplicationImpl)},typeof(ApplicationImpl),Reuse.Transient,PropertiesAndFields.Auto);
            
            c.Intercept<IApplicationImpl,ICustomInterceptor>();
            
            c.Resolve<IApplicationImpl>().UseTool();

            Console.ReadKey();
        }
    }
```
working:
![tim 20181116144311](https://user-images.githubusercontent.com/3907132/48602411-01e27600-e9ae-11e8-910f-a537ebbf3299.png)

**Comment by dadhi** [comment]
I will probably generalize the API, allowing to pass the `Parameter.Of` selector for interceptors in most common form. Then the current API will be just a sugar on top.

And probably it is time to release it as separate package. More packages... yahhh! :)

**Comment by GameBelial** [comment]
nice,This is a good decision, dynamic proxy is a commonly used feature. 😀😀😀

**Comment by GameBelial** [comment]
@dadhi 
Maybe I need to inject the type I specified, but I can't do this with Parameters.Of.Type. It will prompt for the following exception:
![tim 20181116194426](https://user-images.githubusercontent.com/3907132/48619668-2e12ec80-e9d8-11e8-8c3c-8dcc1b6f966e.png)

my code:
```csharp
        public static void Intercept(this IRegistrator registrator,Type serviceType,Type interceptorType, object serviceKey = null)
        {
            Type proxyType;
            if (serviceType.IsInterface())
                proxyType = ProxyBuilder.CreateInterfaceProxyTypeWithTargetInterface(
                    serviceType, ArrayTools.Empty<Type>(), ProxyGenerationOptions.Default);
            else if (serviceType.IsClass())
                proxyType = ProxyBuilder.CreateClassProxyTypeWithTarget(
                    serviceType, ArrayTools.Empty<Type>(), ProxyGenerationOptions.Default);
            else
                throw new ArgumentException(
                    $"Intercepted service type {serviceType} is not a supported, cause it is nor a class nor an interface");

            var decoratorSetup = serviceKey == null
                ? Setup.DecoratorWith(useDecorateeReuse: true)
                : Setup.DecoratorWith(r => serviceKey.Equals(r.ServiceKey), useDecorateeReuse: true);

            registrator.Register(serviceType, proxyType,
                made: Made.Of((Type type) => type.GetConstructors().SingleOrDefault(c => c.GetParameters().Length != 0),
                    Parameters.Of.Type<IInterceptor[]>(request =>
                    {
                        // Test Code
                        var array = new List<IInterceptor>();
                        array.Add(request.Container.Resolve<TestInterceptor2>());
                        array.Add(request.Container.Resolve<TestInterceptor3>());
                        return array.ToArray();
                    }),
                    PropertiesAndFields.Auto),
                setup: decoratorSetup);
        }
```

use it:
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var c = new Container(r=>r.WithTrackingDisposableTransients());
            c.Register<TestInterceptor>();
            c.Register<TestInterceptor2>();
            c.Register<TestInterceptor3>();
            
            c.RegisterMany(new[]{typeof(IApplicationImpl),typeof(ApplicationImpl)},typeof(ApplicationImpl),Reuse.Transient,PropertiesAndFields.Auto);
            
            c.Intercept<IApplicationImpl,TestInterceptor>();

            
            c.Resolve<IApplicationImpl>().UseTool();

            Console.ReadKey();
        }
    }
```
😢

**Comment by dadhi** [comment]
What version of DryIoc do you use?

**Comment by GameBelial** [comment]
@dadhi 
The DryIoc version number I am using is 3.1.0-preview-06

**Comment by dadhi** [comment]
This exception is due an actual bug in processing of custom value for parameter selector, where value is array. Fix is in progress.

**Comment by GameBelial** [comment]
@dadhi 
ok,It is working now.
