### ISSUE TITLE
Cannot avoid TrackingDisposableTransients for Web

### ISSUE THREAD

**Issue by stevozilik** [dadhi/DryIoc#501]
When using DryIoc with Asp Net, current implementation is changing my container rules forcing TrackingDisposableTransients 

https://github.com/dadhi/DryIoc/blob/d2d4eb9f5f1448c51c8c939d89e6a352ee3bf323/src/DryIoc/Container.cs#L5407

My reason to use DryIoc (as opposed to e.g. the Microsoft DI) is because I can configure such behaviour to my preference. However the current implementation is forcing Disposing of Transient instances and hence introducing bugs in my code (undesirable disposing transient classes after each request) since using DryIoc in Web context behaves differently than using DryIoc without Web

**Example use case**
- IMemoryCache implements IDisposable. I've registered it as Transient, so I can have different instance for each use case
- 2 of my classes - e.g. CacheA, CacheB both require IMemoryCache as constructor argument, and are both registered as Singletons (for obvious reasons)
- when running in Web context, whilst CacheA and CacheB are alive across different requests, their underlying cache is disposed after first request, because it's transient. Instead if I wanted to dispose the underlying cache, CacheA,B can implement IDisposable and call IMemoryCache.Dispose() inside

If the reason for forcing this rule is such that Microsoft's transient dependencies are disposed after each request as if running with defualt DI, there is a different override that can be applied to each "microsoft" transient dependency on registering, rather than forcing this globally?

**Comment by dadhi** [comment]
Hi, that was down to conform with MS.DI, and probably it mat be modified to apply the `Setup.With(trackDisposableTransient: true)` for the `ServiceCollection` registrations. I will give it a though. The only drawback I see now is the increased complexity of the adapter, but let's see.
 
Until then, you may prevent the disposal of your components like this `c.Register<MyTransientDisposable>(setup: Setup.With(preventDisposal: true));`

**Comment by dadhi** [comment]
Given that this will be a breaking change and  there is a workaround, I will keep the current rules intact. Let's see if I have complaints.
