### ISSUE TITLE
was there something wrong make by me (RegisterMany) ?

### ISSUE THREAD

**Issue by sgf** [dadhi/DryIoc#517]
![图片](https://user-images.githubusercontent.com/2557696/184081317-38dbce57-9c7f-432f-b4f3-0c2a2798f120.png)

I refer to this example: https://stackoverflow.com/questions/42368192/dryioc-registermany-implementations-of-interface
by the way.DryIoc's API design looks little complex,not easy to use.

**Comment by sgf** [comment]
im see this example:https://stackoverflow.com/questions/42368192/dryioc-registermany-implementations-of-interface
 by the way.DryIoc's looks little complex,not easy to use.

**Comment by dadhi** [comment]
@sgf 
The exception is saying it all. In the provided `asms` there are no legit service types. 
I may mean that you don't have the types at all or no `public` types. In later case, if you want to register non-public types, then you need to pass `nonPublicServiceTypes: true` to `RegisterMany`.

Regarding complexity, if you are manipulating assemblies, you are already on the complex ground... 
I don't see how `container.RegisterMany(new[] { typeof(A).Assembly }, serviceTypeCondition: type => type == typeof(X));` makes it harder, **but I am open for suggestions**.

**Comment by sgf** [comment]
> 

i think,maybe the reason is what types i want to register is winform UseControl.
maybe because it's Implementation of IDisposable.

**Comment by sgf** [comment]
> @sgf The exception is saying it all. In the provided `asms` there are no legit service types. It may mean that you don't have the types at all or no `public` types. In the later case, if you want to register non-public types, then you need to pass `nonPublicServiceTypes: true` to `RegisterMany` (btw, **the exception message has this information as well**).
> 
> Regarding complexity, if you are manipulating assemblies, you are already on the complex ground... I don't see how `container.RegisterMany(new[] { typeof(A).Assembly }, serviceTypeCondition: type => type == typeof(X));` makes it harder, **but I am open for suggestions**.

thank,you
