### ISSUE TITLE
RegisterInitializer() not in IContainer

### ISSUE THREAD

**Issue by znakeeye** [dadhi/DryIoc#524]
Working with `Prism.DryIoc` and `Prism.DryIoc.Extensions` I want to register an initializer for all objects. However, the `IContainer` interface does not have the `RegisterInitializer()` method. Is this intended or can it be improved?

```c#
public override void RegisterTypes(IContainerRegistry containerRegistry)
{
    IContainer container = containerRegistry.GetContainer();
    container.RegisterInitializer(...); // No good :(
    // ...
}
```

**Comment by dadhi** [comment]
In v5+ `RegisterInitializer` is defined as extension method for `IRegistrator` which is implemented by `IContainer`, so it should be available.
