### ISSUE TITLE
Method not found: 'DryIoc.Rules DryIoc.Rules.WithoutFastExpressionCompiler()

### ISSUE THREAD

**Issue by lwlivy** [dadhi/DryIoc#529]
Version: 5.2.2

This error occurs when I use the following code.
How can I solve this problem.

new DryIocContainerExtension(new Container(CreateContainerRules())
                   .WithDependencyInjectionAdapter(services));

**Comment by dadhi** [comment]
What extension are you using? 

The exception means that the extension (whatever it is) expects the method `WithoutFastExpressionCompiler` to be present. But it was removed in DryIoc v5.

**Comment by lwlivy** [comment]
I want to combine IServiceCollection to inject, but it has not been successful.
Now, change to this way, but an error will be reported. When I simply use IServiceCollection, it will not work properly.Did I use it wrong?
**Error：**
System.ArgumentException:“At least one object must implement IComparable.”

**error location：**
public Repository(DbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
            _dbSet = _dbContext.Set<TEntity>();
        }

**IOC Code：**
containerRegistry.RegisterScoped<DbContext, LidsDbContext>();
var services = new[] { typeof(IRepositoryFactory), typeof(IUnitOfWork), typeof(IUnitOfWork<LidsDbContext>) };
containerRegistry.RegisterMany<UnitOfWork<LidsDbContext>>(services);
//containerRegistry.RegisterScoped<IRepositoryFactory, UnitOfWork<LidsDbContext>>();
//containerRegistry.RegisterScoped<IUnitOfWork, UnitOfWork<LidsDbContext>>();
//containerRegistry.RegisterScoped<IUnitOfWork<LidsDbContext>,UnitOfWork<LidsDbContext>>();
containerRegistry.RegisterScoped(typeof(IRepository<>), typeof(Repository<>));

**Comment by lwlivy** [comment]
Do you have any good suggestions？

**Comment by dadhi** [comment]
@lwlivy I don't fully understand the question and what the problem or exception do you have. I would suggest you to ask the question on StackOverflow tagging with dryioc and provide the  complete failing test, so people can understand the context.

**Comment by Sharemee** [comment]
@lwlivy You can see [DryIoc 5.0.0 — Method not found: WithoutFastExpressionCompiler()](https://github.com/PrismLibrary/Prism/issues/2770). This issue can close. Good luck.

**Comment by Tum4ik** [comment]
As far as I can understand, Prism is in action here. So, you can simply override the creation of the container rules. I guess it should be in the `App.xaml.cs` class.
```csharp
protected override Rules CreateContainerRules()
{
    return Rules.Default.WithConcreteTypeDynamicRegistrations(reuse: Reuse.Transient)
                        .With(Made.Of(FactoryMethod.ConstructorWithResolvableArguments))
                        .WithFuncAndLazyWithoutRegistration()
                        .WithTrackingDisposableTransients()
                        //.WithoutFastExpressionCompiler()
                        .WithFactorySelector(Rules.SelectLastRegisteredFactory());
}
```
