### ISSUE TITLE
DryIoc.Web 4.0.0 is incompatible with DryIoc 5.2.2

### ISSUE THREAD

**Issue by cjberg** [dadhi/DryIoc#533]
The `DryIoc.Web` NuGet package hasn't been updated since the changes in commit 32f7131731012b77c19c1245d76885bd0dfdf719 , which changed the `Scope` signature. If used in combination with 5.2.2 the following error is thrown:

```c#
[MissingMethodException: Method not found: Void DryIoc.Scope..ctor(DryIoc.IScope, System.Object).]
   DryIoc.Web.HttpContextScopeContextRequestHandler.SetOrKeepCurrentRequestScope(IScope current) +0
   DryIoc.Web.HttpContextScopeContext.SetCurrent(SetCurrentScopeHandler setCurrentScope) in D:\Dev\DryIoc\src\DryIoc.Web\DryIocWeb.cs:173
   DryIoc.Web.HttpContextScopeContextRequestHandler.OnBeginRequest(Object sender, EventArgs _) in D:\Dev\DryIoc\src\DryIoc.Web\DryIocWeb.cs:95
   ...
```
Would it be possible to release an updated version? A work-around is the stay on 4.8.8 that is compatible.

**Comment by dadhi** [comment]
@cjberg Thanks for letting me know. I will check if it is possible.

**Comment by dadhi** [comment]
fixed.

**Comment by hani1989** [comment]
When will the version be released?

**Comment by dadhi** [comment]
@hani1989 Soon, probably Today.

**Comment by hani1989** [comment]
@dadhi  Thanks for the information.

**Comment by dadhi** [comment]
@cjberg @hani1989 The DryIoc.Web v5.0.0 is released.

**Comment by cjberg** [comment]
@dadhi Thank you for taking the time to update the packages!
