### ISSUE TITLE
DryIoc Exeption in a Contructor of a Dependecy does tunnel through Resolve call

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/DryIoc#536]
We have a Dependecy wich throws a Exceptin in a constructor.

On a other Place, we use the Container to Resolve a Interface wich has the failing class as Parameter.

there we get this exception after a Timeout:
![image](https://user-images.githubusercontent.com/364896/198293060-689152ec-6627-4d21-af18-ce87b907aff9.png)

Is it possible to configure DryIoc to fail directly with the first exception?

**Comment by jogibear9988** [comment]
My first minimal example does work as it should: https://dotnetfiddle.net/TNKroS
I now look whats different in our code.

**Comment by jogibear9988** [comment]
I now found it. The first call raises the exception, the second one throws this error:

https://dotnetfiddle.net/N2GdDR

**Comment by jogibear9988** [comment]
maybe it's possible to store the exception and rethrow it? is that allowed?

**Comment by dadhi** [comment]
@jogibear9988 Looking...

**Comment by jogibear9988** [comment]
https://dotnetfiddle.net/nudfxA
So seems a rethrow is allowed or works.
So maybe you could store the Exception when a Singelton could not be created, and rethrow when it's resolved again.
