### ISSUE TITLE
Registry Caching issue - Multi Threaded

### ISSUE THREAD

**Issue by LunicLynx** [dadhi/DryIoc#55]
Hello,
we found an issue in the current version 3.0.2.

It can be reproduced in 3.1.0-X and 4.0.0-X;

Setting `r => r.WithoutInterpretationForTheFirstResolution()` in 4.0.0-x moves the issue but its still present.

The following code demonstrates the Problem:

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var container = new Container(/*r => r.WithoutInterpretationForTheFirstResolution()*/);
            container.Register<SlowService>();

            // Warmup(container);

            var enumerable = Gen(container).Take(10);

            Task.WaitAll(enumerable.ToArray());

            Console.WriteLine("Done");
            Console.ReadLine();
        }

        private static IEnumerable<Task> Gen(IContainer container)
        {
            while (true)
            {
                // Thread.Sleep(100);
                yield return Task.Run(() =>
                {
                    var fakeContext = new FakeContext();
                    using (var scope = container.OpenScope("Test"))
                    {
                        scope.UseInstance(fakeContext);
                        var slowService = scope.Resolve<SlowService>();
                    }
                });
            }
        }

        private static void Warmup(Container container)
        {
            Gen(container).First().Wait();
        }
    }

    class FakeContext { }
    class SlowService { }
```

The problem is the creation of the factory delegate for `ISlowService`. Which is generated as often as there are cores in the cpu, with this example code. In our real scenario the compilation of the delegate takes so long that it keeps happening for days until the load is gone and the delegate is finally added into the cache,

The problem starts in the UseInstance call where the registry is swapped. The Ref to the cache is copied but it contains an ref to an immutable hashmap which is copied into the new registry. While adding the compiled delegate to the old registry with the same immutable. But now the old registry has the new cache and the new registry has the old one, without this newly compiled delegate.

Registry usage itself should be scoped short and locked. I hope this does explain it well enough. 

Here are the lines in master which are involved:

1. Here is the reference to the current registry taken:
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L280

2. And used much later in this method here:
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L382

3. While in between a call to `UseInstance happens` which does this:
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L572

4. Which it self does this
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L734

5. `WithServices` calls `KeyedFactoryDelegateCache.NewRef()`
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L1679

After 5 the new Registry is safely exchanged but contains a reference to an immutable which will not be updated at 2, because its an old `Ref` with the same immutable. But updating that ref doesn't update the new Registry. So the new delegate never makes it into the cache.

Let me know if you need more infos. We really would like a fix for 3.0.x. 

In my example code there are 2 ways to mitigate the problem. Either a warmup before multi threading happens, or a delay before the yield return in the generator.

The delay isn't feasible for our scenario because this happens in a shopping website, which slows down until we get 503, 504 from the reverse proxy.

A warmup phase is what we are considering, but would also immensely slowdown initial startup.

Alternative Ideas? 

As a Note the `UseInstance` call comes from here:
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc.Owin/DryIocOwin.cs#L82

**Comment by LunicLynx** [comment]
To make it visible add a `Console.WriteLine("<...>");` here:
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L318
and here
https://github.com/dadhi/DryIoc/blob/7cc5eeac50a14baf3071532b3e6dc2d75b533998/src/DryIoc/Container.cs#L327

**Comment by dadhi** [comment]
@LunicLynx,

Thanks for the deep analysis!

I will review it shortly. But from the get-go, it seems like #48 will help.

**Comment by dadhi** [comment]
PRs are welcome, also at the moment I have no idea about general fix, need some time or/and help.

**Comment by LunicLynx** [comment]
Ok, i have an idea. Will try and send you a PR.

**Comment by LunicLynx** [comment]
Can you tell me what the commit hashes are for, 3.0.2, 3.1.0-x and 4.0.0-x ?

**Comment by dadhi** [comment]
- [4.0.0-preview-01](https://github.com/dadhi/DryIoc/commit/a101616f1d9eb8109229f2ce24eddb8cbe3e839b)
- [3.1.0-preview-07](https://github.com/dadhi/DryIoc/commit/63a59a7766be195024242c29d33a277b1c590ca7)
- [3.0.2](https://github.com/dadhi/DryIoc/commit/1c7ce4a9f0fca22cc8c69d72749abc75795c4aa4)

I need to add hashes to nuget packages after all.

**Comment by LunicLynx** [comment]
Either that or add tags to git 😜

**Comment by dadhi** [comment]
Yeah, always forgotten. Will do.

**Comment by LunicLynx** [comment]
This would be the fix for latest master. Please let me know what you think before i create a PR for all the other Versions.

Thanks

**Comment by dadhi** [comment]
We don't need this for v3.1 previews, they are naturally grown to v4 (the latest master)

**Comment by dadhi** [comment]
@LunicLynx 
I have opened code for `UseInstance` and immediately wanted to go somewhere else :( I will be starting with #48 to get a feeling.

**Comment by dadhi** [comment]
...it won't work for all cases (demonstrared by `todo` in added test). We need to make expression consuming the injected instance to be independent from the instance itself. So under the different scope or without it, it should inject a new instance or throw/fallback to normal resolution (if instance is ansent). That means the `Expression.Constant` won't do. We need some kind of dynamic behavior. 

The exactly same problem in current `UseInstance` solved by injecting instance `asResolutionCall`. We can do the same, and when instance is found in scope, inject a `Resolve(...)` call instead. Then in `Resolve` method we need to check scope / singletons again. Seems ok to try.

Point 2 is current `UseInstance` parameters: `serviceKey` and `ifAlreadyRegistered`. But maybe we can turn the instances collection in scope into the mini-registry, adding the `serviceKey` and `DefaultKey` to the mix. My feeling, it is still be much simplier than current `UseInstance` implementation, and more importantly it will be orthogonal to the main Registry. The task is to minimize performance  impact on scope creation and disposal.

**Comment by LunicLynx** [comment]
Will try. Thanks

**Comment by LunicLynx** [comment]
@dadhi Should i implement the test case for 48 or 55 ?

Either way, the test i would write would be to check that a specific function isn't called twice.
In This case, either:
`Interpreter.TryInterpretAndUnwrapContainerException()`
or
`Factory.GetDelegateOrDefault()`.
Is this what you had in mind?

**Comment by dadhi** [comment]
I was thinking about test #55.

It may happen that #48 is not needed when we do `UseInstance` right. Then #48 may be considered just a nice optimization option.

**Comment by dadhi** [comment]
Ok, I am not paying attention, will review your PR again and come back after that.

**Comment by LunicLynx** [comment]
To be exactly precise. #48 would also solve the first problem as well, as long as UseInstance isn't used anymore. Don't know if this was your intention?

**Comment by dadhi** [comment]
My intention was that `UseInstance` did not use `Registry` at all. Instead container when resolving things will firsr look into `Scope` object  (open scope or singletons) to find the instances.

**Comment by dadhi** [comment]
I will likely to go with two routes with UseInstance:
- RegisterDelegate(_  => instance)
- Use(_ => instance), super simple, works directly with scope.

**Comment by dadhi** [comment]
The work is done in #78. Closing it.
