### ISSUE TITLE
project Upgrade to core2.2 and then get an error

### ISSUE THREAD

**Issue by try3** [dadhi/DryIoc#56]
DryIoc  ver3.0.2

DryIoc.ContainerException: Dependency Microsoft.Extensions.DependencyInjection.IServiceScopeFactory as parameter "scopeFactory" reuse CurrentScopeReuse {Lifespan=100} lifespan shorter than its parent's: singleton Microsoft.Extensions.Http.DefaultHttpClientFactory {ServiceKey=DefaultKey(2)} #155

**Comment by dadhi** [comment]
ok, will check

**Comment by dadhi** [comment]
Until then, could try to set compat to `2_1`?

  
  services.AddMvc()
.AddControllersAsServices().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)

**Comment by try3** [comment]
yes,i already set；
now，i set  WithoutThrowIfDependencyHasShorterReuseLifespan this rule

**Comment by dadhi** [comment]
@try3, 

What is the version of `DryIoc.Microsoft.DependencyInjection` do you use?
Could you try the latest `2.2.0-preview-02` ?

**Comment by mike2212** [comment]
I've just created an issue on your bitbucket (https://bitbucket.org/dadhi/dryioc/issues/606/ihttpclientfactory-throws-error-when-used).  Just noticed that it's duplicated here.

I will try with the preview release and report back.

**Comment by mike2212** [comment]
Appears to be resolved in `2.2.0-preview-02`

**Comment by dadhi** [comment]
This version is pretty much stable. Non-preview will be out together with DryIoc v4.

**Comment by try3** [comment]
because i used DryIoc.Internal.  so , wait release v4,then try it again

**Comment by dadhi** [comment]
Oh, thanks for remainder, I need to restore DryIoc.Internal as well.
