### ISSUE TITLE
RegisterInstance missing Reuse

### ISSUE THREAD

**Issue by HypeillingerChillinger** [dadhi/DryIoc#566]
In `RegisterInstance` a reuse is probably missing. What if I wanted to use an interface with `RegisterInstance` but different implementations and scoped for different `Reuse.ScopedForService`?

**Comment by dadhi** [comment]
Mm, you can try to use a RegisterDelegate for this matter. Just return your instance from the delegate.

**Comment by HypeillingerChillinger** [comment]
Ok
