### ISSUE TITLE
container.GetServiceRegistrations() doesn't include decorator registrations

### ISSUE THREAD

**Issue by keirk** [dadhi/DryIoc#57]
I'm trying to create a report of service registrations and container.GetServiceRegistrations() seemed to be useful, but I've noticed that the enumeration doesn't seem to return services registered as decorators?

**Comment by dadhi** [comment]
I did not remember why it was not included. Then the Wrappers should be also provided somehow, right?

**Comment by keirk** [comment]
Yes, I guess so (we don't have any services using wrapper tbh).

**Comment by dadhi** [comment]
Try the latest preview v4.0.0-preview-01, it includes a new method `Factory[] IRegistrator.GetRegisteredFactories(Type serviceType, object serviceKey, FactoryType factoryType)`.

Here is the whole [`IRegistrator` interface](https://www.fuget.org/packages/DryIoc.dll/4.0.0-preview-01/lib/netstandard2.0/DryIoc.dll/DryIoc/IRegistrator).

**Comment by dadhi** [comment]
closing then...
