### ISSUE TITLE
`asResolutionRoot` does not affect validation

### ISSUE THREAD

**Issue by Metadorius** [dadhi/DryIoc#578]
```cs
            container.Register(
                Made.Of(_ => ServiceInfo.Of</*ILoggerFactory*/_SerilogLoggerFactory>(),
                    f => f.CreateLogger(Arg.Index<Type>(0)),
                    r => r.Parent.ImplementationType),
                setup: Setup.With(condition: r => r.Parent.ImplementationType != null,
                    asResolutionRoot: false));
```

Currently this does not affect validation whatsoever because there's no exclusion of `AsResolutionRoot == true` services in the `Validate`, which is counterintuitive.

_Originally posted by @Metadorius in https://github.com/dadhi/DryIoc/issues/577#issuecomment-1564329201_

One option would be amending the default validation condition which would probably make more sense in general conditions (usually there's not many resolution roots) but would break the default behavior: https://github.com/dadhi/DryIoc/issues/577#issuecomment-1564362538

Another option is:

> I would rather filter all registrations based on the IsResolutionRoot, then if nothing found fallback to the current behavior.

_Originally posted by @dadhi in https://github.com/dadhi/DryIoc/issues/577#issuecomment-1564377235_

**Comment by Metadorius** [comment]
Hello! Been checking for a while, is there any ETA on the new version release?

**Comment by dadhi** [comment]
@Metadorius No promises, but will try to release this weekend.

**Comment by dadhi** [comment]
@Metadorius Released right now, it might be some time until NuGet will index the 5.4.1 version.
