### ISSUE TITLE
Windows 11 - Smart App Control

### ISSUE THREAD

**Issue by hathawcs** [dadhi/DryIoc#581]
Windows 11 introduced Smart App Control. One of the security checks for apps is ensuring that the app and its binaries are signed. Because DryIoc does not sign its binaries, software using it will be blocked from running when Smart App Control is enabled.

Please sign DLLs produced for DryIoc.

https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003

DryIoc (unsigned):
![image](https://github.com/dadhi/DryIoc/assets/8010826/4cadd0fa-fa3d-4663-92d0-f5e2223dffdc)

Microsoft dll (signed):
![image](https://github.com/dadhi/DryIoc/assets/8010826/12c4bd49-e97d-4faf-bf7a-041ccca795ca)

**Comment by dadhi** [comment]
zomby returns, ok...

**Comment by dadhi** [comment]
@hathawcs Ok, I did not check it first, but you have an old version of DryIoc (v4.1.4)
The newer versions are signed with by the https://github.com/dadhi/DryIoc/blob/master/DryIoc.snk 
You may manually sign the old assemblies using this file via https://learn.microsoft.com/en-us/dotnet/framework/tools/signtool-exe or https://learn.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool or any other OSS tool.
