### ISSUE TITLE
Wrong comment for PropertiesAndFieldsSelector.All

### ISSUE THREAD

**Issue by michkot** [dadhi/DryIoc#592]
https://github.com/dadhi/DryIoc/blob/edec0182ca1611f29a00f7e4145da8d63315e439/src/DryIoc/Container.cs#L11399-L11407

>  If all parameters are omitted the return all public not primitive members

I cannot find any logic in the code that would implement that. is this maybe a relict of the past before such functionality was moved to PropertiesAndFieldsSelector.Auto ?
https://github.com/dadhi/DryIoc/blob/edec0182ca1611f29a00f7e4145da8d63315e439/src/DryIoc/Container.cs#L11358-L11359

**Comment by dadhi** [comment]
@michkot Thanks for finding, PR?
