### ISSUE TITLE
Breaking changes in MefAttributedModel

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#599]
Hi, Maksim!

There is a class in `MefAttributedModel` library that is used as a 
serializable container for exported registrations: [ExportedRegistrationInfo](https://github.com/dadhi/DryIoc/blob/edec0182ca1611f29a00f7e4145da8d63315e439/src/DryIoc.MefAttributedModel/AttributedModel.cs#L1353)

I use it in my app for registrations not available at compile time.
Scripted components are stored in the database with their serialized registrations.
On startup, I load and deserialize registrations and register in DryIoc container.
Serialized registrations allow to compile scripts on-demand rather than up-front.

When upgrading from version 4.8.7 I noticed that some properties became internal.
So I can't deserialize my registrations anymore 😮

![image](https://github.com/dadhi/DryIoc/assets/672878/9e895567-3798-47dc-b71a-e82c0d8b1c95)

I guess they are not public to protect the integrity of registrations.
But does it make sense in a serializable DTO class to have internal properties?
Can we revert the change and have them all public? Or am I missing something obvious?

**Comment by yallie** [comment]
Or can we just make `Flags` public?

**Comment by dadhi** [comment]
@yallie Done :) Will release a new version shortly

**Comment by yallie** [comment]
Thanks a lot! 👍
