### ISSUE TITLE
Could not load type 'System.ComponentModel.Composition.ExportAttribute' from assembly 'DryIocAttributes, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by SlowLogicBoy** [dadhi/DryIoc#60]
👋,

I have 2 projects:
1. Host - net461
1. Logic - netstandard2.0

Host has a reference to Logic
Logic contains references to:
DryIoc.dll
DryIoc.MefAttributedModel.dll
with code:
```csharp
var Container = new Container().WithMefAttributedModel();
Container.RegisterExports(new[] { GetType().Assembly }); //Exception is thrown here.
```

When I run Host I get the exception:
```
Exception has occurred: CLR/System.TypeLoadException
An unhandled exception of type 'System.TypeLoadException' occurred in mscorlib.dll: 'Could not load type 'System.ComponentModel.Composition.ExportAttribute' from assembly 'DryIocAttributes, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null'.'
<Cannot evaluate the exception stack trace>
```

If I run Host that targets `netcoreapp2.1` it works fine.

**Comment by dadhi** [comment]
What are the versions of DryIoc.MefAttributedModel and DryIoc?

**Comment by SlowLogicBoy** [comment]
DryIoc.dll 3.0.2
DryIoc.MefAttributedModel.dll 4.0.4

**Comment by dadhi** [comment]
Will check

**Comment by dadhi** [comment]
@SlowLogicBoy, 

What about the latest preview versions, did you see the same issue?

**Comment by dadhi** [comment]
Thanks, will release compatible Mef and Attributes versions shortly.

**Comment by dadhi** [comment]
@SlowLogicBoy The new versions are released Today. Please check and let me know if it works for you.

**Comment by SlowLogicBoy** [comment]
Sorry I won't be able to test this any time soon. I'll assume this works now.

**Comment by SlowLogicBoy** [comment]
Looks like issue hasn't been solved:
```xml
<PackageReference Include="DryIoc.dll" Version="4.0.4" />
<PackageReference Include="DryIoc.MefAttributedModel.dll" Version="5.0.0" />
```
Exception:
```
Exception has occurred: CLR/System.TypeLoadException
An unhandled exception of type 'System.TypeLoadException' occurred in mscorlib.dll: 
'Could not load type 'System.ComponentModel.Composition.ExportAttribute' from assembly 'DryIocAttributes, Version=5.0.0.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768'.'
```

**Comment by dadhi** [comment]
This is fine workaround, will look at problem when time permits. %hanks for letting me inow.

**Comment by SlowLogicBoy** [comment]
in net45 assembly there should be a TypeForward attribute for each type that's in System.ComponentModel.Composition namespace:
```csharp
[assembly: TypeForwardedTo (typeof (ExportAttribute))]
[assembly: TypeForwardedTo (typeof (MetadataAttributeAttribute))]
...
```
