### ISSUE TITLE
Add direct net8.0 target as soon as Appveyor CI will support it

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#606]

**Comment by yallie** [comment]
Related issue: https://github.com/appveyor/build-images/issues/140

**Comment by yallie** [comment]
.NET 8 is now supported on Appveyor! 🎉

**Comment by dadhi** [comment]
@yallie Thanks for letting me know!

**Comment by xingzuhui** [comment]
Updating fast，thanks

**Comment by dadhi** [comment]
done
