### ISSUE TITLE
Rules.SelectLastRegisteredFactory() does not account for OpenGenerics

### ISSUE THREAD

**Issue by LunicLynx** [dadhi/DryIoc#61]
See attached example.
I Would expect that `X` gets `AB` instead of `A<B>`.
I ran into this issue because of: https://github.com/dadhi/DryIoc/blob/a326e0af402bf55bece91b28988f2c764dee0338/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L65

```csharp
internal class Program
    {
        private static void Main(string[] args)
        {
            var container = new Container(rules => rules.WithFactorySelector(Rules.SelectLastRegisteredFactory()));
            container.Register(typeof(IX), typeof(X), Reuse.ScopedOrSingleton);
            container.Register(typeof(IA<B>), typeof(AB), Reuse.ScopedOrSingleton);
            container.Register(typeof(IA<>), typeof(A<>), Reuse.ScopedOrSingleton);

            var resolve = container.Resolve<IX>();
            resolve.WhoAmI();

            Console.ReadLine();
        }
    }

    internal interface IA<T>{void WhoAmI();}

    internal class A<T> : IA<T>
    {
        public void WhoAmI() => Console.WriteLine("A");
    }

    internal class B{}

    internal class AB : IA<B>
    {
        public void WhoAmI() => Console.WriteLine("AB");
    }
    internal interface IX{void WhoAmI();}

    internal class X : IX
    {
        public IA<B> A1 { get; }
        public X(IA<B> a){A1 = a;}

        public void WhoAmI() => A1.WhoAmI();
    }
```

**Comment by dadhi** [comment]
Not sure what's happening, but I will check. Thanks for reporting.

**Comment by LunicLynx** [comment]
I would expect that `var resolve = container.Resolve<IX>();` resolves to `X` with an instance of `AB`.
Since the registration `container.Register(typeof(IA<B>), typeof(AB), Reuse.ScopedOrSingleton);` is more explicit then `container.Register(typeof(IA<>), typeof(A<>), Reuse.ScopedOrSingleton);`.

But because of `rules.WithFactorySelector(Rules.SelectLastRegisteredFactory())` the fact that the second one is an open generic is ignored.
Which is arguably not completely incorrect but should in my opinion not the default for the DryIocAdapter. At least i wouldn't expect this behavior. 🤔

**Comment by dadhi** [comment]
fixed
