### ISSUE TITLE
Resolve within a scope returns parent instance

### ISSUE THREAD

**Issue by CoskunSunali** [dadhi/DryIoc#62]
This is my first time implementing something with DryIoc, so please pardon my ignorance if I am doing something wrong.

I create a container using the following piece of code.

```cs
var dryContainer = new DryIoc.Container()
    .With(rules => rules
        .With(FactoryMethod.ConstructorWithResolvableArguments)
        .WithFactorySelector(Rules.SelectLastRegisteredFactory())
        .WithTrackingDisposableTransients());
```

And I assign the `dryContainer` variable to another variable of type `IResolverContext`. Details don't matter but that is because I am trying to develop a wrapper around DryIoc.

```cs
_resolverContext = dryContainer;
```

My wrapper is of type `ICustomContainer`.

```cs
_resolverContext.UseInstance<ICustomContainer>(this);
```

That is so far so good. I can resolve any services I register within the root container, including `ICustomContainer`.

The `ICustomContainer` type has a method called `CreateScope` with a return type of again `ICustomContainer` - I guess you got why I keep a reference to `IResolverContext` which is because DryIoc's `OpenScope` method returns an `IResolverContext` too and I can use the `ICustomContainer` type both for the root container and for scopes too.

```cs
_resolverContext = parent.OpenScope(); // parent is the ICustomContainer instance I previously created

_resolverContext.UseInstance<ICustomContainer>(this, IfAlreadyRegistered.Replace);
````

Again, so far so good. I can call `Resolve<ICustomContainer>` on both the root `ICustomContainer` and the scope `ICustomContainer` for which the results are correct. Each returns the corresponding instance without any issues.

I have a service called `SomeService` which implements `ISomeService`. This service is registered using the `Populate` method which is located at https://github.com/dadhi/DryIoc/blob/master/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L135

The `SomeService` method has the following constructor.

```cs
public SomeService(ICustomContainer container)
{
}
```

The initial registration of that service within the `IServiceCollection` instance is as below.

```cs
services.AddSingleton<ISomeService, SomeService>();
```

Yes, it is a singleton registration and the first time it gets resolved is within a scope.

```cs
using (var scope = container.CreateScope())
{
    var someService = scope.GetRequiredService<ISomeService>();
}
```

Once again, if I resolve the `ICustomContainer` using `GetService` or `GetRequiredService` methods, I get the correct instances on both `container` and `scope` so the backing `IResolverContext` objects seem to be correct.

However, the problem is that the moment `ISomeService` is resolved, it is resolved with the root container even though it is resolved within the scope the first time.

Am I doing something wrong while configuring the DryIoc container?

Thank you for your reply in advance.

**Comment by dadhi** [comment]
Hi, thanks for detailed explanation.

I think it is a right behavior, cause singletons are always bound to the root context (initial container). That's why they are singletons - single instance in containers. Scopes are different from container, they don't have their own registration, they only have scoped instance in them (this includes instances added directly to scope via `UseInstance`, though here things may start to be wonky). I would've avoid using `UseInstance` if possible, because it mixes / messes instance between registration (how to find it) and an actual instance storage (scope or singleton scope). I have intention to cleanuo this behavior in upcomoing versions. There is an open issue somewhere.

**Comment by dadhi** [comment]
I mean you need to know more (than needed) and be aware of edge cases when using `UseInstance`. But if you figure out this, and your solution works, then it is fine.

**Comment by CoskunSunali** [comment]
Oh, okay. I had the impression that it should work because of the summary you have for the `UseInstance` method.

> Stores the externally created instance into open scope or **singleton**, replacing the existing registration and instance if any.

>But if you figure out this, and your solution works, then it is fine.

Well, it works partially. It works when I use `Resolve` to resolve the instance of the `ICustomContainer` but it doesn't work when it needs to inject the instances into constructors. Hence the confusion. 

Would that be unwise if I create new containers for each scope using `.With()`?

**Comment by CoskunSunali** [comment]
Alright, I debugged a bit more and it seems that it works as you described. It made me reconsider some of the design decisions I have taken, great job on your side!

Out of the scope but let me not create a new issue and waste your time there.

Let's say that I have a DryIoc container (`IContainer`) and I created a new container from that one using `.With`. Can I dispose the second container and its service instances without disposing the first one?

**Comment by CoskunSunali** [comment]
I guess I made it!

Just closing this issue.

Thank you for your replies!

**Comment by dadhi** [comment]
Using `With` is up to you. Just be aware that since v3, you may specify to keep the cache of original container, e.g. performance reasons. But it won't be as important in future (v4) with major first resolution perf improve (50x times faster).

**Comment by CoskunSunali** [comment]
I am utilizing DryIoc for a multi-tenant environment. There is a shared container (let's name it aspnetContainer) and there are containers for each site.

I could solve the issue with using named registrations but the tenants can be reloaded, unloaded, etc.

Considering these facts, I create so-called child containers for tenants using `With`.

If a tenant gets unloaded, the container created with `With` gets disposed.

That being said, my current "site container" creation code is as:

```cs
var tenantServiceCollection = GetTenantServices();
var container = aspnetContainer
    .WithoutCache();

container.Populate(containerBuilder);
```

Do you see any problems here? I guess I should not be calling `WithoutCache` and call `With` without any parameters instead, right? The rules will not change between the parent container and the tenant containers. It is just the tenant containers might have additional registrations and each tenant might have different registrations. Do I actually populate the services in the parent container when I invoke `Populate` on the tenant containers?

I am aware of the `WithRegistrationsCopy` but I am not sure if that copies singletons with their instances or not.

I guess I should play a bit more and see how it goes.

Thank you for your replies, great work!

**Comment by dadhi** [comment]
I would suggest you to look inside those `With..` methods. They just a sugar on top of single `With` method. You may use it directly and control all of parameters.
