### ISSUE TITLE
Consistent behavior of a faulty singleton

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#624]
### Discussed in https://github.com/dadhi/DryIoc/discussions/619

<div type='discussions-op-text'>

<sup>Originally posted by **yallie** December 20, 2023</sup>
Hello @dadhi,

Consider a singleton service that failed to initialize when it was first resolved.
What's the intended behavior on subsequent resolutions?

1. Should it rethrow the same exception every time it's resolved again?
2. Or should it rather retry its initialization (and if it succeeds, it's instance stays cached in the container)?</div>

**Comment by dadhi** [comment]
@yallie Hi there,

The tests describing the behavior and workarounds:
https://github.com/dadhi/DryIoc/blob/master/test/DryIoc.IssuesTests/GHIssue619_FaultySingletonDependency.cs

Summary:

- Exception will persist for the resolved singleton of the specific registration.
- The exception is the same `ScopedItemException` wrapping the original creation exception (I have fixed the issues with different exceptions appearing).
- You may work around by replacing or adding the new registration for the same service, so the faulty dependency will be re-resolved. 
- The non-eager singletons now fail consistently with the same `ScopedItemException`.

**Comment by yallie** [comment]
Awesome! Thanks a lot Maksim! 👍
