### ISSUE TITLE
FactoryType is not forwarded in the RegisterMapping<TService, TRegisteredService> method

### ISSUE THREAD

**Issue by bollhals** [dadhi/DryIoc#625]
[In this line](https://github.com/dadhi/DryIoc/blob/cceaf22f431fcd1d5c4864522b27f1d4ca6d3117/src/DryIoc/Container.cs#L9135), shouldn't the factoryType be forwarded to the next call? 

(It's not a problem for me, but I found this when I was looking for something else)

**Comment by dadhi** [comment]
@bollhals Wut ? :) yeah, it is a bug. Thanks for letting me know.
