### ISSUE TITLE
[BUG] Resolve<> crashes with the misleading, casting-related Exception when class is also registered using RegisterInitializer

### ISSUE THREAD

**Issue by MacSz-mjss** [dadhi/DryIoc#648]
Hello,

We use DryIoc in our project and don't always create registrations with standard DI `Register<TAbstraction, TImplementation>` manner, but rather simplified `Register<TImplementation>`. Having DryIoc, we also use `RegisterInitializer`, like so:

```
container.Register<SomeClass1>(Reuse.Singleton);
container.Register<SomeClass2>(Reuse.Singleton);
container.RegisterInitializer<SomeClass2>((service, _) => service.Initialize());
```

Under some circumstances, creating these instances for the very first time, using `Resolve<>`, can throw an Exception and this is expected behavior for our application.

We have recently found a bug in DryIoc that throws DryIoc logic-related Exception instead of the real Exception, thrown by our code while creating our instance using `Resolve<>`. The Exceptions thrown are related to object casting and might vary depending on unknown circumstances. We have found two distinct, yet similar Exceptions (being thrown while calling `Resolve<>` for the second time that throws our Exception; first attempt is always correct and caught by try/catch):

- `System.ArgumentException: Object of type 'DryIoc.ScopedItemException' cannot be converted to type 'SomeType'.`
- `System.InvalidOperationException : No coercion operator is defined between types 'DryIoc.ScopedItemException' and 'DryIoc.HiddenDisposable'.`

In both cases, the stack trace completely hides the real Exception we expect to see (it is expected that our codebase throws). Reproduction of the bug is attached in the below sample project:
[DryIocResolveBug.zip](https://github.com/user-attachments/files/15883171/DryIocResolveBug.zip)

As a workaround, we have found 2 working solutions:

1. Do not use `RegisterInitializer`: service registered using just only `Register<>` is resolved correctly - our expected Exception is always thrown as expected.
2. Use registrations with standard DI manner `Register<TAbstraction, TImplementation>`: as soon as the service is registered and resolved with the usage of an interface, it Resolves correctly, even if it used `RegisterInitializer`.

Kindly please fix the behavior so that DryIoc rethrows Exceptions being thrown by the registered services while Resolving.

**Comment by dadhi** [comment]
@MacSz-mjss Thanks for the reporting.

```cs
System.ArgumentException: Object of type 'DryIoc.ScopedItemException' cannot be converted to type 'SomeType'.
System.InvalidOperationException : No coercion operator is defined between types 'DryIoc.ScopedItemException' and 'DryIoc.HiddenDisposable'.
```

**Comment by MacSz-mjss** [comment]
You are welcome :). Thank you for your quick reply.

**Comment by MacSz-mjss** [comment]
@dadhi Hello
We have checked our case with the _6.0.0-preview-07_ version and the behavior is now correct 😊

Our expected exceptions are now thrown correctly and there are no signs of any object casting-related errors.

Thank you for your quick fix and response, we truly appreciate it 👍

**Comment by dadhi** [comment]
:-) fixed
