### ISSUE TITLE
Latest commit 33e0fe6  Resolve IHttpClientFactory throw a exception

### ISSUE THREAD

**Issue by try3** [dadhi/DryIoc#65]
i use Latest commit 33e0fe6 code,will throw a exception:
System.ArgumentNullException:“Value cannot be null.”

if use DryIoc.Microsoft.DependencyInjection 2.2.0-preview-02 it's ok

this is a demo in ConsoleApp
`
 class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddHttpClient();
            services.AddSingleton<ITest,Test>();
            //var provider = services.BuildServiceProvider();
            //provider.GetService<ITest>();

            IContainer container = new Container();
            container = container.WithDependencyInjectionAdapter(services);
            container.BuildServiceProvider();
            container.Resolve<ITest>();
        }
    }

    public interface ITest
    {
    }

    public class Test:ITest
    {
        public Test(IHttpClientFactory httpClientFactory)
        {
        }
    }
`

**Comment by dadhi** [comment]
Thanks for letting me know, will check.

**Comment by dadhi** [comment]
Seems no longer reproducible.
