### ISSUE TITLE
Populate on `IRegistrator`

### ISSUE THREAD

**Issue by Falco20019** [dadhi/DryIoc#660]
Is there a reason why `RegisterDescriptor` and `Populate` in the `DryIocAdapter` are defined on `IContainer` instead of `IRegistrator`? It's only using those APIs.

I'm in a context where I only get `IRegistrator` internally and would like to add a `ServiceCollection` using `Populate`. `((IContainer)builder).Populate(sc);` works fine, it's just ugly to rely on the knowledge that an `IRegistrator` in my case is always castable.

Would it be possible to change the API in an upcoming major version (if there is no hard reason for it as it is) or to at least add the `IRegistrator` variants, marking the other ones deprecated for backwards-compatibility?

**Comment by dadhi** [comment]
@Falco20019 Hi, seems you are right. I will try the change.

**Comment by dadhi** [comment]
@Falco20019 Done.

**Comment by dadhi** [comment]
Soon. I want to release it in the upcoming month.
