### ISSUE TITLE
DryIocAdapter.WithDependencyInjectionAdapter Adapter ServiceDescriptor.ServiceKey

### ISSUE THREAD

**Issue by LostAsk** [dadhi/DryIoc#661]
hello, dryioc not Adapter ServiceDescriptor.ServiceKey.help
![image](https://github.com/user-attachments/assets/e4c97422-d3ac-44bd-af7e-55feff527b4d)

**Comment by dadhi** [comment]
fixed, thank you.

**Comment by LostAsk** [comment]
> 固定，谢谢。

need fix IKeyedServiceProvider
![image](https://github.com/user-attachments/assets/acd6be1c-7ee9-402c-a7f2-87a0b66eb723)
