### ISSUE TITLE
DryIocAttirbutes and DryIoc.MefAttributedModel are not `nullable` friendly

### ISSUE THREAD

**Issue by abdes** [dadhi/DryIoc#663]
The implementation in these two modules is not nullable compatible, and when the dependencies are added to a project with `nullable` enabled, they generate many C# errors.

Disabling `nullable` for the entire project is not an option.

Please either add the generated tag in the file header comments:
```c#
// <auto-generated />
```

Or, disable nullable checks with `#nullable disable/enable`, or update the code to become nullable compliant.

**Comment by dadhi** [comment]
Thanks for the info. Will look.

**Comment by abdes** [comment]
Thank you for the quick turnaround.
