### ISSUE TITLE
Unable to resolve type with optional arguments with both MefAttributedModel and MS DI

### ISSUE THREAD

**Issue by lucacivale** [dadhi/DryIoc#669]
Using the `.WithMefAttributedModel()` will break with an Error.UnableToResolveUnknownService exception. 
I can repro this only if I enable Microsofts logging enrichment or redaction(Microsoft.Extensions.Telemetry). 

Tested this in a minimal console application with DryIoc.Microsoft.DependencyInjection 6.2.0 and DryIoc.dll 5.4.3

-- Crash --
```
HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);

builder.Logging
    .EnableEnrichment()
    .EnableRedaction();

builder.ConfigureContainer(new DryIocServiceProviderFactory(new Container(rules => rules.WithMefAttributedModel())));

using IHost host = builder.Build();

var container = host.Services.GetRequiredService<IContainer>();
var serviceProvider = container.Resolve<IServiceProvider>();

_ = container.Resolve<ILogger<Program>>();
_ = serviceProvider.GetRequiredService<ILogger<Program>>();
```

-- Works --
```
HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);

builder.ConfigureContainer(new DryIocServiceProviderFactory(new Container(rules => rules.WithMefAttributedModel())));

using IHost host = builder.Build();

var container = host.Services.GetRequiredService<IContainer>();
var serviceProvider = container.Resolve<IServiceProvider>();

_ = container.Resolve<ILogger<Program>>();
_ = serviceProvider.GetRequiredService<ILogger<Program>>();
```

**Comment by dadhi** [comment]
@lucacivale Interesting, thanks for the repro. Will look.

**Comment by dadhi** [comment]
@lucacivale I've reproduced the issue. Looking into it.

**Comment by lucacivale** [comment]
@dadhi glad to hear the issue is resolved. Can we have a bug fix release for DryIoc.dll 5.4?

**Comment by dadhi** [comment]
@lucacivale I am not sure about that. Personally I don't want spend the time on the previous version, because I am trying to release the new one right now.
