### ISSUE TITLE
change project url on nuget to github

### ISSUE THREAD

**Issue by gitlsl** [dadhi/DryIoc#67]
since you move here , please change `https://bitbucket.org/dadhi/dryioc`  on nuget      to github

**Comment by dadhi** [comment]
Thank you, here it was done for the upcoming version https://github.com/dadhi/DryIoc/blob/33e0fe6acfdfb2b18ffee5f069a3742591aaf910/src/Directory.Build.props#L9

**Comment by gitlsl** [comment]
ok thanks your nice work
