### ISSUE TITLE
Class Initializer for Class Libraries

### ISSUE THREAD

**Issue by ashtondavvo** [dadhi/DryIoc#69]
Hi,

We are writing a mobile application using Prism with Xamarin Forms. DryIoc looks like the best of the suggested compatible IoC frameworks. The issue we have is our existing Library code we are going to use in the application uses Autofac (which is not compatible with Prism).

Is there a way to use Autofac modules to register classes with DryIoc? Or is there a 'Class Initializer' interface we can implement which we can use to provide the DryIoc container with the Services from the Class Library? i.e. The interface would be implemented to request the Service from the Autofac container where applicable and provide this to DryIoc to use in the app. Autofac will take care of the internal dependencies we want to hide from the user of the library, but DryIoc will still be able to get a functioning Service from the Library.

Any help would be much appreciated.

**Comment by dadhi** [comment]
Here is the FAQ you may find helpful:
https://bitbucket.org/dadhi/dryioc/wiki/FaqAutofacMigration#markdown-header-modules
