### ISSUE TITLE
Context-based injection

### ISSUE THREAD

**Issue by nestquik** [dadhi/DryIoc#7]
I have the following classes:
```
public interface IValidator { }

public interface IValidator<T>:IValidator { }

public class AbstractValidator<T> : IValidator<T> { }

public class SignInViewModel {
    public SignInViewModel(IValidator validator) { }
}

public class SignUpViewModel {
    public SignUpViewModel(IValidator validator) { }
}
```
How can I configure registration to achive injection of `IValidator<SignInViewModel>` in `SignInViewModel` and `IValidator<SignUpViewModel>` into `SignUpViewModel` accordingly?

It's super easy in [SimpleInjector](https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection):
```
container.RegisterConditional(
    typeof(IValidator),
    c => typeof(AbstractValidator<>).MakeGenericType(c.Consumer.ImplementationType),
    Lifestyle.Singleton,
    c => true);
```

**Comment by dadhi** [comment]
DryIoc way:

    container.Register<IValidator>(
        Reuse.Singleton,
        made: Made.Of(r => typeof(AbstractValidator<>).MakeGenericType(r.Parent.ImplementationType).SingleConstructor()));

Writing from phone,

**Comment by dadhi** [comment]
Hmm, seems like I am lacking `Made.Of` overload for using implementation type directly, w/out specifying a constructor. Will be adding then.

**Comment by nestquik** [comment]
@dadhi I'm not sure if I should open new issue.
```
namespace Validators // not my assembly
{

    internal class ObjectValidator<TObject> : IObjectValidator where TObject : IValidatableObject
    {
        public ObjectValidator(TObject instance)
        {
        }
    }

    public interface IObjectValidator
    {
    }

    public interface IValidatableObject
    {
        IObjectValidator Validator { get; }
    }

    public interface IObjectValidatorBuilder
    {
        IObjectValidator Build(IValidatableObject instance);
    }

    public interface IObjectValidatorBuilder<in TObject> where TObject : IValidatableObject
    {
        IObjectValidator Build(TObject instance);
    }

    public class ValidationBuilder<TObject> :
        IObjectValidatorBuilder<TObject>,
        IObjectValidatorBuilder
        where TObject : IValidatableObject
    {
        IObjectValidator IObjectValidatorBuilder.Build(IValidatableObject instance)
        {
            return Build((TObject)instance);
        }

        public IObjectValidator Build(TObject instance)
        {
            var validator = new ObjectValidator<TObject>(instance);
            return validator;
        }
    }
}
```

How can I configure container to resolve `IObjectValidator` like this:
```
public class SignInViewModelValidationBuilder : ValidationBuilder<SignInViewModel>
{
}

public class SignInViewModel
{
    public SignInViewModel(IObjectValidator validator) // IObjectValidator should be build by SignInViewModelValidationBuilder 
    {
    }
}

public class SignUpViewModelValidationBuilder : ValidationBuilder<SignUpViewModel>
{
}

public class SignUpViewModel
{
    public SignUpViewModel(IObjectValidator validator) // IObjectValidator should be build by SignUpViewModelValidationBuilder 
    {
    }
}
```

With SimpleInjector I can achieve this only with property injection, what about DryIoC?

**Comment by dadhi** [comment]
Hi @nestquik 

Check the added sample test: https://github.com/dadhi/DryIoc/blob/master/Net45/DryIoc.IssuesTests/GHIssue7_2_Context_based_injection.cs

The problem is in recursive dependency - DryIoc will detect it and indicate what is that in the error message.

Injecting as property is one on possibilities. The other one is injecting as `Func<T, R>`.

**Comment by dadhi** [comment]
@nestquik

... or something more crazy, like this :-)

https://github.com/dadhi/DryIoc/blob/master/Net45/DryIoc.IssuesTests/Interception/WrapAsLazy.cs

https://github.com/dadhi/DryIoc/blob/master/Net45/DryIoc.IssuesTests/Interception/WrapAsLazyTests.cs

**Comment by nestquik** [comment]
Is it possible to change `SignInViewModelValidationBuilder` to `IObjectValidatorBuilder` to have more generic registration?
https://github.com/dadhi/DryIoc/blob/8fae38801d77c1e8f7ec6889b33ee80f2a9f2d04/Net45/DryIoc.IssuesTests/GHIssue7_2_Context_based_injection.cs#L18

**Comment by dadhi** [comment]
Single registration to fit all ViewModels? Need to think a bit..

**Comment by nestquik** [comment]
@dadhi after registering builders and objects with `RegisterMany` resolving throws exception:
```
DryIoc.ContainerException: 'Expecting single default registration but found many:
KV(DefaultKey(0), {ID=32, ImplType=Sigin.Client.Wpf.Framework.Validation.Builders.SignInViewModelValidationBuilder, Reuse=SingletonReuse {Lifespan=1000}}), 
KV(DefaultKey(1), {ID=33, ImplType=Sigin.Client.Wpf.Framework.Validation.Builders.SignUpViewModelValidationBuilder, Reuse=SingletonReuse {Lifespan=1000}}), 
KV(DefaultKey(2), {ID=34, ImplType=Sigin.Client.Wpf.Framework.Validation.Builders.UserViewModelValidationBuilder, Reuse=SingletonReuse {Lifespan=1000}})
when resolving ReactiveValidation.IObjectValidatorBuilder with args [_SignInViewModel0]
  in singleton ReactiveValidation.IObjectValidator #40 with args [_SignInViewModel0]
  in wrapper Func<Sigin.Client.Wpf.ViewModels.SignInViewModel, ReactiveValidation.IObjectValidator> as parameter "validator" #10 with args [_SignInViewModel0]
  in Sigin.Client.Wpf.ViewModels.SignInViewModel #29
  from container.
Please identify service with key, or metadata, or use Rules.WithFactorySelector to specify single registered factory.'
```

Here `IObjectValidator` registration:
```
_container.Register<IObjectValidator>(
    Made.Of(
        r => ServiceInfo.Of<IObjectValidatorBuilder>(),
        builder => builder.Build(Arg.Of<IValidatableObject>())
    ),
    setup: Setup.With(condition: req => req.Parent.ImplementationType.IsAssignableTo<IValidatableObject>())
);
```

**Comment by dadhi** [comment]
I did not specify anywhere dependency to view model type. I think you need this overload: https://www.fuget.org/packages/DryIoc.dll/3.0.2/lib/netstandard2.0/DryIoc.dll/DryIoc/Made?code=true#M%3ADryIoc.Made.Of%28System.Func%7BDryIoc.Request%2CSystem.Reflection.MemberInfo%7D%2CSystem.Func%7BDryIoc.Request%2CDryIoc.ServiceInfo%7D%2CDryIoc.ParameterSelector%2CDryIoc.PropertiesAndFieldsSelector%29

You should consider generic `IObjectValidatorBuilder<Tvm>`. 

Don't gave a laptop with me for now to provide a full solution. Look back at first / initial example.

**Comment by nestquik** [comment]
I'll wait, cuz still don't get it.

**Comment by dadhi** [comment]
Here is the most succinct working variant: https://github.com/dadhi/DryIoc/blob/master/Net45/DryIoc.IssuesTests/GHIssue7_2_Context_based_injection.cs#L63

Check above a couple of more ways.

**Comment by nestquik** [comment]
Thank you very much for your help and for the incredible DryIoC.
