### ISSUE TITLE
No ContainerException thrown for a missing type

### ISSUE THREAD

**Issue by Leon99** [dadhi/DryIoc#70]
I was switching to DryIoc in a .NET Core console app that uses IHostedService. Found https://stackoverflow.com/questions/51872490/use-hostbuilder-configureservices-with-dryioc-container, but the code from there didn't work for me. Then I switched back to MS DI, and got an error about a missing registration. Fixed it, now DryIoc works as well. Here is the simplified code:
```csharp
class BootstrapService : IHostedService
{
        public BootstrapService(FooService bar){}
...
}

class Program
{
    static async Task Main(string[] args)
    {
        var host = new HostBuilder()
            .ConfigureServices(services =>
            {
                services.AddHostedService<BootstrapService>();
            })
            .UseServiceProviderFactory(new DryIocServiceProviderFactory())
            .ConfigureContainer<Container>((hostContext, container) =>
            {
// no errors from DryIoc when the following line is uncommented
//                container.Register<FooService>(Reuse.Transient);
            })
            .ConfigureHostConfiguration(builder => { builder.AddEnvironmentVariables(); })
            .Build();

        await host.RunAsync();
    }
}
```

**Comment by dadhi** [comment]
In this SO answer, the `DryIocServicePrioviderFactory` does not pass any optional argument to `.WithDependencyInjectionAdapter(services)`. But in reality the method accepts `Func<Type, bool> throwIfUnresolved` parameter where you can specify to use DryIoc exceptions for certain (all) unresolved types.

**Comment by dadhi** [comment]
Btw, thanks for the issue. Will use it as a note to add the parameter to `https://github.com/dadhi/DryIoc/blob/master/src/DryIoc.Microsoft.Hosting/DryIocHosting.cs` as well. 

I was also planning to create package `DryIoc.Microsoft.WebHosting` or something. I am not sure did MS consolidated general and the web hosting in the latest releases.

**Comment by Leon99** [comment]
Thanks, I'll try that. From reading https://bitbucket.org/dadhi/dryioc/wiki/ErrorDetectionAndResolution, I was under impression that throwing the exception is the default behaviour.

> consolidated general and the web hosting in the latest releases
They didn't in v2.2, although I read they plan to. I haven't tried 3.0 preview.

**Comment by dadhi** [comment]
Yes, default in DryIoc. But MS.DI has a different default convention in its abstraction :/

**Comment by Leon99** [comment]
Hmm but MS.DI actually throws the exception

**Comment by dadhi** [comment]
I was talking about Ms.Di conforming abstraction for other containers. But yes, it may be a completely different issue.
