### ISSUE TITLE
Any changes with ThrowIfDependencyHasShorterReuseLifespan?

### ISSUE THREAD

**Issue by SeriousM** [dadhi/DryIoc#77]
After updating  DryIoc.Microsoft.DependencyInjection from v.2.1.0 to v3.0.0-preview-01 I got a ContainerException in context of ThrowIfDependencyHasShorterReuseLifespan.

Did something changed? I tried to compare the two versions but can't find any obvious modifications to the settings. Maybe you can help me @dadhi?

Thank you very much.

**Comment by dadhi** [comment]
> from v.2.1.0 to v3.0.0-preview-01

Sorry, to what version did you update? The latest preview version is v4.0.0-preview-02 and the latest stable version is v3.0.2

**Comment by SeriousM** [comment]
Ah sorry, two packages.

DryIoc.Microsoft.DependencyInjection: v2.1.0 -> v3.0.0-preview-01
DryIoc.dll: v3.0.2 -> v4.0.0-preview-02

**Comment by SeriousM** [comment]
Maybe it isn't an error yet the result of the recent changes.

This is the full message
```
DryIoc.ContainerException: Dependency Adventics.Shared.Database.DbEntities as parameter "context" reuse Scoped {Lifespan=100} lifespan shorter than its parent's: scoped Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore<Adventics.Shared.Database.Identity.ApplicationUser, Microsoft.AspNetCore.Identity.IdentityRole, Adventics.Shared.Database.DbEntities, String, Microsoft.AspNetCore.Identity.IdentityUserClaim<String>, Microsoft.AspNetCore.Identity.IdentityUserRole<String>, Microsoft.AspNetCore.Identity.IdentityUserLogin<String>, Microsoft.AspNetCore.Identity.IdentityUserToken<String>, Microsoft.AspNetCore.Identity.IdentityRoleClaim<String>>: Microsoft.AspNetCore.Identity.IUserStore<Adventics.Shared.Database.Identity.ApplicationUser> as parameter "store" FactoryId=366
  in scoped Microsoft.AspNetCore.Identity.UserManager<Adventics.Shared.Database.Identity.ApplicationUser> as parameter "userManager" FactoryId=363
  in scoped Adventics.Account.Web.Utils.CustomUserClaimsPrincipalFactory: Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory<Adventics.Shared.Database.Identity.ApplicationUser> {ServiceKey=DefaultKey(1)} as parameter "factory" FactoryId=376
  in Adventics.Account.Web.Controllers.TestController {DryIoc.IfUnresolved.ReturnDefaultIfNotRegistered} FactoryId=330 IsResolutionCall
  from Container with Scope {no name}
 with Rules with {TrackingDisposableTransients, SelectLastRegisteredFactory} and without {ThrowOnRegisteringDisposableTransient, ImplicitCheckForReuseMatchingScope}
 with FactorySelector=SelectLastRegisteredFactory
 with Made={FactoryMethod=ConstructorWithResolvableArguments, PropertiesAndFields=<custom>}
To turn Off this error, specify the rule with new Container(rules => rules.WithoutThrowIfDependencyHasShorterReuseLifespan()).
```

And here are the types used:
testController: TransientReuse/0 (via MS.DI)
-> customUserClaimsPrincipalFactory: ScopedOrSingleton/1000 (via MS.DI)
-> userManager: ScopedOrSingleton/1000 (via MS.DI)
-> -> dbEntities: Scoped/100 (self registered)

The resolution happens during an api call, thus, in a scope.
Should the MS.DI services be flagged as Scoped instead of SingletonOrScoped?
Can I disable the error but get a warning callback instead for such problems (like in validate with special rule options)?

**Comment by dadhi** [comment]
I see what the problem is now, thanks.

`ScopedOrSingleton` should allow `Scoped` dependencies if resolved as `Scoped`. Probably I did broken something with latest fixes for other things. Should fix it now.

**Comment by SeriousM** [comment]
I've added 4 tests all related to scoped resolves in via a parent container where 3 of them fail.
The strange thing is that in one case the lazy was created but results in null.

**Comment by SeriousM** [comment]
These tests were working prior v4.

**Comment by SeriousM** [comment]
Could you publish a new preview package?

**Comment by dadhi** [comment]
I will publish a stable release Today.

**Comment by SeriousM** [comment]
Works, thank you
