### ISSUE TITLE
Split UseInstance two roles into separate RegisterInstance and Use

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#78]
The problem with `UseInstance` is that it conflates to use cases: adding a new registration and adding a new instance into the current scope or singletons scope. That's it is so complex and implemented in a specific way without reusing the common registration path.

Here I am splitting it into two specialized methods: `RegisterInstance` and `Use`:

`RegisterInstance` method:
- From the User perspective is just a `RegisterDelegate(_ => instance)`, except it will `Dispose` the registered `IDisposable` instance when the container is disposed even if the instance was not resolved or injected once.
- Always a Singleton
- Available in `IRegistrator` and `IContainer`
- Is Not specific to the current scope
- Is Not available in `IResolver` and `IResolverContext`

`Use` method:
- Puts the instance directly into the current scope or singletons scope
- Can be put via the `FactoryDelegate` which creates the instance every time when resolved or injected
- Is available in `IResolver` and `IResolverContext`
- Does Not support service keys, decorators, or any other registration features
- Is Not resolved in `ResolveMany` or in Wrappers

**Comment by CoskunSunali** [comment]
Great release!

Does it mean that any instance registered using the `Use` method doesn't get disposed even if it implements `IDisposable` and `IResolverContext.Dispose` is invoked?

**Comment by dadhi** [comment]
Yep, it does not track. But `ResolverContext` has a `TrackDisposable` ext method to help.

```cs
var foo = new Foo();
container.Use(r => r.TrackDisposable(foo));
```

**Comment by CoskunSunali** [comment]
Thanks for the quick response!
