### ISSUE TITLE
Parity of registration methods between IContainer and IRegistrator

### ISSUE THREAD

**Issue by lassevk** [dadhi/DryIoc#8]
Since using a composition root seems to be easier with `IRegistrator` than with `IContainer` (a nested container is injected?), it would be nice if there was parity between the methods available on the two interfaces so that `IRegistrator` could be used instead of `IContainer`.

For instance, these methods are available on/for `IContainer` but not `IRegistrator`:

* UseInstance
* RegisterMapping
* RegisterPlaceholder

I didn't check if overloads are missing.

**Comment by dadhi** [comment]
@lassevk, Thanks, for posting. 

The reason for moving these methods to `IContainer`, is the need for resolution behavior. For instance,  `UseInstance` need to access a current scope if any, but this runtime data is not available from registrator.

V3 had introduced (made public) a `IResolverContext` wich provides access to `UseInstance` and scopes in addition to `IResolver` methods.

But I see that it is not ideal. Will try to improve.

Btw, `RegisterPlaceholder` not in the registrator seems like a bug, will check.

**Comment by dadhi** [comment]
@lassevk,

Interesting, if I add the methods to `IRegistrator` now, without pulling them off `IContainer`. Will it be a breaking change?

**Comment by dadhi** [comment]
Hey @lassevk, 

I have added `UseInstance`, `RegisterMapping` (extended with optional FactoryType argument), and `RegisterPlaceholder` for IRegistrator.

Non-breaking from the static API :-) Yay!

**Comment by jzabroski** [comment]
I think the phrase Container masks the duality between IContainer and IRegistrator. While IContainer is a natural term in Java/C#/OOP land, the correct name is IRegistry and IRegistrar. A Registrar is one who keeps an official book of registers, whereas a Registrator is one who registers with the Registrar. The  Registry "is maintained by" the Registrar. In order as a consumer to register your services, you ask the registrar. In this sense, DryIoC abstracting request scope and resolution gives it a "Blackboard pattern" where you can both a) publish services b) discover subscription terms c) subscribe anonymously but be granted subscription terms (I.e. why was THIS object the one I got from the container?) 

Am I incorrect?

Sorry if this is philosophical drivel
