### ISSUE TITLE
Suppress registration exceptions by service type

### ISSUE THREAD

**Issue by coreyasmith** [dadhi/DryIoc#81]
I've been experimenting with DryIoc on top of Sitecore, which has hundreds of its own services registered with the built-in `Microsoft.Extensions.DependencyInjection` container. Out of the box, Sitecore has three registrations that fail the shorter reuse lifespan rule. To get DryIoc to work, it seems there are two options: re-register Sitecore's services to pass the rule, or disable the rule for the Container altogether. Neither option is ideal--I'd rather be able to tell DryIoc to suppress the exception for the offending services.

Is it possible to suppress rules per service registration with DryIoc?

**Comment by SeriousM** [comment]
Hi @coreyasmith, which version did you use? In case of v4 preview there is a flaw with lifetimes. #77

**Comment by coreyasmith** [comment]
> Hi @coreyasmith, which version did you use? In case of v4 preview there is a flaw with lifetimes. #77

In my case, Sitecore is registering singleton services that depend on scoped services, which should indeed throw an exception. I'd just like to suppress the exception for those services and have DryIoc continue to validate my other registrations.

**Comment by dadhi** [comment]
@coreyasmith, Check out the new Today's versions. Let me know if they helped.

**Comment by dadhi** [comment]
Closing as there was not any updates.
