### ISSUE TITLE
Update Sample WithDependencyInjectionAdapter for version 4, pls

### ISSUE THREAD

**Issue by vdasus** [dadhi/DryIoc#86]
Can you update sample to last version? How to use 
``` csharp
 throwIfUnresolved: type => type.Name.EndsWith("Controller")
```
in DryIoc 4.0?

After upgrading from 2 to 4 can't build project:
Error	CS1739	The best overload for 'WithDependencyInjectionAdapter' does not have a parameter named 'throwIfUnresolved'	DryIoc.AspNetCore.Sample

``` csharp
.WithDependencyInjectionAdapter(services,
                    // optional: get original DryIoc.ContainerException if specified type is not resolved, and prevent fallback to default resolution by infrastructure
                    throwIfUnresolved: type => type.Name.EndsWith("Controller"))
                .ConfigureServiceProvider<CompositionRoot>();
```

**Comment by SeriousM** [comment]
This change was added with: https://github.com/dadhi/DryIoc/commit/aff9a3531e3ea10eae9f8e4e764225dea4542a71#diff-1b67f547c8bdf0c85ef20d3423360002L86

**Comment by dadhi** [comment]
I will update the sample. You don't need `throwIfUnresolved: type => type.Name.EndsWith("Controller")` anymore. It should throw automatically.

**Comment by vdasus** [comment]
Thank you

**Comment by dadhi** [comment]
@vdasus I have updated the sample.

**Comment by vdasus** [comment]
@dadhi You are incredible fast :) thank's again
