### ISSUE TITLE
Use IServiceCollection extensions only with DryIoc Container/IRegistrator?

### ISSUE THREAD

**Issue by SeriousM** [dadhi/DryIoc#87]
I want to use extensions that target IServiceCollection with the DryIoc Container, is this somehow possible?
The reason is that some nuget packages hide the implementation types and only expose the interfaces (as good architecture does) and I can't register the services in a DryIoc-exclusive environment because there is nowhere a IServicesCollection adaption around.

Could you help me with an idea how to achieve this? A workaround with special constructs would do it as well.

Thank you very much!

**Comment by dadhi** [comment]
Could you illustrate with pseudo example code what you want to achieve?

**Comment by SeriousM** [comment]
Here is the example:

The package [CodeBasics.Command contains the ServiceCollection extension](https://www.fuget.org/packages/CodeBasics.Command/1.0.3/lib/netstandard2.0/CodeBasics.Command.dll/CodeBasics.Command/CommandServiceExtensions?code=true) that injects the services for CommandFactory into the services.
When using DryIoc I still want to use the ICommandFactory but I can't access the internal types of the package.

I already found the solution, it's actually via the dryioc.microsoft.dependencyinjection package:

```
var serviceCollection = new ServiceCollection();
serviceCollection.AddCommands(); // or whatever service you want to use
var container = new Container();
// add my own registrations
var augmentedContainer = container.WithDependencyInjectionAdapter(services);

// use augmentedContainer as usual with the injected ServiceCollection services.
```
