### ISSUE TITLE
Update Sample to demo Lazy/Func registration

### ISSUE THREAD

**Issue by jzabroski** [dadhi/DryIoc#88]
Samples should include examples of: https://github.com/dadhi/DryIoc/issues/4

**Comment by jzabroski** [comment]
I think the ideal way is to just write something like:
```csharp
public interface IAlwaysLazy
{
}
public class ExpensiveResource : IAlwaysLazy
{
  public ExpensiveResource
  {
     //download all of project gutenberg here :)
  }
}
```

Then update [CompositionRoot.cs](https://github.com/dadhi/DryIoc/blob/master/samples/DryIoc.AspNetCore.Sample/CompositionRoot.cs)

```
c.RegisterAsLazy<IAlwaysLazy, ExpensiveResource>();
```

**Comment by dadhi** [comment]
You mean sample in `DryIoc.Docs`? I am accepting PRs for that as well :)

**Comment by jzabroski** [comment]
No, I think maybe the link changed but I'm referring to the AspNetCore sample in the samples folder: https://github.com/dadhi/DryIoc/tree/master/samples/DryIoc.AspNetCore.Sample

**Comment by dadhi** [comment]
Ok, I may include such an example but there are a lot of in the docs already. I just don"t see a value, cause this sample is more about .Net Core intergration. It is already includes too much non related optional things for my taste.
