### ISSUE TITLE
DryIoC.CommonServiceLocator.dll package out-of-date link

### ISSUE THREAD

**Issue by jzabroski** [dadhi/DryIoc#89]
New link: https://github.com/unitycontainer/commonservicelocator

**Comment by dadhi** [comment]
Mmm, you mean link in the readme or where?

**Comment by jzabroski** [comment]
https://www.nuget.org/packages/DryIoc.CommonServiceLocator.dll/ codeplex site tells user to click to github.  Eventually the codeplex will go away.

**Comment by dadhi** [comment]
Oh, got it. thanks.
