### ISSUE TITLE
DryIoc.ComminServiceLocator.dll nuget package needs updated.

### ISSUE THREAD

**Issue by pkoelbl** [dadhi/DryIoc#91]
This package hasn't been updated to 4.0.0 https://www.nuget.org/packages/DryIoc.CommonServiceLocator.dll/3.1.0-preview-01

**Comment by dadhi** [comment]
Good catch, thanks. Just forgot to publish it. Will do.

**Comment by dadhi** [comment]
Published V4 packages, should be available shortly.
