### ISSUE TITLE
Support ASP.NET Core 3.0

### ISSUE THREAD

**Issue by HamedFathi** [dadhi/DryIoc#92]
You can not define a return type for `ConfigureServices` in ASP.NET Core 3.0. I got an error on this.

```cs
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    ...
}
```

Can you show me how to use you amazing IoC with ASP.NET Core 3.0 preview 3?

**Comment by dadhi** [comment]
Will try it soon. Thanks for head up.

**Comment by dadhi** [comment]
The docs for the reference:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0

**Comment by HamedFathi** [comment]
@dadhi 
Yes, I tried it before, please see the following picture.

![image](https://user-images.githubusercontent.com/8418700/54876610-6caa2f00-4e30-11e9-9a74-6186133e0ec3.png)

**.NET Core 3.0.100-preview3-010431**
```
Unhandled Exception: System.NotSupportedException: ConfigureServices returning an System.IServiceProvider isn't supported.
   at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at DryIOC.Program.Main(String[] args) in C:\...\DryIOC\Program.cs:line 18
```

Related link:

[Unable to use ConfigureTestServices with StructureMap](https://github.com/aspnet/AspNetCore/issues/5949)

**Comment by dadhi** [comment]
Instead of creating the Container in your Startup, you may just move it the host, and make Startup fully IOC agnostic - see deails here: https://github.com/dadhi/DryIoc/issues/94#issuecomment-475605873

In addition, `DryIocServiceProviderFactory` has couple of optional parameters if you need some customization.

**Comment by HamedFathi** [comment]
I revert all configs in `Startup.cs` except `AddControllersAsServices`
![image](https://user-images.githubusercontent.com/8418700/54880479-8fedd200-4e62-11e9-83a1-2a1228b2bf55.png)

And in `Program.cs` 

![image](https://user-images.githubusercontent.com/8418700/54880521-025eb200-4e63-11e9-9f09-66502f04d55e.png)

```
Could not load file or assembly 'DryIoc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=dfbf2bd50fcf7768'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by dadhi** [comment]
This is strange, could you share this sample application with me?

**Comment by HamedFathi** [comment]
Sure, You can find it [here](https://github.com/HamedFathi/DryIOCMVCCore3)

**Comment by dadhi** [comment]
I tried to build the sample in vs2019 and .NET Core 3 preview 3, and after some quirks got the same error.

Not sure the reason, but it shoud not relate to DryIoc itself. DryIoc is strongly signed now, is it a problem? or is it a binding redirects? Not sure. But won't spend much time on it until RC. If you yave ideas, pleaze help.

**Comment by dadhi** [comment]
I think a possible workaroud would be the use of source code package for DryIoc.MS.DI, which is not existent. Maybe it is time to make it , hmmm...

**Comment by dadhi** [comment]
I have published __DryIoc.Microsoft.DependencyInjection.src__ source package and will try it.

**Comment by dadhi** [comment]
Puzzle solved:

![image](https://user-images.githubusercontent.com/39516/55293801-fc3c7880-5402-11e9-8d1c-eeff130e57a7.png)

The problem was that the sample project has the same name as the transient dependency (DryIoc).
