### ISSUE TITLE
DryIoc.Microsoft.Hosting depends on DryIoc 3.0.2

### ISSUE THREAD

**Issue by jasper-d** [dadhi/DryIoc#94]
## Repro:
1. Create a new project and add DryIoc.dll v. 4.0.0 Dry.Microsoft.Hosting 1.0.0-preview-01
2. Add some code that uses it, i.e. `var host = new HostBuilder().UseDryIoc(s=> new Container().WithDependencyInjectionAdapter(s))` 
3. Compile

## Expected:
Compilation succeeds

## Actual:
Compilation fails with:
> error CS0012: The type 'IContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'DryIoc, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'

**Comment by dadhi** [comment]
Hi @jasper-d ,

Do you still need this extension? 
Cause now you can you use:

```
var host = new HostBuilder()
    .UseServiceProviderFactory(new DryIocServiceProviderFactory());
```

`DryIoc.Microsoft.Hosting` was just a sugar on top of [`DryIocServiceProviderFactory`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#container-configuration) - it is a one-liner to wrap it in `UseDryIoc` method. 
I think, starting from the ASP .NET Core 3 `UseServiceProviderFactory` should be available for both Web and the general host builders.

**Comment by jasper-d** [comment]
Hi @dadhi,

you're absolutely right. Works like a charm with UseServiceProviderFactory  :)
