### ISSUE TITLE
Resolving last registration from multiple default services

### ISSUE THREAD

**Issue by CoskunSunali** [dadhi/DryIoc#97]
Do you have any opinion on why the following container would return the first registration of a service when multiple registrations exist? That is contrary to what `IServiceProvider` does so I am a bit confused.

```cs
var container = new Container(rules => rules
    .With(FactoryMethod.ConstructorWithResolvableArguments)
    .WithFactorySelector(Rules.SelectLastRegisteredFactory())
    .WithTrackingDisposableTransients()
    .WithCaptureContainerDisposeStackTrace());

container.Register<IService, A>(reuse: Reuse.Singleton);
container.Register<IService, B>(reuse: Reuse.Transient);

var instance = container.Resolve<IService>(); // returns A
```
I am almost certain that you have implemented an option to change this behavior but I cannot find it.

Thanks for your support in advance.

**Comment by CoskunSunali** [comment]
Investigating further discloses that if I register both services as singletons, it works as I expect it. However, if the first registration is singleton and the next one is transient, it resolves using the singleton registration.

You may ask why would I register the same service using different lifetimes. It is not me actually, it is IdentityServer4 but what they do makes sense to me too.

Their `AddIdentityServer` method adds a default in-memory `IPersistedGrantStore` service which is singleton. They also have a method called `AddPersistedGrantStore` where we can set the store service type and they register it as transient this time. 

I would still like to know if there is a way to make DryIoc resolve to the last registration no matter what lifetime is used during registrations.

**Comment by dadhi** [comment]
https://github.com/dadhi/DryIoc/blob/e2ad29ee2d24cb17c243b70e6ec41ee0f004fcc4/docs/DryIoc.Docs/RulesAndDefaultConventions.md#implicit-registration-selection-based-on-scope

This?

**Comment by CoskunSunali** [comment]
Unfortunately I am not able to interfere with scopes used internally within IdentityServer 4.

I am also unable to change the way the services are registered internally. They only call AddSingleton for the default registration and AddTransient for the custom one.

**Comment by dadhi** [comment]
I mean, turn Off the implicit scoped service selection:

```cs
var container = new Container(rules =>
            rules.WithoutImplicitCheckForReuseMatchingScope());
```

**Comment by CoskunSunali** [comment]
I see. Thanks for the lead.

Doesn't that mean I won't be able to take advantage of `Reuse.ScopedTo` in the other parts of the application (shared container) which I would really like to be able to because it is a nice feature of DryIoc?

**Comment by dadhi** [comment]
No, it does not mean that, cause `ScopedTo` requires the specific scope target.

**Comment by CoskunSunali** [comment]
I mean, based on the documentation's example:

```cs
        var container = new Container(rules =>
            rules.WithoutImplicitCheckForReuseMatchingScope());

        container.Register<I, A>(Reuse.ScopedTo("a"));
        container.Register<I, B>(Reuse.ScopedTo("b"));

        using (var scopeB = container.OpenScope("b"))
        {
            // Throws an exception because of the multiple `I` registrations found
            Assert.Throws<ContainerException>(() => scopeB.Resolve<I>());
        }
```

A scope named `b` is opened but resolving the service `I` throws because there is also one registered to scope `a`. We have nothing to do with scope `a` and we are explicitly working in scope `b`. It might be my understanding or ignorance but it seems that `ScopedTo` doesn't have any use case once you call `WithoutImplicitCheckForReuseMatchingScope` because it throws even though `I` registrations are registered to different scopes.

I think the default behavior of ScopedTo, the one without having `WithoutImplicitCheckForReuseMatchingScope` called and the one that resolves `I` to type of `B` seems the correct approach. However, just to get the "resolve to the last one registered" work I am being have to disable the correct approach of named-scope registrations.

Sorry I am struggling to understand.

**Comment by dadhi** [comment]
Hmm, OK. I need to re-check. Maybe there is an issue here.

**Comment by CoskunSunali** [comment]
Thanks in advance!

**Comment by dadhi** [comment]
Yeah :( from this perspective it is a problem.
Essentially it boils down to the place in pipeline where `SelectLastFactory` is inserted. Will think how to fix it in the least breaking manner.

**Comment by CoskunSunali** [comment]
Glad we agree that it is a problem from some perspective. 

Please let me know if you want me to test it when you have a solution.

**Comment by SeriousM** [comment]
> 
> 
> Unfortunately I am not able to interfere with scopes used internally within IdentityServer 4.
> 
> I am also unable to change the way the services are registered internally. They only call AddSingleton for the default registration and AddTransient for the custom one.

I had a similar issue: https://github.com/dadhi/DryIoc/pull/76
Does this help you in any way?

**Comment by dadhi** [comment]
@SeriousM Thanks for more info.
Actually, it should not be a problem with the latest DryIoc.Microsoft.DependencyInjection, because it is already uses option `WithoutImplicitCheckForReuseMatchingScope`.

**Comment by SeriousM** [comment]
you're welcome

**Comment by CoskunSunali** [comment]
@SeriousM I actually don't use the `DryIoc.Microsoft.DependencyInjection` package. I have my own adapter, due to other reasons that doesn't concern DryIoc. Apparently when you use the DI adapter, things should work, as @dadhi said, because it already uses `WithoutImplicitCheckForReuseMatchingScope` but in my case, we are trying to avoid using that option because we really like how `ScopedTo` services work. `ScopedTo` is a brilliant feature of DryIoc that I don't want to give up on :(

**Comment by dadhi** [comment]
Fix is on the way :)

**Comment by CoskunSunali** [comment]
🕺

**Comment by CoskunSunali** [comment]
@SeriousM I forgot to thank you for commenting and sharing what information you have. Thank you too.

**Comment by CoskunSunali** [comment]
So, does your commit mean that when using “select last registered”, the container will work, by default, the same way Microsoft’s service provider works?

**Comment by dadhi** [comment]
Yes, if you are using `Rules.SelectLastRegisteredFactory()`, it will override implicit scope based selection, if you have multiple candidates. Like in case of `Singleton` and `Transient`. 
If you have a single candidate e.g. `ScopedTo`, then it will be selected.

**Comment by CoskunSunali** [comment]
Great work! Thanks for your quick reaction. 

Too much if I ask the release date for 4.0.1?

**Comment by dadhi** [comment]
... in case you have `Singleton` or `Transient` and `ScopedTo`, and all of them can be applied, then the last registered will be selected.

**Comment by dadhi** [comment]
Will release Today or Tomorrow's morning.

**Comment by dadhi** [comment]
It is out.

**Comment by CoskunSunali** [comment]
Great! I’ll go ahead and test it ASAP. 

Thanks a lot for your efforts!
